#----------------------------------------------------------------------
# This file was generated by make.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

down_mini = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAAAcAAAAECAYAAABCxiV9AAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9oMCAc5KTZMU1QAAAAZ"
    "dEVYdENvbW1lbnQAQ3JlYXRlZCB3aXRoIEdJTVBXgQ4XAAAAKUlEQVQI12NkYGD4z4ADMF25"
    "cIIRm8SVCycYmWAMdAkGBgYGJnQBZIUA8pYPlV8OqscAAAAASUVORK5CYII=")
getdown_miniData = down_mini.GetData
getdown_miniImage = down_mini.GetImage
getdown_miniBitmap = down_mini.GetBitmap

#----------------------------------------------------------------------
left_mini = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAAAQAAAAHCAYAAAAvZezQAAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9oMCAc4OEXnQucAAAAZ"
    "dEVYdENvbW1lbnQAQ3JlYXRlZCB3aXRoIEdJTVBXgQ4XAAAANklEQVQI11XMIRbAIAxEwUnO"
    "g6js/RUygvtQBS9dN19srJrOxvPu7IDsgMAF5KoZvwA93tMTP9cJD3g/AmcYAAAAAElFTkSu"
    "QmCC")
getleft_miniData = left_mini.GetData
getleft_miniImage = left_mini.GetImage
getleft_miniBitmap = left_mini.GetBitmap

#----------------------------------------------------------------------
right_mini = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAAAQAAAAHCAYAAAAvZezQAAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9oMCAc5GomcMkIAAAAZ"
    "dEVYdENvbW1lbnQAQ3JlYXRlZCB3aXRoIEdJTVBXgQ4XAAAAN0lEQVQI11WNIQ4AMAgDr7xn"
    "YnL/V0gE/2FmIayu10sqoDJcvBjA2qc+MKGAXj8DIMNls7QxXy5/+A7lc2DVyQAAAABJRU5E"
    "rkJggg==")
getright_miniData = right_mini.GetData
getright_miniImage = right_mini.GetImage
getright_miniBitmap = right_mini.GetBitmap

#----------------------------------------------------------------------
up_mini = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAAAcAAAAECAYAAABCxiV9AAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9oMCAc5CQ0ic5wAAAAZ"
    "dEVYdENvbW1lbnQAQ3JlYXRlZCB3aXRoIEdJTVBXgQ4XAAAAK0lEQVQI12O8cuEEAwzoGFj8"
    "v3LhBCOMz4QsgUzDJZEFkPmMDAwMKBLIAAAj8A2+/239zgAAAABJRU5ErkJggg==")
getup_miniData = up_mini.GetData
getup_miniImage = up_mini.GetImage
getup_miniBitmap = up_mini.GetBitmap

