#----------------------------------------------------------------------
# This file was generated by C:\Dokumente und Einstellungen\Administrator\Eigene Dateien\Entwicklungsumgebung\Skeletons\wxWebAppSkeleton\src\BaseUI\wxApi\res\make.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

error_32 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAABiRJ"
    "REFUWIXFl11sHFcVgL97Z/bX693sbtd2ipOqCU7sQKukFYUigQgv/a+hoZGoqipvfQKpAsED"
    "D0hIvCHEj/pQ3sIDUdOiIqUyqXioEFSUhqit7cRJFJpEruxs1mt77Z3d2Z259/KwM5vZXTtO"
    "ERJXOrozZ+6e852fuXcW/s9D3O3Cs1Bow1Nx234BKQ9qpYpK6yFLSseScsVoveApdUrAzNOw"
    "9j8DOAMTtmX9RsM3SqOjevcXDqUzu8dI5AvEc8O0axu4q6s4yzdZvnCxUSmXLWHMXzxjXpmG"
    "q/81wGmIZ6T8NXDi8w8did//+GPS8j1YWQXHgVYbfA/sGCRiMDQExTzKtvn3zDv6k9m5Fsac"
    "XNT6+y+D95kAZqCEEO/cMzIy9eBLLybjyodrN6DpDqw1/dfpFNw3TtuSfPz7P7irlZUL2pjH"
    "n4GVuwJ4G/JCiLl9U1OjB58/ZnP5Mqxv3NGpMWZAz64cHNzHlTf/5N9YuHzTMeaLx6HW78+K"
    "3pwGKynEu/snJycOHPuWzdw81BuDUQZOdfQ+MmvAuC1MdY3i178izUo15VZXj07DyTf6OGX0"
    "Jivlz0vFwgMTz3/bNnMXO0ZCo8b0iIk4C0WFzsP1TRc1e4l9x56N5YuFwxkpf9afgW4J/gi7"
    "M1IuHH3lezm5uAQbmwOpjc79ujArA2uMgWwGMz7KP377u/WW1pPTUB7IQFrKXx44NJWRbQ9d"
    "2+hGqbeRMEoTZEQFJdERfVgmvVFH+D57Jw9k4lL+YqAEpyGnjZm+95knLHVjcVvHA6WIPgtL"
    "E+hVH4i6vsS9T3zTVsY8NwPZHoAUPFUs5JVQCt1q9zqORKm3iLKrF6IjkfSHOiUlqu0hhCSX"
    "HdYePNYDEBPiu6MT+zOquo6JGNGhESkxUnYNmkCnLQtjWRgpMRG9CtZ3JdD7axsU9+3N2EK8"
    "EALYQcNMpvfuQTcaXUMIAa+/Hi0Xgs9weASjefx4p5mFQDdbpD63G/HRhakeAA2l+EgJU652"
    "iIMMyO2sRoYxBq1191oIgZQSITqooT0A7fnEirswUAp/LwG0MZlYIY9WqpPaIHU7Da01Sqlu"
    "o4UQSil830dr3emVsBeMIZbLoI0Z7gGQQtTbjoOOxW/XewcApVQ38jsBNs6fx6tWO70Si+GW"
    "KwghNsM1NoCAW81KJTeUjKNbrR2N7uS4B7TRwJ+fR6TTxO4fxzUeAio9AMCl+tVrE0NHDmM2"
    "nU4DAu6JE53UGoNfLuNdv45xnO4OF/ZKz+4X2T179I6D5To0NupouNgD4Btzqjx/8WjpS0cy"
    "PU1Tr6MqFfylpc4bss1W26/rBwyfybECtcvXNrUxp3oAXJjZ2Kxb7cVP8P61gDGgWy2M624Z"
    "5d1E3wNkDDKdwMQkjtuygbMhgAQ4DjUhxFvL/5z15X1jeLUaynW7p1u484WiuL3V9m/NoV6F"
    "50Ogjx3YQ/mDBV8a3piGzR4AAFfrHy4vlesmm0bks7edRQ6aAafcPoZVH2AUXOYzkI5TvbVa"
    "9+FHREYX4BgsI8RrV9/9oJF4eBKTjO8YvdoCJgqujcGkEqQemmDxb7OOFOLV6FHcAwBQ1/on"
    "TtOd/fTvH3rJRx/ApBIDqd0q+p5sRaInnWDoywdZem+u7bbaH9W1/il9Y2Brfwt22TBfKOVH"
    "xr92JOacv4S/UuttuC06PKoHsEs5hg7vZ/m9eW+zWltuwoNbfRNuebacgXsEnE2lkof2Hn04"
    "ZRouzQvXUU5z29cwFGs4TWpyHJGK8+lfP256bnuuDU8+B9WtfG17uL0GsTF4VQrxYn60kBh5"
    "5JDEbdG6uYq/7qDdFtpTELOQyQRWLk1sLI+MW9w6d8Wv3Vrz2nDyJPzgDDS287MVgAAywBCQ"
    "+Q5MTsOPs/BIMpVQ2bFCKlnMYg+nsYeSeE6TVq1Be3WD9ZtrTc9tWetw7k341dtwBagDTmTe"
    "ESAdAAxH5z0w9iQ8ehi+moWxBGRsiPvguVBfh8qH8P6f4dxSp9PrdN73cN6k859R3U0J0nS+"
    "28JMpIM5FUgCiNP5X2ECox7gAk06KQ8ldLzZ7/xOANHnscBhCkgGjuOB3gb8CEAbaAWO3UA3"
    "4DQ6/gPnmhBFs5mqXAAAAABJRU5ErkJggg==")
geterror_32Data = error_32.GetData
geterror_32Image = error_32.GetImage
geterror_32Bitmap = error_32.GetBitmap

#----------------------------------------------------------------------
information_32 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH1gUdFDM4pWaDogAABwNJREFUWMPFlltsVNcV"
    "hv+199lnbh7PjAdfMGNDcA04EKMkJlIsBVJVbRqlEVUrqyW0QAtFTVWpjVpFfamUF6K+tCTK"
    "QyXn0jaiShOrbRqRoHJpEEoIEBucENuk2OViPB5f5j5zrvuc3YcMFQ8FPBFVj7S0paN91v+t"
    "f1/OAv7PD9UzeeCpp0KRCrYyHtymoPrgySYAANdyBBr2Peu1agP+NrR/v3nHAb6/52d7wfiv"
    "Wlet11NdvZG21laEwzo0RvA9F4uLi7h08bxxaWLUVp78xSsv/XrwjgAMDDyjRxPWUGOy5Uu9"
    "/VsjEA3I5KvIVQ240gHIh9CA5YkwelIJRATw94NvGpnpK0fL+eDA0NAzzq3ya7cDjCbsoWWr"
    "1j+y4f4vB/41Z8JTeaxqE7hndSNiEeELzn3LkapQdfzJTE5JV/GBb28LHz327lcnzp4ZAvB1"
    "AOpmAvyWtv/g6R9GW1c+uf6Bx0KfzpjoTmnYtDaKtkTAj4aEFBqTnJPUOfciIeG3N4XVQtmy"
    "zl/JuY8/fH9wOjO/smvVmuy5s+8P1w2wa9dP46SLN3sf2ha7uiixaU0Qna06NA6PMXIZQRJB"
    "MiIXRBKABygv3hBQV+bK1dmcoR7d3Bc5c/pk/8YNfYOjo6es/6bDbgbAdLa9uXNj2PYF2pOE"
    "loQGAiRIuUTkME42J7IZweYES+NkckZWWNfseEPAKJtOoWxLu69/c5jpbPtNdW7qPwvsbO1c"
    "F8pVLKxs0+HD94gpl0AOQTlEsDkjizFmMk4WESyNM4NzMgOCVYI6q17OlIp9992ngek769+E"
    "vtfVEI3jWqaKgAgAIAlFLuOwGZHDiTnElGQgF4DvM1LKV7Bdz2NExaCuhQpVm1Y0p5qhvNV1"
    "AyjlRTWhwVM2TMdzgkJzieAQyGGMbMZgfwZBEiBPA3xX+VSouAvBAFeMyDddD7rgpHw/WjcA"
    "Ma0EZScZk5heqFrxiO4BzCGCzYgsBrI4I5sYcxlBKl/5WdOdd6S0gxoLEZEiIq4AnzGq1r0H"
    "iPhYuZRFU1R3FgqWkS1aZQA2gWzOyGQcJudkaAwVR3qz8yXzvCXlzJoViaagrlWCjJnLm8Ja"
    "rli2GNMm6wbwPPO31y6Ollc2N3pcI+fyYjW/8a5EKqQTz5WtdLHsTi1W7Im5vDlcMdxxwVk2"
    "Ys9/pTI3+WhAaIauM+MLbYnlH46MVKVyX6v7Hhg9e2ps3doN32ld0Rlrb1nmmK4stCdCSCUj"
    "Le1NwW6uXJ08m/t2OarBXh0ie0syHu0plKtTFGw8n4o33q1z1XngD7+X3C/uHBkZces7hoAi"
    "1946fPSvtpDlYFdLPDI8mR03HC87frXwFpgqLYuFuzrbkg8m49EeDsqDa+cizXcNpppia5ui"
    "+sYXnn+O29LbOTg4aHzun9GOPT/pDemhf3xzx25DicjkiqaAIs4zhumMRUJaPhzgJZ0LQ5C7"
    "gXjQL1kS0YD+o337nhWlYvHJV178zZ9vlZ/dDuDVl57/2HWt755894hINoYSmZx11TYKCUZK"
    "Cs4cnQuDmGtfvDiRdD3n04aA6J4YHzeLhfLg7cSXBAAA5NPpufS1WFjwkFSelZ6ZLWfn0kli"
    "TDJdue8dO9qenp2d1DVR4cTarlyZJgV5dim5lwTw8sv7c1L6H89cm6FlDcHVhlOJffThsa9d"
    "+ud72y5+cnTn2PjJJ1avjOoESnBiPadOfRDTGT5YSm5tqR2R7Zp7//L6gRPf27NjVaolqS9M"
    "Czh28W6mgDXdKxCNRb/oOlV18O3D1xzXGXpx8LnZO94Tbt/x+MFYouexh7dsQU/PWjRGI+Bc"
    "AyMgm1vAO28fxvj4xOX5jL7u0KEX7DvqAAC0Nucf2rLZhq8Y3njjT8gulOBKDw0NAQjNQT43"
    "5eQWL3iHDk3YS81ZF0B6psI/GbuAXbu+gQf7H4ArPeQWC5jLZKCUhQvjWb2QD3bVk5PVM9nz"
    "5LML8waOH38fekBHIhFDqqMFXd0pnDhxGmMTU3Bd9/X/GQDntO/eezswMPBjaFwAABxH4sKF"
    "q+jt7cX6ni6EQuJbdeWsZ3J3d/PTmqaEYUyhXDZBTEOhWIIQwOi5jzA1eRnZXPFSPO7/bmbG"
    "lLfqhus5BVotRH9/x7rGxtBeIQJPACrMOYNSPpRiUIpnlTIOnzmT+eX8fLH8WZMKF4Csje7n"
    "cUAHEKhFcHq6ZE5OZoc7O3tlc3N33+7dP9c2bXoE09NlO52uHDhyZOTVatUWte+otsTXg2pQ"
    "SwagG6r/jwsAQul0erqjo+OesbGx1tHRUT+fz48dP378j57neQD8mtB1B1TtnV9zo64loJqo"
    "XhtFDUQHEGhvb2/2fZ9nMpliTcAFYNdC1sIBYN1sCeq5Ca9bqtWcu9Fe3FDl9Uqvu3HLjfhv"
    "TUo85WzjhogAAAAASUVORK5CYII=")
getinformation_32Data = information_32.GetData
getinformation_32Image = information_32.GetImage
getinformation_32Bitmap = information_32.GetBitmap

#----------------------------------------------------------------------
warning_32 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAABSZJ"
    "REFUWIXll1toVEcYgL+Zc87u2Yu7MYmrWRuTJuvdiMuqiJd4yYKXgMQKVkSjFR80kFIVJfWC"
    "Wlvpg4h98sXGWGof8iKNICYSo6JgkCBEJRG8ImYThNrNxmaTeM7pQ5IlJkabi0/9YZhhZv7/"
    "//4z/8zPgf+7KCNRLgdlJijXwRyuDTlcxV9hbzv8nQmxMjg+XDtiOEplkG9PSfkztGmTgmFQ"
    "d+FCVzwa3fYN/PHZAcpBaReicW5xcbb64IEQqko8Lc26d/58cxS+/BY6hmJvyEfQBoUpwWCm"
    "W1FErKaGWHU13uRk4QkEUtxQNFR7QwIoB4eiKD9PWbVKbb10CZmaCqmpxCormRYO26QQx85B"
    "0mcD+AeK0xYvHqu1tNDx+DH6gQM4jh0j3tCA3tGBLyfHLuD7zwJwAcYqun44sHy51nr5Msqs"
    "WWj5+djCYdS5c4ldvUr24sU2qarflUL6qAN0wqH0vDy7+fAhXZEI+v79CNmt7igpofPVK5Sm"
    "JvyhkJBwYlQBSiHd7vUWZ86bp8WqqtCWLkVbuBAhBEIItGAQ2+rVxG7cICMY1KTDsekc5Iwa"
    "gIQTmStXis47dzBiMfR9+xCi+wb39s79+zFiMczGRjLmzTMlnBoVgLMwyzF+/Cb/lClq2/Xr"
    "2AoKUKdPxzAMWltbiUajmKaJkpGBY8sW3tbW4g8EVNXrXVEKK0YMoMKp7Px8K15Tg2VZOHbv"
    "BiASiRAMBgkGg0QiEYQQOIuLsRSFrnv3yJo/HxVOW5947D4KUAa57qysvNSUFOVtbS32rVuR"
    "fj9CCFwuV2Kfy+VCCIFMScFVVET7/fukJidLm883rQy+HhaABUII8cvUNWt4W1WFcLvRd+5M"
    "nHl/AOjOB+eOHchx44jX1ZEdCqkSTpaDbcgA5+GrpNmzc9ymKdvr67Hv2oVMSko4cjgcKIqC"
    "oijoup64EdLpxLV3Lx1PnuCVUrgmTfK9hV1DAjgKqlSUk1PCYdl25QrS70cvLEw4SWS+04nT"
    "6XxvXgiBc8MGtKlTaa+rIysnR1Ok/OF38PxngAzY4VuwYKL99WvR8fQpjj17kLqeiL6393g8"
    "eDyeAWBSVfEcOkRXczOOaBRvVpZuDPJEDwD4DVyKrv+UlZurxSorUWfMQC8oGOBcCDHgC/Rd"
    "c4TD2BctIl5fT+bkyTahaXvOw8RPApiwd2Ju7hjZ2EhXSwvOkhKQcoADgIqKCioqKgYcQW9L"
    "OnIEIxZDbWpiXCCABT9+FKAUxtm83pKMUEiLVVejLVqEtmTJB50LIdi2bRuFPbnRd7232efM"
    "wbVuHR2PHjHR77dJXS8sg5mDAihweFJenmrevYvR1oazpGTQ6IQQaJqG7ClI/dd655IOHsSy"
    "LMSLF6QFAib9nugEQClk2Xy+orTsbK3t1i3sa9ei5eQMGr0QgvLyci5evDiocyEEtsxMPNu3"
    "0/nsGRO8XlVzu8NlkNvrV+0T/fHMZcusrtu3MeNx9PXrobUVq8cYQrw3TrRub1h9+v573Bs3"
    "Ej1zBvP5c/zp6dbLhoaTwPy+ANKCfF92thq7dg2A6JYt/fNlxGK8eUNSerryHEJHQT8K8V4A"
    "5ztojty8OeaLzZul1DSwLCzDANPEMozusWFgmWZ33288YK3/nGlixuM0v3xpWfDX0Z4i1Vup"
    "XEWwIgRnJfhGPfQ+YsLr+7DzNFwCuvqWyiRg7DSYoIBu9smPkYqEd4AwIN4ITUAL0A4Da7UC"
    "6ICdEfy2fUBMoAvo7GnWKNoemfwLcAuinuFNL7QAAAAASUVORK5CYII=")
getwarning_32Data = warning_32.GetData
getwarning_32Image = warning_32.GetImage
getwarning_32Bitmap = warning_32.GetBitmap

