#----------------------------------------------------------------------
# This file was generated by D:\Entwicklungsumgebung\Flight Lookout\src\BaseUI\wxApi\res\make.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

delete_22 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABYAAAAWCAYAAADEtGw7AAAABHNCSVQICAgIfAhkiAAAAAlw"
    "SFlzAAAN1wAADdcBQiibeAAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA"
    "AAP6SURBVDiNtZXLa9xVFMc/93d/j/nNTF5Nah+EWkWLLsQquhAEwQoSbYIRWhAFNxUXbtzo"
    "qn9AC8UHFV3oRheVWleKdSfuC61gjbYJxTRpWjMzyWRmfvm97rnXRaYxVhca8cDhXs6B7/me"
    "c885Vznn+D/EB5g6Go1Xq0Mfra+vPQ+o7QAp5UkUVT/Ist5bX32Rlz5AHA+8/9ijhydeefmE"
    "qkQ1ALZmcmdWf+dL07Y+cWr62MLCTxeBz9TkkXAsCKLF9079GJ08+S7tlWU8z/uTau3dYdN/"
    "8T196BDVunD6w1fnz37a3O9p7R975OCE7XRyLl76YTtV6DMX7t53kOGhXaNTR6PnvDCM33j2"
    "mdfj8+fPI2K2Day1pt1u8MLU2/V6beS4LyLVlZUGL05PMzk5ia81mxV0buN++/wHtk6ni1jZ"
    "oaaORC95Wp/5L2y3iu+H1pjisHLO8dqb9ebExFOjURgh4jDiELGUuSUvhDwTilxYTw3rPUOa"
    "lqSpIAaMWKw4xEJpUuLqjSufnO494G/EUatlwWgca5Qn+IECPExkqRiNKS3OhSgqpFlClqYU"
    "paXIhSwTssxgRZOlitUuv0F/QJxTzbLkPk/5iJN+2RzOgbOOWnUvxlh2jT4M+Fz+5VtqQQVT"
    "NglDD61jBmqj9JIqrfbsEoAHIMbdKgpB63CzVs6BtQ6tq9Ti3YRBnetLFwiCOg89OI3CJwhr"
    "1Gt3MTy0h3p9DGsdxtjrm4yNsTfy3KC9COgCEPiDxNEIigrtzjxWNGM7DhD4Mbgc5flUwkGM"
    "sYiUaK3J87QQsUubwEUhN7KsEO3Hmhw8L8TzYsZ3P4nnVbg2/z1JskqzNcfNW1fBaQK/Sll0"
    "KcsCB2gdkmXrxgrLm8BWXKPXSfIwGKxWojGUClBU0V5Es3UFhcaIwRjBiGWgtpNKtAMriyRJ"
    "D3Boz6fXXRNr3R+PZy2NokCicIQsa2JMiadKkrTJcmuGwgjGFKAChgf3styaZ6huSdZXEVv2"
    "F5Gim3QQu5WxpbHaXnMAYkvECnm5ynLrMiMj99PrtsizBfaPP4FSIXFlJ6Y0LN2c668BBziS"
    "pOdb2dJuVmi0220P57BiEGMwYsm7S1hRlCZHeSFBWENKg6d8fl28QJYnOOfQOqQsM8pSQudo"
    "bQKLpZEkWSQ2wzqFsQYxgjGWxsocphBKY5md+w7fH2BhaQZTCtZutGYUxqRZgrMq+/pcPsxZ"
    "VnyAb74sKpNH/Obc7Oyee+49gBjpj7btB3CIbKi1sH/8ccRabu97Y3Jmfr5EkatrwD6llPJv"
    "D8TNxfKdM5+fOy4iQ9v5B63VV67OFB/3hy5XzjmUUgoYAOpA+q9RNyQGCqDjnCt+BzEGY1pX"
    "iXo0AAAAAElFTkSuQmCC")
getdelete_22Data = delete_22.GetData
getdelete_22Image = delete_22.GetImage
getdelete_22Bitmap = delete_22.GetBitmap

#----------------------------------------------------------------------
edit_22 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABYAAAAWCAYAAADEtGw7AAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH1gcFDBUEtI+i2QAAAJF0RVh0Q29tbWVudABU"
    "b29sYmFyLXNpemVkIGljb24KPT09PT09PT09PT09CgooYykgMjAwMyBKYWt1YiAnamltbWFj"
    "JyBTdGVpbmVyLCAKaHR0cDovL2ppbW1hYy5tdXNpY2hhbGwuY3oKCmNyZWF0ZWQgd2l0aCB0"
    "aGUgR0lNUCwKaHR0cDovL3d3dy5naW1wLm9yZxbzvxQAAALTSURBVDjLnZVLTBNBGMd/u1uC"
    "oBxaDzR7MBxIiCf0olcOoiacfMRED+CVgyYk3ognQ0JAQvCiMSoEDoTyiB7QkEh8UHpCRCwP"
    "U4QCCqXYh7SN3dDd8QBbFlkq8E8238xk85v/fDPzDVjk7UAcJeaUtwMhhBBHiXY82dpJLQ9v"
    "xeknh4oWSWbDAdDY1NA1+C0JXOBNoB6o3RM943d3xZ5Pd4BaXvrv0djkFPmf7wNQ121I2Rka"
    "mxrEtSs3GB8fx+VyEY1GcTqdrKysoKoqsViM4uJigsEgqqqytraGqqqEw2EmJiZwLzVT0+Zl"
    "caSX931t1HUbksO07na7qaioAMAwDBRFoby8HEmSEGIrjWVlZciyjGEYAAghcC81c/vRKMsf"
    "upicWdcBJZsKgMLCQjRNA0BRFNsNNscVRSEUCvH1+cUdaCBCdLpfMVORBcvyzj4Gg8GcJ2h9"
    "fZ3Zzipq2rwE33Uy5g+RDLzK5ncX2KqSkpJ9oaurqzvQt518mfu1B7oveD/HWaetW9DpxRjx"
    "mQG0sw+gu57/gu0cZ522elkY6WFqIUrE34fz0gtC4Z97/j+QY9NpdcsI34famfkRJ+Lvp7J+"
    "kvn5+YODrY6FEIy0nKP64UcCQ+3MLMWJzw5QWT8JQCQSsU1bTsdCCDweD5vyeaZ8PhZXfhOf"
    "HeB0zWvC4TBCCHRdPzjYdKzrOuqPFobXSunp66NUHuPU9V5SqRTJZJKioiLS6fS+YNnOsRAC"
    "TdOo6zZovTnH6OZVTpZd5ozLBYDL5ULTtOwt3OYYVvAxO8dCCIQQ2SXf2l6BefskSSKTyeB2"
    "u5kPJtjm/IGtMuoACuyWIkkSkiTZXmlTeXl55Ofnm90CQAN0QHKYRSMWi+Hz+TisLJNbZxUO"
    "IJ3YSAw+ffa4iiMqsZEYBNJmGsx67ABOAEXAcctJkXOwzE3KACkgASS3+7ueEtnycQiw2Tb+"
    "GeMvnmKjxk6hepkAAAAASUVORK5CYII=")
getedit_22Data = edit_22.GetData
getedit_22Image = edit_22.GetImage
getedit_22Bitmap = edit_22.GetBitmap

#----------------------------------------------------------------------
filenew_22 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABYAAAAWCAYAAADEtGw7AAAABmJLR0QA/ADpAE8017ENAAAA"
    "CXBIWXMAAA3XAAAN1wFCKJt4AAAAB3RJTUUH1QISDiUwykMmCQAAAkFJREFUOMutlc1rE2EQ"
    "h5+Z3VSa4gdNmzUInjyIeBLEVvAf8NKDJ2/i1bMIYi+i4sc/4cGLeJDcRREENaUXC3qyudSQ"
    "GCgiMabZZMfDfmZT7Wp9IWR32Pd5Z36/mV1hn2vUWRGgBPiuV7c4LvHF/Yd3bwOrfwNVCagc"
    "GVBb7OGosTPUxxcvNK+5Xr3vZp5bvXH9ZmGomQ/+R4L+S3yrYJTZ/vrpiuG8GnVWnrr5Dc1m"
    "E8dxMDNEBJGwqOw1GCVpUdYXOKVZbOYS4sxzaOE1Fjy7LPZtXfPgGBBDzAzMMDMsMMwAxqj0"
    "ENnBZAF0HlDgADAuA4f3BCNAHFNBFUQcAjlIwCIy2gT/DQQdhoMGYj82gO3fglU1/BdBRNPD"
    "RFFxCDjKgGWGdgKGa7j+czY/byEET4CWuxtYVVONEZCsxgIqCDOYHMOnwphTzM6VaGx858zJ"
    "1gfg51TGa+uNSbMy2Sc/4iocTOcw5zgyc5pev4Tr1fuuV7cp8LmzS9RqtZympHKoRPdRdaJh"
    "VZNjwa5StNvtcJNpKENSPkkVkadED0wt909dYWJJdvleTg4QQSkATjYBGpkVagqi0X0cj5IN"
    "47lxzwfevX87lZFIKEUMzWossQl7gZeXzlOtVtMe1shENDJOEBTVbJdoMY273e5EuzHxnpDk"
    "gGxlhTROT9GMeRGQeMRJ9C8MTrLR1LiIF1uZTqNJpo8LZpy4Ho82k8aFVVAsY8/z+B8rAQdB"
    "cOfBo3u39gP7stW6OvXNy6vwj+zkY/oLI/uTo02YtuAAAAAASUVORK5CYII=")
getfilenew_22Data = filenew_22.GetData
getfilenew_22Image = filenew_22.GetImage
getfilenew_22Bitmap = filenew_22.GetBitmap

#----------------------------------------------------------------------
fileopen_22 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABYAAAAWCAYAAADEtGw7AAAABHNCSVQICAgIfAhkiAAAAAlw"
    "SFlzAAAN1wAADdcBQiibeAAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA"
    "AAMUSURBVDiNnZVPaBxVHMc/b2Z2NlnbImgONiBFiVAEDx6ktYh/0D2IRxFkTHPyVs8evYp4"
    "6kXrQUTMqWfBKIhCam2D/7AXzaGWbEOarUk33Z2defN7v5+H3W5306hJv/CY+THM533f9/3m"
    "jcuyjP9SFcrCORebmXPOAXDnJq2lf/Tz8vk0Tdu730sAvPfx7Ozs4b3A6xut+meffo5zbmIA"
    "LC5+cXzpm6UV4Clg5x7w3Nzc7865xwHbDTYz1tbWKMtyVIcQUFVOn16g0+k8uvLTyoWy759J"
    "07Q/ARaR4/Pz84QQMDNUFQBV5YMP3yeKIi5dvjQx4ckTJwA4c+Ydd+6Tj59cvrB8FuPt3WAT"
    "EddqtRARVBVVxcxwzpGmKc1XmpjZyDVAu91GRHj25Cl38ccf3lDZBQ4hmKo6ERkt884ASJKE"
    "pa+/IoQwcvziCy/hvR8UDlQ1gmgyY5HKRCpCCPjqLlhEwMXgYprNVyfcjl+TpI5ZpOu1l6e+"
    "O3bNZ6ur6rIso9FoyMLCQnzxSovzvwhRdHdmMyNyY/Wu/R3yh6tzwTnXvnzuzaOjjEMIbN5W"
    "nnv6GK+demL0AsCwu/bU+KPcS/zeR9/OZNlbNspYRMhLY2a6zman4PpW/19Qe2uqFvPw4RpR"
    "HHVhsivoVfDYA3UwSMbi2I/UoPSByEWdEbiqBpuXV44jjTpmkMT7B/cKYTqN8V5wEdsj8CCK"
    "QO7hUKMGQLIPblAjLwMSlOm0RtH3ADfHHRNCoKgAHF70HoAaw69yUHtR1CY7pNMrMbUb445V"
    "ROh7wwejWwR6peBF9wTsGUcZs3krR1TXJxxXIvhgbHcrWlt9gv4/bFw7tYitTlFZ0M0RGNC8"
    "DNRrMbf6ghwQClBWxna39Dj39ziYbqE88tARHmwkHJo6WKsBRM7R65VialsAyeLiYtJsNu3P"
    "jZKbnYLvf756YChAMKXby1PpbV8jHjiu53n+5a+r7derRj253SvuA+vMzKTc2Vi+cv7dq78N"
    "T4EacBSYYSya+5Ay+D39lWVZkQACXAduMHmmHFQ2hFcA/wDxAPK+pndhwAAAAABJRU5ErkJg"
    "gg==")
getfileopen_22Data = fileopen_22.GetData
getfileopen_22Image = fileopen_22.GetImage
getfileopen_22Bitmap = fileopen_22.GetBitmap

#----------------------------------------------------------------------
filesave_22 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABYAAAAWCAYAAADEtGw7AAAABHNCSVQICAgIfAhkiAAAABl0"
    "RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAKlSURBVDiNpZXBa1RXFMZ/Z+a9"
    "IKNGGtMuLERScGPblei6oauCkL+g4MbWlS7jRqFQcFEKUtwExFXsuuBKqWg33QTMphsXQhsM"
    "loFAJpqRe/Pu+bq4783MM1am9cDw7rvvvd9895z7nWvnvv35mrt/Bxg5xMF4c+5f3zFwzK4U"
    "7n7t6oUlK4suZ+//AO6GBBKSQA6S4Z7v3UHKHAk19xK/fnWd16Hizr31WwVgHTN++2ObT27f"
    "fIuQ6ePJqct8vngMoFsAltxJyTnx/a33AleDzAEoAFLKS577+tJ7gflpneSTYHe8ngCIMbK1"
    "tTUVa3FxcTSWOz6p2F3Ix4WemZlpfTBtSE6VMqcDUCUh+Ts/mgrsaqXC3L2lOKXE5ubmVLDJ"
    "lbmcVLWK5y3F3W73/6XCRUoJqFORkuP+NjP9V7CTak5dPEfuXPzx92wqyK5C2WD1FVQ/b+YZ"
    "uVCCjhlVlUZgq+pUyCH8vcHwz0dTKTy08AXF/Kc1W8js4D6WC5cY/vWY5eVlZmdnKcuSoigo"
    "y3I0LoqCGCP9fp+1tTV6c6dplulSex+nKjeT5p/n5+cpioLV1dWRupWVFUIIDIdDYoyY5Wbo"
    "KeVxzkUrFaSUcI1N0uv1KMuytezBYECMkRgjIQRijE0xkAsBHVduD02OG6g0Bjfbpond3d0W"
    "tAFnxR0k4UCVJhRXlQNjk+zt7U0oehfYsiCre7Ix7m4GL5/3B0dPHO/xvP9qBAkhHABPQkfP"
    "5Uj14aOxQQrBlxvPXjz87ORHRz/+8AhPgZ2dHUIILC0tsb+/TwiBwWDQAqe6aHOzM5h1AeGC"
    "uJ8AZJI4+83dMwYPBMcWtn/pjk6/N0Jqu9MwNj84D9atT0zLULhhB1426wAlcAg4DByZuAIM"
    "gb2J32sgSmpV+x+v6euDGbT4ywAAAABJRU5ErkJggg==")
getfilesave_22Data = filesave_22.GetData
getfilesave_22Image = filesave_22.GetImage
getfilesave_22Bitmap = filesave_22.GetBitmap

#----------------------------------------------------------------------
help_22 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABYAAAAWCAYAAADEtGw7AAAABHNCSVQICAgIfAhkiAAAABl0"
    "RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAThSURBVDiNjZRrbFRFGIafmTPn"
    "tm2Bgm2XO7tsLZctd+QqAQkksiAmGhISQ1QiKCgmRqReEn8YZUlI0IjIH/gBURMTIyFsAMFy"
    "EaQQJZSWUuhlWwqUNkUotN2223OOP3bboIA4yZv5M/PMl3m/9xOe5/GkFYhEDSAM3ANq4rGi"
    "J14SjwMHItEZwDpgNjAS6ARkWpeBE8DWeKzo5v8Cp6vbDKwNh/wZcyaOJBzyU5jvB6C8uomy"
    "6kZOX6hLllc3JYC34rGi7/8THIhExwIx21S5m15bkLF4Vj7F52oor22iorYZKSSFIT/hUB7z"
    "pwY49PtVoruPtSW6kieAFfFYUcdD4EAkagKV44J5I7/58EVxrryBrXt/ozvpoJSGpkmklAgh"
    "EAIybYN3V85mfDCHd6L7u8qqG/fGY0VvPAq8zbb0NQe3v+7buuckJ87XMX38cF5aOJ4JIT85"
    "2Rkkexwab7dx6EwV+09W4rgeC6YGWLVkEs+v39We6Eoui8eKjvWB00YVf7ZusU/XNT7fdRzT"
    "0Nm46llWLCp8pLk//nqJPbFSHNflvZUzabnbzsdfH2z2PEbHY0VtMn3u7UkFg33PPRNi23en"
    "MU0d09TxgMMl1Xyys5i1Ww7ww5FLfeCF0wLYtoltGew+cIHFM/OZPGZoBhAh3ToAs+dODnCk"
    "pIoex8PQFaahs/dQGTt//pOr1+/QlnA4XXa9D6w0ic82sC0DxxOcq7jJvGmjfcBMABmIRC1g"
    "xIT8wVTEm9F1DUNXGIZCVxqmoWOZBj7bYPXSSX3gi7Ut2JaJZRlYpkFd410KQ34hpZjXW/FE"
    "IFGY76eyrgWlNHRd9ckwUt+ydvlkJj+dB8C1pnvESuqwLQPbNDBNnfqm+4wdlYPneWMBFNAG"
    "SCEEUpMoTUNpEj39gKErXpgbYtqYVEDqm+6z9+hVdENHSImUAgToSqVaEdHZW/FlQFXUNhMO"
    "5iGlRNNSUpqGUhoTQ7l9X1BcehNd17EtA8vUMQwdXSlGD8vm6rUWhBQXAFQ8VuQGItHKippb"
    "E8cFcym5dAMpU2HQpEDTJDv2XcRnG1iWkYLaBj2OiwAcxyWpJMEh/amobnQdxz35YFecOFVa"
    "78yfGsAyVCo5kE6Z4JVFY1gTCfPqogKysyx8tomuNKQmEVJgG4rCYA7FZ6s6gZIHwVtKSusT"
    "Z8sbWL18CgAe4OHheR652T78A33kDrDBc0l0dtPT4+C6Lp7rsXRWkFMX6r3zlTcqgMN94PTo"
    "W//pt790zAwPY0rBYFzXxXU8XNdNvZJeXd09JBJddHYl6U72UDCsPwF/Fh99FetwHHdF76z+"
    "x3QLLo0emVE4ct6295cZ56/c4qfjlQhNwzJ7jVIopSGFQGmCxVOHE/D3Y/3mfR1/XGrYWHtg"
    "045e1r/HZqYQYntWhvnyFxuWZEwfN5TzV25xrfk+N1ra0XWNUf4BjMjLojAwiDNlDd6mLw90"
    "tHd0f/Ag9CEwKcMy/bPejNjZI3bMmRL0zZ8WMsOj80T+iEEAVDf8RXnNLffomSvJs6U1tber"
    "jm1orT52GWj1PK/tkWAhRDYwEBikZ+QM6ReYu9DIzAmbWU8VoDJyBI7rdLY2J1obq7pbGy+3"
    "1hw/Dd5t4A5wG7jpeV7icRUrwAZ8QFZa/YDMtNkJUmm9n97b0+r0HoD9DcIi5yD3PoxAAAAA"
    "AElFTkSuQmCC")
gethelp_22Data = help_22.GetData
gethelp_22Image = help_22.GetImage
gethelp_22Bitmap = help_22.GetBitmap

#----------------------------------------------------------------------
preferences_22 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABYAAAAWCAYAAADEtGw7AAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsRAAALEQF/ZF+RAAAAB3RJTUUH1QkaCxgledlRSQAABAxJREFUOMullX9MlHUc"
    "x1/PcQIp4KGWcoSIzWlWwgmjDe4WhbgWCs5labKmFstq/eFYCxnu25PEUf/QBuTI1ppjLcwt"
    "c9omsWkt2JQfZzupQyV2uziQHpEuQLg7nqc/5Lkd50Ftfbdnez7Pvs9r7+/n834/j0TEEkII"
    "4P258j2gV5bldv7vEkJoo7dHtJmZac3l+k0TQmgVFRXFgPQvr0qAQS8MUTaYmz49gaaqpJrN"
    "7Nu3l4SEhPOAthA8p7wl5YMT59Sc8pZTkWBJCJEFIMvyMGC2133EzPQ9MjIyIlVFQrMA77HD"
    "OzEvZ01OeUu7Dpaqq6tlwCGEOK7DrVYrkvTAgdQogh1dn+2np6eHg/nLCi3p8YUARmBJTEzM"
    "sTcPl2OIiX0XqN6yZQubNm1E01QkScI/M3lFCJEly/K1KGoZGBjA4/Hw4feTAObQ0Zqbm52l"
    "JTufXLr0IQJ+P5qmoWlaCJBkSqa21g5gnmuVDnV0Nr1E3tun9a2W7pNl10JgIURKfHz8r89v"
    "LzQ9/sRTSJIUmpVv/O59+HITtfY6APMF74bVgONq8yvB3De+MgJF3SfL2qMOQwiRlZ6e/rnb"
    "7c7Wn+Xm5ga2bStc8vdf42iaxrLEJFpbW2nqjOXnhhexvnNmnspwrrSIn1MAG9BaVXWUsTsK"
    "12/+wcdn3Xx7vJiCI2cXhAKa9B8CkwU41lqKOXHhBt9U5VP1RTclmwO4XP2WsIHq/Yvuy3DT"
    "K0Mer16vSk3jcv0uDtS1scsSz8slRdTU1OgDHQVmFzV8OHTP9o1kbl6PoozxScsVVqWmUbEj"
    "BbPJyPqMdaQ+moYsywCWSCsaFoO+WmpFnVBINJkotCShDHlw9f6EzWYjPi6WO3/e5v43C4ee"
    "3KhgHfr67kwO7X6Gtos/8GNPPxiMzAaDIa/KsszKh1cjSdKCcEMk9OhrVvYX53H6u3a6+gbJ"
    "s9lwuW4R8E8D4PP5FL/fny3LMitWPQIQgsfFxYXgBj1FypDHK7/1LHu2Z3PqzEUGPV6Kiktw"
    "uW7hdd+ko1/FGBzdUF9ff9dut98YGRmx6spn/H4OHjxAZWUlgCMEVoY8jiNlT1NakEnrucsM"
    "erzYniucBw2M9lqmFHcSsAJY6XQ6A06ns1iWZcypaTQ2NuLz+UKdMOp36evSmFU1RocGH4BO"
    "/N5WoLguBeaEJAOGzs7OIDA8MTGxt6Gh4euxsTFUVb0aCATsoeSte8Gu7cg3Y8m28FiKiV/6"
    "bnG1q4uOfpUp96X80b42JWImaphVZ4EZYBKYBoLArBFgxZqUrec7vL16g+5NTdDRrxJnmCxQ"
    "k1PHASXM9zpQ/6Ooc/CgDp0X6a2HvrSMjQz36nVCYuza660VI+ExDYNKUWKszl0aoP0DjPbe"
    "8WKg6ioAAAAASUVORK5CYII=")
getpreferences_22Data = preferences_22.GetData
getpreferences_22Image = preferences_22.GetImage
getpreferences_22Bitmap = preferences_22.GetBitmap

#----------------------------------------------------------------------
print_22 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABYAAAAWCAYAAADEtGw7AAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH1QsVEgcbRLaZtQAAAvJJREFUOMu1lc9rFEkU"
    "xz/V7iQz6yBRNNntxawxTg456CHiD4RdFGHFk7qKiHqPf0NIwKioB896USTmIKKZ4IKsiEl2"
    "iSQHbzn6Y2FNlB4PM8mY6e7prnoepqedJMPEH/jgUUVX1adeVX9fPfhOpup9zI6O3Af+/EzG"
    "g6NHjh3/rJnZ0REREdFaN3QRkezoiNRj/NBog9nZWXK5HADj409RSnHgwEGUUti2TVtbW+3J"
    "l2xgrRZ9a2srU1PPSKVSJJNJpqaeYds2lmU15KwKvnfvLr7v43le7MPDQyilGnIaXoVSilOn"
    "TqOUIpt9AMCJEyexLGs5OFg14v6Bvp540LJwHAfHcUgkEqxfvyGG1l5F7Zq64P6BvjPA89qI"
    "bdvGtm22b99BZ2cnlmXFXmPPo7VqBTgauDN4/iIAxWIRAGMMWmva239l8+Z2PM/DdV0WFxfj"
    "OV2ZDMCd/oG+01WmWg5dmM8zNjHB+NgYxuiGP/YX2yaTybBn7z7evXvLw78eApy9MHhpuBqt"
    "VM11XflScxxHHMeRmZkZ6R/okyWqmC/kmfjnX3bv3sXGjZuYnp6mu7sbEYnvU2sdn0KMoKxP"
    "yhgauk1Pz86VcnszO8fc3BzpdJrJyUk6OraQTq8FKgoQkVhiOgxjgIihXA7I5/OUy+FKsFIK"
    "EeHC4CBBWEZr8wkmIFHGipiIWIm6KdmE1oZUKkUY1gEXCgW6ujL81NZKYb6ABUikHhEhCAM+"
    "FIuUSi7WGoVSCqWsWO/NTYn6mReGIYKQTq+lOdmM53kgoE0lQqM1LS0bEBHEaIxUTiQiGGMQ"
    "Ufi+H8u4Cr7xdOxJ76E/DvP340df9bBv7djGq9cv8H3/UQwuB8GtpkSid2GhwO+/7V+RshVF"
    "hDWJJUs0HgQhpZLL6/9eksu9vwaIqsm860Dvt5SjIAhvXrl89RwQqDqlKgW0AJuAn4F1wI+R"
    "m2iOAYqAA/wP5IASoKOx+jUvyvc1QCJqk1G/CtbRU+lGrVleQT4CIpSukW+4hbcAAAAASUVO"
    "RK5CYII=")
getprint_22Data = print_22.GetData
getprint_22Image = print_22.GetImage
getprint_22Bitmap = print_22.GetBitmap

#----------------------------------------------------------------------
spreadsheet_22 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABYAAAAWCAYAAADEtGw7AAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAA3XAAAN1wFCKJt4AAAAB3RJTUUH1QYYDQgLwxltPwAAA4BJREFUOMullU9oHFUc"
    "xz+/t7PdyWZnEhPMv02rSTVaujmoKY01mBVPguChIP67BHrQiydRhKpgiMaABw+eRaFSaJFW"
    "KhbaQykpWosg4kZNUiKRzG67VNdkNsnMZud5mNntpk00pQ8e/N6PN5/f933fnxGAyamJ94F3"
    "uIumtR5/+62j725KTk5N6Lttk1MTupFpNA4WFhaIxWJoHc4RBJQAOowlzDVkQDTpdO9tK9gE"
    "FhFEBK3h6tX5CA5L+Tzpnh4AHMchne5BI+Qdh+xodktrtgSLaBzHQUTq8NpYROE4+ZtzldwJ"
    "WEin06RSKQDm5ubIZrOICLlcjkwmA0Aul0PJDsFKKXSg8TwvzKmwUNktg4BSCtd16/PZBqwa"
    "B1d+/KH+gWmaWJaNlbIREWzbxrYb4hY7skL9v+KDB4bp7u7GcRx8z2dVQpUiEqqM1NUUs73g"
    "260oFAoAJMwEKdtCgHw+j21bEPkfKgclipioO9s83/cpu254mkVwy7WYHXls3JqogU3TJGVZ"
    "KIRCASyrhZCjaLFb6hapnSj+/vJ3PHFoBADP81Hi1lW57grXLl2i8MnHLM3NEyyHqv9MJWke"
    "zJAcGqodea217t4Efnz4EB0dHRQKBUxzFynLCleQF3558w3cb85w30vPEh/ZT6CEjSDArwSI"
    "Mtk4/TXHDjx28cmvTr0oIktGVKVuQ7FYRETwPB8RFxFF+eQJjCvTPPDq82yslCgtLlEJAvyq"
    "JtbSRiUIqB4cIP7b0sjZp0Y/AsaM7Z5BM2FiRYqN8+dIv/IM7uJ8HVgJAn7v6ucv36ASbOBL"
    "ldQjXTx48tRh4LVtN2/d9xA3jPm7RNVfw6vehEr3LqyhBJ8Wn8aveAy0pQiqFfZ//mUCaNpS"
    "sUYzOJhBiUKJMNvWTuzeXlhdw7tRpFLVNA8k2bt3ha68Q3r3Q/yav05/8Q/cRMJjfT1uAPUH"
    "urOzc0tbeo8c4efPvqBv7DDt9z+MNgxaR9oJmhTvDQnHF1bYvTjDo6dP4Pf3n2NmRgvAB5Pj"
    "40qpo//167HOnqdpeppKdph4byvmqMbzA8o3Knx7JuC5yxdZ7+v76fXZ2ZeB643XRoAY0Ay0"
    "AhaQjHocMMf27RvNlEov3LO83BVfW41pDRvJZNXr7Ly2uGfPsQ8vXDgOOMA/t95Habg4KgIa"
    "UcFYNI5HxeORjRrwgHLUV4Hqv0lRjKtbp8qOAAAAAElFTkSuQmCC")
getspreadsheet_22Data = spreadsheet_22.GetData
getspreadsheet_22Image = spreadsheet_22.GetImage
getspreadsheet_22Bitmap = spreadsheet_22.GetBitmap

