#----------------------------------------------------------------------
# This file was generated by C:\Dokumente und Einstellungen\Administrator\Eigene Dateien\Entwicklungsumgebung\Flight Lookout\src\BaseUI\wxApi\res\make.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

connect_creating_16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAACBUlEQVQ4jZWSO2hTURjHf+fc"
    "tCGpTTFIm/YODmIa6iClFAexdunig4L1UfCFCE4dhIqD4CTS1aGDBB3UJYM6iA+q+FgUwVcr"
    "GOJobaAaoWiTe5vHPZ9DTNqbGsE/HM7h/M//953zcRARauP2w5m9j168nL00fXN47f6/PM0a"
    "tYXaLm6Lx7f3dPWco0HNPB+g4LrtWmuiHe3hRkAzzwdQShkREBFpBDTzdOPB/5WqAY8cOth3"
    "4MTppzsHd8Rev//kfHj1+CzGCyqF7F64Pt0MEKgtNkQ6Jt0fi7GZ+3fQWocT8a1JI4IYDxZg"
    "JDnpC2afPSCdyqwCPM/TjuMC1RsZcRFjSLy7TN94ApY/robffCWdyjBy45uqA0qlEo5TwBhZ"
    "hZjqbPca+PWlGv6s62HfE8rlMoVCAc8zgCAYhuavVasvRerV7U74bts8OdklPsBK3pN8vkCx"
    "VKRS8fAqJQDSqQxpYJNt0z9mQzRP/8Qg2bl2fw+6e+cv5HIbT2EJARSiNKnW/SgRlGgOZ+9B"
    "Zy9YPWTnMut7kLzydnHfnl0DSkfvKmU2BwItKAWiBMnnIAZYEV/Y9w8AxHiMjo61Lud/bik6"
    "7oBR3FIKhpdmmbpaJOsO+cLrAACVSgXXXeHo8WPdwZZgFqXUmdBz+sYT68K+JtZkWRbhcIjW"
    "lqBjBQJTf86c/1sY4Df2IRlBM8NGSgAAAABJRU5ErkJggg==")
getconnect_creating_16Data = connect_creating_16.GetData
getconnect_creating_16Image = connect_creating_16.GetImage
getconnect_creating_16Bitmap = connect_creating_16.GetBitmap

#----------------------------------------------------------------------
connect_established_16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAACXBIWXMAAAsTAAALEwEAmpwY"
    "AAAKT2lDQ1BQaG90b3Nob3AgSUNDIHByb2ZpbGUAAHjanVNnVFPpFj333vRCS4iAlEtvUhUI"
    "IFJCi4AUkSYqIQkQSoghodkVUcERRUUEG8igiAOOjoCMFVEsDIoK2AfkIaKOg6OIisr74Xuj"
    "a9a89+bN/rXXPues852zzwfACAyWSDNRNYAMqUIeEeCDx8TG4eQuQIEKJHAAEAizZCFz/SMB"
    "APh+PDwrIsAHvgABeNMLCADATZvAMByH/w/qQplcAYCEAcB0kThLCIAUAEB6jkKmAEBGAYCd"
    "mCZTAKAEAGDLY2LjAFAtAGAnf+bTAICd+Jl7AQBblCEVAaCRACATZYhEAGg7AKzPVopFAFgw"
    "ABRmS8Q5ANgtADBJV2ZIALC3AMDOEAuyAAgMADBRiIUpAAR7AGDIIyN4AISZABRG8lc88Suu"
    "EOcqAAB4mbI8uSQ5RYFbCC1xB1dXLh4ozkkXKxQ2YQJhmkAuwnmZGTKBNA/g88wAAKCRFRHg"
    "g/P9eM4Ors7ONo62Dl8t6r8G/yJiYuP+5c+rcEAAAOF0ftH+LC+zGoA7BoBt/qIl7gRoXgug"
    "dfeLZrIPQLUAoOnaV/Nw+H48PEWhkLnZ2eXk5NhKxEJbYcpXff5nwl/AV/1s+X48/Pf14L7i"
    "JIEyXYFHBPjgwsz0TKUcz5IJhGLc5o9H/LcL//wd0yLESWK5WCoU41EScY5EmozzMqUiiUKS"
    "KcUl0v9k4t8s+wM+3zUAsGo+AXuRLahdYwP2SycQWHTA4vcAAPK7b8HUKAgDgGiD4c93/+8/"
    "/UegJQCAZkmScQAAXkQkLlTKsz/HCAAARKCBKrBBG/TBGCzABhzBBdzBC/xgNoRCJMTCQhBC"
    "CmSAHHJgKayCQiiGzbAdKmAv1EAdNMBRaIaTcA4uwlW4Dj1wD/phCJ7BKLyBCQRByAgTYSHa"
    "iAFiilgjjggXmYX4IcFIBBKLJCDJiBRRIkuRNUgxUopUIFVIHfI9cgI5h1xGupE7yAAygvyG"
    "vEcxlIGyUT3UDLVDuag3GoRGogvQZHQxmo8WoJvQcrQaPYw2oefQq2gP2o8+Q8cwwOgYBzPE"
    "bDAuxsNCsTgsCZNjy7EirAyrxhqwVqwDu4n1Y8+xdwQSgUXACTYEd0IgYR5BSFhMWE7YSKgg"
    "HCQ0EdoJNwkDhFHCJyKTqEu0JroR+cQYYjIxh1hILCPWEo8TLxB7iEPENyQSiUMyJ7mQAkmx"
    "pFTSEtJG0m5SI+ksqZs0SBojk8naZGuyBzmULCAryIXkneTD5DPkG+Qh8lsKnWJAcaT4U+Io"
    "UspqShnlEOU05QZlmDJBVaOaUt2ooVQRNY9aQq2htlKvUYeoEzR1mjnNgxZJS6WtopXTGmgX"
    "aPdpr+h0uhHdlR5Ol9BX0svpR+iX6AP0dwwNhhWDx4hnKBmbGAcYZxl3GK+YTKYZ04sZx1Qw"
    "NzHrmOeZD5lvVVgqtip8FZHKCpVKlSaVGyovVKmqpqreqgtV81XLVI+pXlN9rkZVM1PjqQnU"
    "lqtVqp1Q61MbU2epO6iHqmeob1Q/pH5Z/YkGWcNMw09DpFGgsV/jvMYgC2MZs3gsIWsNq4Z1"
    "gTXEJrHN2Xx2KruY/R27iz2qqaE5QzNKM1ezUvOUZj8H45hx+Jx0TgnnKKeX836K3hTvKeIp"
    "G6Y0TLkxZVxrqpaXllirSKtRq0frvTau7aedpr1Fu1n7gQ5Bx0onXCdHZ4/OBZ3nU9lT3acK"
    "pxZNPTr1ri6qa6UbobtEd79up+6Ynr5egJ5Mb6feeb3n+hx9L/1U/W36p/VHDFgGswwkBtsM"
    "zhg8xTVxbzwdL8fb8VFDXcNAQ6VhlWGX4YSRudE8o9VGjUYPjGnGXOMk423GbcajJgYmISZL"
    "TepN7ppSTbmmKaY7TDtMx83MzaLN1pk1mz0x1zLnm+eb15vft2BaeFostqi2uGVJsuRaplnu"
    "trxuhVo5WaVYVVpds0atna0l1rutu6cRp7lOk06rntZnw7Dxtsm2qbcZsOXYBtuutm22fWFn"
    "Yhdnt8Wuw+6TvZN9un2N/T0HDYfZDqsdWh1+c7RyFDpWOt6azpzuP33F9JbpL2dYzxDP2DPj"
    "thPLKcRpnVOb00dnF2e5c4PziIuJS4LLLpc+Lpsbxt3IveRKdPVxXeF60vWdm7Obwu2o26/u"
    "Nu5p7ofcn8w0nymeWTNz0MPIQ+BR5dE/C5+VMGvfrH5PQ0+BZ7XnIy9jL5FXrdewt6V3qvdh"
    "7xc+9j5yn+M+4zw33jLeWV/MN8C3yLfLT8Nvnl+F30N/I/9k/3r/0QCngCUBZwOJgUGBWwL7"
    "+Hp8Ib+OPzrbZfay2e1BjKC5QRVBj4KtguXBrSFoyOyQrSH355jOkc5pDoVQfujW0Adh5mGL"
    "w34MJ4WHhVeGP45wiFga0TGXNXfR3ENz30T6RJZE3ptnMU85ry1KNSo+qi5qPNo3ujS6P8Yu"
    "ZlnM1VidWElsSxw5LiquNm5svt/87fOH4p3iC+N7F5gvyF1weaHOwvSFpxapLhIsOpZATIhO"
    "OJTwQRAqqBaMJfITdyWOCnnCHcJnIi/RNtGI2ENcKh5O8kgqTXqS7JG8NXkkxTOlLOW5hCep"
    "kLxMDUzdmzqeFpp2IG0yPTq9MYOSkZBxQqohTZO2Z+pn5mZ2y6xlhbL+xW6Lty8elQfJa7OQ"
    "rAVZLQq2QqboVFoo1yoHsmdlV2a/zYnKOZarnivN7cyzytuQN5zvn//tEsIS4ZK2pYZLVy0d"
    "WOa9rGo5sjxxedsK4xUFK4ZWBqw8uIq2Km3VT6vtV5eufr0mek1rgV7ByoLBtQFr6wtVCuWF"
    "fevc1+1dT1gvWd+1YfqGnRs+FYmKrhTbF5cVf9go3HjlG4dvyr+Z3JS0qavEuWTPZtJm6ebe"
    "LZ5bDpaql+aXDm4N2dq0Dd9WtO319kXbL5fNKNu7g7ZDuaO/PLi8ZafJzs07P1SkVPRU+lQ2"
    "7tLdtWHX+G7R7ht7vPY07NXbW7z3/T7JvttVAVVN1WbVZftJ+7P3P66Jqun4lvttXa1ObXHt"
    "xwPSA/0HIw6217nU1R3SPVRSj9Yr60cOxx++/p3vdy0NNg1VjZzG4iNwRHnk6fcJ3/ceDTra"
    "dox7rOEH0x92HWcdL2pCmvKaRptTmvtbYlu6T8w+0dbq3nr8R9sfD5w0PFl5SvNUyWna6YLT"
    "k2fyz4ydlZ19fi753GDborZ752PO32oPb++6EHTh0kX/i+c7vDvOXPK4dPKy2+UTV7hXmq86"
    "X23qdOo8/pPTT8e7nLuarrlca7nuer21e2b36RueN87d9L158Rb/1tWeOT3dvfN6b/fF9/Xf"
    "Ft1+cif9zsu72Xcn7q28T7xf9EDtQdlD3YfVP1v+3Njv3H9qwHeg89HcR/cGhYPP/pH1jw9D"
    "BY+Zj8uGDYbrnjg+OTniP3L96fynQ89kzyaeF/6i/suuFxYvfvjV69fO0ZjRoZfyl5O/bXyl"
    "/erA6xmv28bCxh6+yXgzMV70VvvtwXfcdx3vo98PT+R8IH8o/2j5sfVT0Kf7kxmTk/8EA5jz"
    "/GMzLdsAAAAEZ0FNQQAAsY58+1GTAAAAIGNIUk0AAHolAACAgwAA+f8AAIDpAAB1MAAA6mAA"
    "ADqYAAAXb5JfxUYAAAIASURBVHjahNLPaxNBFAfw75uZ3WQ3uyZptPSgLdSKSMFYEP+CgoGC"
    "BxEE6cF/w4PgxYsHwX9A0EvPPUhBpBerJ2+Kegg1qa1amhhLNuvs7PzwVEiL2X5P78Hjw3vM"
    "kHMOR3lyfxE7aQ0f+1Wcm4rmGeOP4zj+kCnzzAy7+mq8hwcvv2A8bLwhAESEPM+9/f2DZq9/"
    "cCsISq0/g8PpNJXg/Ng4AECMN9a6y8bhWhgEdxmyKwQEO93OdZnZF40geG3t4BWAzxOBvfzC"
    "Q1SmWuejsEHOACDoXNdqdb4c+rT8M6EmgNWJgKpebFWiqOHrDDJTEJyDiJw1BrV6nX6L4Gbh"
    "CUIwHQYlEMqIQotSUAIBSNOUgqAMzpk5BRBsbnbu5AwdFb1enwoBrbXZbrcxKVprWwhwxjab"
    "S0v3JgFb77Y2CwEHrHQ63+B5Ar7vw/dLyKSClH9RLpdARCun/ANrkySBcw5CcOt5HpOZglY5"
    "KnEEa60rBpzjKs8hpXTaaBARrLEAHLgvYB1YIeAfbm8kstZKXFg1KiMhBAgEAwetfiCUvzYK"
    "gRnefdQZJuvfB9XblTK7oXM1q63ddeR9apTzN/PV3fWTwLGVGGNfndFrudKrCwuX1sA5MqWe"
    "J6P0DsE9ZYzahRsYY0BEmJ45m43S9O2ZuLoYR/H7/mA4clb+92n/DQDMft8q4PNRpgAAAABJ"
    "RU5ErkJggg==")
getconnect_established_16Data = connect_established_16.GetData
getconnect_established_16Image = connect_established_16.GetImage
getconnect_established_16Bitmap = connect_established_16.GetBitmap

#----------------------------------------------------------------------
connect_no_16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAACXBIWXMAAAsTAAALEwEAmpwY"
    "AAAKT2lDQ1BQaG90b3Nob3AgSUNDIHByb2ZpbGUAAHjanVNnVFPpFj333vRCS4iAlEtvUhUI"
    "IFJCi4AUkSYqIQkQSoghodkVUcERRUUEG8igiAOOjoCMFVEsDIoK2AfkIaKOg6OIisr74Xuj"
    "a9a89+bN/rXXPues852zzwfACAyWSDNRNYAMqUIeEeCDx8TG4eQuQIEKJHAAEAizZCFz/SMB"
    "APh+PDwrIsAHvgABeNMLCADATZvAMByH/w/qQplcAYCEAcB0kThLCIAUAEB6jkKmAEBGAYCd"
    "mCZTAKAEAGDLY2LjAFAtAGAnf+bTAICd+Jl7AQBblCEVAaCRACATZYhEAGg7AKzPVopFAFgw"
    "ABRmS8Q5ANgtADBJV2ZIALC3AMDOEAuyAAgMADBRiIUpAAR7AGDIIyN4AISZABRG8lc88Suu"
    "EOcqAAB4mbI8uSQ5RYFbCC1xB1dXLh4ozkkXKxQ2YQJhmkAuwnmZGTKBNA/g88wAAKCRFRHg"
    "g/P9eM4Ors7ONo62Dl8t6r8G/yJiYuP+5c+rcEAAAOF0ftH+LC+zGoA7BoBt/qIl7gRoXgug"
    "dfeLZrIPQLUAoOnaV/Nw+H48PEWhkLnZ2eXk5NhKxEJbYcpXff5nwl/AV/1s+X48/Pf14L7i"
    "JIEyXYFHBPjgwsz0TKUcz5IJhGLc5o9H/LcL//wd0yLESWK5WCoU41EScY5EmozzMqUiiUKS"
    "KcUl0v9k4t8s+wM+3zUAsGo+AXuRLahdYwP2SycQWHTA4vcAAPK7b8HUKAgDgGiD4c93/+8/"
    "/UegJQCAZkmScQAAXkQkLlTKsz/HCAAARKCBKrBBG/TBGCzABhzBBdzBC/xgNoRCJMTCQhBC"
    "CmSAHHJgKayCQiiGzbAdKmAv1EAdNMBRaIaTcA4uwlW4Dj1wD/phCJ7BKLyBCQRByAgTYSHa"
    "iAFiilgjjggXmYX4IcFIBBKLJCDJiBRRIkuRNUgxUopUIFVIHfI9cgI5h1xGupE7yAAygvyG"
    "vEcxlIGyUT3UDLVDuag3GoRGogvQZHQxmo8WoJvQcrQaPYw2oefQq2gP2o8+Q8cwwOgYBzPE"
    "bDAuxsNCsTgsCZNjy7EirAyrxhqwVqwDu4n1Y8+xdwQSgUXACTYEd0IgYR5BSFhMWE7YSKgg"
    "HCQ0EdoJNwkDhFHCJyKTqEu0JroR+cQYYjIxh1hILCPWEo8TLxB7iEPENyQSiUMyJ7mQAkmx"
    "pFTSEtJG0m5SI+ksqZs0SBojk8naZGuyBzmULCAryIXkneTD5DPkG+Qh8lsKnWJAcaT4U+Io"
    "UspqShnlEOU05QZlmDJBVaOaUt2ooVQRNY9aQq2htlKvUYeoEzR1mjnNgxZJS6WtopXTGmgX"
    "aPdpr+h0uhHdlR5Ol9BX0svpR+iX6AP0dwwNhhWDx4hnKBmbGAcYZxl3GK+YTKYZ04sZx1Qw"
    "NzHrmOeZD5lvVVgqtip8FZHKCpVKlSaVGyovVKmqpqreqgtV81XLVI+pXlN9rkZVM1PjqQnU"
    "lqtVqp1Q61MbU2epO6iHqmeob1Q/pH5Z/YkGWcNMw09DpFGgsV/jvMYgC2MZs3gsIWsNq4Z1"
    "gTXEJrHN2Xx2KruY/R27iz2qqaE5QzNKM1ezUvOUZj8H45hx+Jx0TgnnKKeX836K3hTvKeIp"
    "G6Y0TLkxZVxrqpaXllirSKtRq0frvTau7aedpr1Fu1n7gQ5Bx0onXCdHZ4/OBZ3nU9lT3acK"
    "pxZNPTr1ri6qa6UbobtEd79up+6Ynr5egJ5Mb6feeb3n+hx9L/1U/W36p/VHDFgGswwkBtsM"
    "zhg8xTVxbzwdL8fb8VFDXcNAQ6VhlWGX4YSRudE8o9VGjUYPjGnGXOMk423GbcajJgYmISZL"
    "TepN7ppSTbmmKaY7TDtMx83MzaLN1pk1mz0x1zLnm+eb15vft2BaeFostqi2uGVJsuRaplnu"
    "trxuhVo5WaVYVVpds0atna0l1rutu6cRp7lOk06rntZnw7Dxtsm2qbcZsOXYBtuutm22fWFn"
    "Yhdnt8Wuw+6TvZN9un2N/T0HDYfZDqsdWh1+c7RyFDpWOt6azpzuP33F9JbpL2dYzxDP2DPj"
    "thPLKcRpnVOb00dnF2e5c4PziIuJS4LLLpc+Lpsbxt3IveRKdPVxXeF60vWdm7Obwu2o26/u"
    "Nu5p7ofcn8w0nymeWTNz0MPIQ+BR5dE/C5+VMGvfrH5PQ0+BZ7XnIy9jL5FXrdewt6V3qvdh"
    "7xc+9j5yn+M+4zw33jLeWV/MN8C3yLfLT8Nvnl+F30N/I/9k/3r/0QCngCUBZwOJgUGBWwL7"
    "+Hp8Ib+OPzrbZfay2e1BjKC5QRVBj4KtguXBrSFoyOyQrSH355jOkc5pDoVQfujW0Adh5mGL"
    "w34MJ4WHhVeGP45wiFga0TGXNXfR3ENz30T6RJZE3ptnMU85ry1KNSo+qi5qPNo3ujS6P8Yu"
    "ZlnM1VidWElsSxw5LiquNm5svt/87fOH4p3iC+N7F5gvyF1weaHOwvSFpxapLhIsOpZATIhO"
    "OJTwQRAqqBaMJfITdyWOCnnCHcJnIi/RNtGI2ENcKh5O8kgqTXqS7JG8NXkkxTOlLOW5hCep"
    "kLxMDUzdmzqeFpp2IG0yPTq9MYOSkZBxQqohTZO2Z+pn5mZ2y6xlhbL+xW6Lty8elQfJa7OQ"
    "rAVZLQq2QqboVFoo1yoHsmdlV2a/zYnKOZarnivN7cyzytuQN5zvn//tEsIS4ZK2pYZLVy0d"
    "WOa9rGo5sjxxedsK4xUFK4ZWBqw8uIq2Km3VT6vtV5eufr0mek1rgV7ByoLBtQFr6wtVCuWF"
    "fevc1+1dT1gvWd+1YfqGnRs+FYmKrhTbF5cVf9go3HjlG4dvyr+Z3JS0qavEuWTPZtJm6ebe"
    "LZ5bDpaql+aXDm4N2dq0Dd9WtO319kXbL5fNKNu7g7ZDuaO/PLi8ZafJzs07P1SkVPRU+lQ2"
    "7tLdtWHX+G7R7ht7vPY07NXbW7z3/T7JvttVAVVN1WbVZftJ+7P3P66Jqun4lvttXa1ObXHt"
    "xwPSA/0HIw6217nU1R3SPVRSj9Yr60cOxx++/p3vdy0NNg1VjZzG4iNwRHnk6fcJ3/ceDTra"
    "dox7rOEH0x92HWcdL2pCmvKaRptTmvtbYlu6T8w+0dbq3nr8R9sfD5w0PFl5SvNUyWna6YLT"
    "k2fyz4ydlZ19fi753GDborZ752PO32oPb++6EHTh0kX/i+c7vDvOXPK4dPKy2+UTV7hXmq86"
    "X23qdOo8/pPTT8e7nLuarrlca7nuer21e2b36RueN87d9L158Rb/1tWeOT3dvfN6b/fF9/Xf"
    "Ft1+cif9zsu72Xcn7q28T7xf9EDtQdlD3YfVP1v+3Njv3H9qwHeg89HcR/cGhYPP/pH1jw9D"
    "BY+Zj8uGDYbrnjg+OTniP3L96fynQ89kzyaeF/6i/suuFxYvfvjV69fO0ZjRoZfyl5O/bXyl"
    "/erA6xmv28bCxh6+yXgzMV70VvvtwXfcdx3vo98PT+R8IH8o/2j5sfVT0Kf7kxmTk/8EA5jz"
    "/GMzLdsAAAAEZ0FNQQAAsY58+1GTAAAAIGNIUk0AAHolAACAgwAA+f8AAIDpAAB1MAAA6mAA"
    "ADqYAAAXb5JfxUYAAAKASURBVHjadJO9axRBGId/Mzuzu5fLJn5E7yRKCosoItFLQLASQY2N"
    "lSltDIErtbKwFkEk9f0FNhZ2NulsBAtTmJDAYTCnyd3l4nlf+zGzu/Na3B0xnv5g4GU+HoZ5"
    "5mVEBAB4UXoLALAtc2fKs576YfSMc/6l7QdwpLh6yvNeNbrJqk75GgA8Ly4BADgGYeBg4PBc"
    "+Xi+sHB/TIqHnW4PO5V9hEG4VCjML3quXB7uG0YMC2n1SymYGSCTnx0fBICoPyeFSKVF+DNH"
    "ADcDIgIhJgDg3CIHBMYEGOODU5yEI8EYGwVsfnwPKSXmrhcUADQPa0Y39+CQBSReDACJ7ury"
    "+jpirYFHd48DartbV2zbmWqez88BwEFt/0an01lmjDG/nb0JAL8a1Wv13a1bWqkGgE0AYEML"
    "xWJxzXWcy/lcbtoYQ7bjkCUEN6mBSVOKY824ZaFaq1WVUtulUun2sRtkXHfa87x8Lne2L6U/"
    "jiQNEgTBuU632x15gzAMQ855VD9oZH0/oLGxDAkheJqkSJIEOtbIZrPwfT8KgyAcBSgFblms"
    "5/tot9vQWkFKCa01krQPISKEKkKk1aiFKDKuEMaOkxhKKcSDA2RMXxsR4rEMlCInisgdAUzT"
    "XoXUeLbZ4jNpEoOl6bEPQ2Rw2OphQu1XJqm3MwKYyVRettPMhXLVegKTLoASJqTsLxpCSoBh"
    "7c8zE99eT2b8yggAjH2wOEMaq0+tVnf20uzFB99/7K30er2WY9urRHwj62U3OGdlsH/0wtCc"
    "MVReXLxXPnnCy9fqByunp860pWW9USr+2pf5n14AEYgIjmOjXq9he3trd3zceyeEOIy17jAw"
    "qCTG3/k9ALI0RT57sk02AAAAAElFTkSuQmCC")
getconnect_no_16Data = connect_no_16.GetData
getconnect_no_16Image = connect_no_16.GetImage
getconnect_no_16Bitmap = connect_no_16.GetBitmap

#----------------------------------------------------------------------
delete_16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QAAAAAAAD5Q7t/AAAA"
    "CXBIWXMAAA3XAAAN1wFCKJt4AAAAB3RJTUUH1QQWDyovwTM/8wAAAhxJREFUOMulks9LlGEQ"
    "xz/P+9syNUWyXBQzAunQrYQI+wPqYiLh2im6dokILwndqpvdskMXCUPtFmFE5yQNMrNwxS3L"
    "FQQxZd3d932eeTqYW2EESwPDwDDz4TtfBv4zFEDv5bZuEWe8slW5OTaydNfrSbf3dnScGe3v"
    "G6hofXxi6A5MznjAaH/fAMPDj1hZ/oLjuLiu88/ade4sF7uv8WZ68oWzS5x9N0cQBARBSBju"
    "ZkQURURR1c8aEYYhuZVcWYkHsLDwlqH79yo6YWb65Y6JPen2B8DVrq5T5FYziLWIWIy2aG0x"
    "WohjIUkMOrGIgDYGYwzW2mEF0JNut9dvpFnfmN3xVyybGyWUqsZza1nfWGZrs8B2XlMsGQ7W"
    "HWXq9RRjI4vK+5s8a6GhPkVL8xUA8vkPzH16Tn7fFoWCRbRbni2b6KhfzSONF3DciEz2Idvb"
    "8ziOiwV8r4ooCmlsqN0LULi4TkAY1BGFLaSa0iS6yOLnSTLZVzQ1nkCsYIwhiMK9gMA/gO/X"
    "oJSDBXJr4ygUranzKFyaD3ci1hKXNO5vasseKOVgrcFay+raBPU1nQTeMar3H6Lj+CXez4+h"
    "dYJYQyJmL0CLwVqDiBDH38l+e0YSG5Ty+bjwlLhkEKMRMYjWfwBCgGxmPWltO+kba5FE0CJo"
    "LRQLq6SaTmOMYIwljg3Zpa8J4AOBB8RxSd96/GTkdgWP6BcLySCgfwCHx/uHvBXx4AAAAABJ"
    "RU5ErkJggg==")
getdelete_16Data = delete_16.GetData
getdelete_16Image = delete_16.GetImage
getdelete_16Bitmap = delete_16.GetBitmap

#----------------------------------------------------------------------
edit_16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH1QkWEjcpO1ICSAAAActJREFUOMulk01oE0EU"
    "x38z3aNIFiIt4rHgKaBYKwEPghWEeOxF0LYnr6UXFTyKIMUg9SJ+gJoWijG9WxoRTVwQ7cFi"
    "040bTP3A1WzrEBVakc14MEOzbWorvsv/Dcz7z29m3oP/DGGS4l36gBng2FZ6eIi8qZMAl0cv"
    "nQFmDh532I62ElhNvQHw7fk5tqNXT0rdrDstjdPeVEBZFVjdk6esCvzoethWX0xLBseKHOkf"
    "Bhg3BMTjccSJpT+LfU1lTX3fJ39PMnTtGR+ejDO3EIRAh9V6H6UU9Xp9w0sHQYCbSa0Ve8t8"
    "LU11AD0RA9u2sW07Uuz7Pm4mxeBYkcXHGV6Vl1GlHEDPyGRj9q8E5uSBdIHFfIa5twpVyvFz"
    "/0XOn70wC4hNCbTWFNK9DFx5ijd9h8rn76j5B7zvGqazzTdGCLTWZLNZfslDzDsO7z7VWXo9"
    "Bb1pdq2sANo0oW5LEIYhuz+mefSlm/u5HN3yJTv7bpFMJnFdlzeVBYyLXE9QrVbxPI+RyQZH"
    "Oyus7kgQHhglkUhgWRaWZUW6eANBLBZDa02tVkNrjZQSrTVCCIQQrdsbEQOlFI7jbDp1xmR9"
    "GIOJm7evn/qHKZ4wyW9aneiYeQn8EgAAAABJRU5ErkJggg==")
getedit_16Data = edit_16.GetData
getedit_16Image = edit_16.GetImage
getedit_16Bitmap = edit_16.GetBitmap

#----------------------------------------------------------------------
filenew_16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/ADpAE8017ENAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH1QISDiYc07YZKQAAAWpJREFUOMutkE9LW1EQ"
    "xX9z741WJH0lgtDKWxbc1O5cZqkb8w2ycVm/Rd6y3XcjBMSC38BNN90qhVJKslJKSVqEEP9F"
    "Ypved8eFJsYYk1R6NjMMc+acM1Iul7drtVqREZid/cvcXJtn0W/yy5/f5aJvH+HPvmTDGaVS"
    "Scfh/HhTL0/faOe8oJcnK52LxuKutrLr2jIzrqvSbDYJIQAgIj31jNlj2n4h474iZgnrTCbY"
    "9mrHt1tTzld7BwbJ3WrkCGvqiHmFuAJgMSpG01+L4F66/qyD5OtebzoLTIE4EAuCABduNFkI"
    "Ok/Q59hQRdNpQNC0ot6besamFffQ57uHAq/x4SfgsVoBFO9f6OlZ69PM/PeDkRFEBOUpHV1D"
    "dYE0/QE8YWvn0GxsbL8FcKPItzWL1zwiQhRFNBpJT9QwIfp/0497EYY5eIh8x8GwpcHZsB0z"
    "qd2xEXK5HI+Bi+P4Q5IkxX8hxXH8nv+FK8w9mWB7rBTJAAAAAElFTkSuQmCC")
getfilenew_16Data = filenew_16.GetData
getfilenew_16Image = filenew_16.GetImage
getfilenew_16Bitmap = filenew_16.GetBitmap

#----------------------------------------------------------------------
fileopen_16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAACXBIWXMAAAsTAAALEwEAmpwY"
    "AAAKT2lDQ1BQaG90b3Nob3AgSUNDIHByb2ZpbGUAAHjanVNnVFPpFj333vRCS4iAlEtvUhUI"
    "IFJCi4AUkSYqIQkQSoghodkVUcERRUUEG8igiAOOjoCMFVEsDIoK2AfkIaKOg6OIisr74Xuj"
    "a9a89+bN/rXXPues852zzwfACAyWSDNRNYAMqUIeEeCDx8TG4eQuQIEKJHAAEAizZCFz/SMB"
    "APh+PDwrIsAHvgABeNMLCADATZvAMByH/w/qQplcAYCEAcB0kThLCIAUAEB6jkKmAEBGAYCd"
    "mCZTAKAEAGDLY2LjAFAtAGAnf+bTAICd+Jl7AQBblCEVAaCRACATZYhEAGg7AKzPVopFAFgw"
    "ABRmS8Q5ANgtADBJV2ZIALC3AMDOEAuyAAgMADBRiIUpAAR7AGDIIyN4AISZABRG8lc88Suu"
    "EOcqAAB4mbI8uSQ5RYFbCC1xB1dXLh4ozkkXKxQ2YQJhmkAuwnmZGTKBNA/g88wAAKCRFRHg"
    "g/P9eM4Ors7ONo62Dl8t6r8G/yJiYuP+5c+rcEAAAOF0ftH+LC+zGoA7BoBt/qIl7gRoXgug"
    "dfeLZrIPQLUAoOnaV/Nw+H48PEWhkLnZ2eXk5NhKxEJbYcpXff5nwl/AV/1s+X48/Pf14L7i"
    "JIEyXYFHBPjgwsz0TKUcz5IJhGLc5o9H/LcL//wd0yLESWK5WCoU41EScY5EmozzMqUiiUKS"
    "KcUl0v9k4t8s+wM+3zUAsGo+AXuRLahdYwP2SycQWHTA4vcAAPK7b8HUKAgDgGiD4c93/+8/"
    "/UegJQCAZkmScQAAXkQkLlTKsz/HCAAARKCBKrBBG/TBGCzABhzBBdzBC/xgNoRCJMTCQhBC"
    "CmSAHHJgKayCQiiGzbAdKmAv1EAdNMBRaIaTcA4uwlW4Dj1wD/phCJ7BKLyBCQRByAgTYSHa"
    "iAFiilgjjggXmYX4IcFIBBKLJCDJiBRRIkuRNUgxUopUIFVIHfI9cgI5h1xGupE7yAAygvyG"
    "vEcxlIGyUT3UDLVDuag3GoRGogvQZHQxmo8WoJvQcrQaPYw2oefQq2gP2o8+Q8cwwOgYBzPE"
    "bDAuxsNCsTgsCZNjy7EirAyrxhqwVqwDu4n1Y8+xdwQSgUXACTYEd0IgYR5BSFhMWE7YSKgg"
    "HCQ0EdoJNwkDhFHCJyKTqEu0JroR+cQYYjIxh1hILCPWEo8TLxB7iEPENyQSiUMyJ7mQAkmx"
    "pFTSEtJG0m5SI+ksqZs0SBojk8naZGuyBzmULCAryIXkneTD5DPkG+Qh8lsKnWJAcaT4U+Io"
    "UspqShnlEOU05QZlmDJBVaOaUt2ooVQRNY9aQq2htlKvUYeoEzR1mjnNgxZJS6WtopXTGmgX"
    "aPdpr+h0uhHdlR5Ol9BX0svpR+iX6AP0dwwNhhWDx4hnKBmbGAcYZxl3GK+YTKYZ04sZx1Qw"
    "NzHrmOeZD5lvVVgqtip8FZHKCpVKlSaVGyovVKmqpqreqgtV81XLVI+pXlN9rkZVM1PjqQnU"
    "lqtVqp1Q61MbU2epO6iHqmeob1Q/pH5Z/YkGWcNMw09DpFGgsV/jvMYgC2MZs3gsIWsNq4Z1"
    "gTXEJrHN2Xx2KruY/R27iz2qqaE5QzNKM1ezUvOUZj8H45hx+Jx0TgnnKKeX836K3hTvKeIp"
    "G6Y0TLkxZVxrqpaXllirSKtRq0frvTau7aedpr1Fu1n7gQ5Bx0onXCdHZ4/OBZ3nU9lT3acK"
    "pxZNPTr1ri6qa6UbobtEd79up+6Ynr5egJ5Mb6feeb3n+hx9L/1U/W36p/VHDFgGswwkBtsM"
    "zhg8xTVxbzwdL8fb8VFDXcNAQ6VhlWGX4YSRudE8o9VGjUYPjGnGXOMk423GbcajJgYmISZL"
    "TepN7ppSTbmmKaY7TDtMx83MzaLN1pk1mz0x1zLnm+eb15vft2BaeFostqi2uGVJsuRaplnu"
    "trxuhVo5WaVYVVpds0atna0l1rutu6cRp7lOk06rntZnw7Dxtsm2qbcZsOXYBtuutm22fWFn"
    "Yhdnt8Wuw+6TvZN9un2N/T0HDYfZDqsdWh1+c7RyFDpWOt6azpzuP33F9JbpL2dYzxDP2DPj"
    "thPLKcRpnVOb00dnF2e5c4PziIuJS4LLLpc+Lpsbxt3IveRKdPVxXeF60vWdm7Obwu2o26/u"
    "Nu5p7ofcn8w0nymeWTNz0MPIQ+BR5dE/C5+VMGvfrH5PQ0+BZ7XnIy9jL5FXrdewt6V3qvdh"
    "7xc+9j5yn+M+4zw33jLeWV/MN8C3yLfLT8Nvnl+F30N/I/9k/3r/0QCngCUBZwOJgUGBWwL7"
    "+Hp8Ib+OPzrbZfay2e1BjKC5QRVBj4KtguXBrSFoyOyQrSH355jOkc5pDoVQfujW0Adh5mGL"
    "w34MJ4WHhVeGP45wiFga0TGXNXfR3ENz30T6RJZE3ptnMU85ry1KNSo+qi5qPNo3ujS6P8Yu"
    "ZlnM1VidWElsSxw5LiquNm5svt/87fOH4p3iC+N7F5gvyF1weaHOwvSFpxapLhIsOpZATIhO"
    "OJTwQRAqqBaMJfITdyWOCnnCHcJnIi/RNtGI2ENcKh5O8kgqTXqS7JG8NXkkxTOlLOW5hCep"
    "kLxMDUzdmzqeFpp2IG0yPTq9MYOSkZBxQqohTZO2Z+pn5mZ2y6xlhbL+xW6Lty8elQfJa7OQ"
    "rAVZLQq2QqboVFoo1yoHsmdlV2a/zYnKOZarnivN7cyzytuQN5zvn//tEsIS4ZK2pYZLVy0d"
    "WOa9rGo5sjxxedsK4xUFK4ZWBqw8uIq2Km3VT6vtV5eufr0mek1rgV7ByoLBtQFr6wtVCuWF"
    "fevc1+1dT1gvWd+1YfqGnRs+FYmKrhTbF5cVf9go3HjlG4dvyr+Z3JS0qavEuWTPZtJm6ebe"
    "LZ5bDpaql+aXDm4N2dq0Dd9WtO319kXbL5fNKNu7g7ZDuaO/PLi8ZafJzs07P1SkVPRU+lQ2"
    "7tLdtWHX+G7R7ht7vPY07NXbW7z3/T7JvttVAVVN1WbVZftJ+7P3P66Jqun4lvttXa1ObXHt"
    "xwPSA/0HIw6217nU1R3SPVRSj9Yr60cOxx++/p3vdy0NNg1VjZzG4iNwRHnk6fcJ3/ceDTra"
    "dox7rOEH0x92HWcdL2pCmvKaRptTmvtbYlu6T8w+0dbq3nr8R9sfD5w0PFl5SvNUyWna6YLT"
    "k2fyz4ydlZ19fi753GDborZ752PO32oPb++6EHTh0kX/i+c7vDvOXPK4dPKy2+UTV7hXmq86"
    "X23qdOo8/pPTT8e7nLuarrlca7nuer21e2b36RueN87d9L158Rb/1tWeOT3dvfN6b/fF9/Xf"
    "Ft1+cif9zsu72Xcn7q28T7xf9EDtQdlD3YfVP1v+3Njv3H9qwHeg89HcR/cGhYPP/pH1jw9D"
    "BY+Zj8uGDYbrnjg+OTniP3L96fynQ89kzyaeF/6i/suuFxYvfvjV69fO0ZjRoZfyl5O/bXyl"
    "/erA6xmv28bCxh6+yXgzMV70VvvtwXfcdx3vo98PT+R8IH8o/2j5sfVT0Kf7kxmTk/8EA5jz"
    "/GMzLdsAAAAEZ0FNQQAAsY58+1GTAAAAIGNIUk0AAHolAACAgwAA+f8AAIDpAAB1MAAA6mAA"
    "ADqYAAAXb5JfxUYAAAK2SURBVHjaXJFPbxtFGMZ/s7PejR0ix1CTrIKFEuEolopyKLQ9giLC"
    "JbcIkU+QUxQkDnwFvgNnpJzoLeqpooeocKBIqdQmikpLwREhbf7YZu3d2Zl5ORhbCc9lNO+8"
    "z0/vPK/a2NgAYGdnh5G2t7ffX15erjYajXB3d/fTer1eD4Lg7fJENBWE0fREeXLOx9M8/PXg"
    "IBQRrmp1dbW5ubl5L0mShve+2NrakmazWQc4Sw1PnrchiLn94Rx/db6Pwn6/fw1wfn5+e2Vl"
    "5WatVrtWLwrL3v5v1G7UmZ97Bw/khQsDay3W2nGj1toNBgMPICKICM5aLs7PiAPhvbkbCIp+"
    "AdYjoQw7xwCl1LU/KaWwzmGMwZgc68B48AqcF0KT54RhODY45xjlIiIopcYgAYwd9qA0HiE8"
    "OT7m6eHhGDAa+/93EcFaISsEWxiEmLwQQufctbCMMd57PzaPIQwhaT9DvKUQTZo7wtGII01O"
    "TqqrgNG7eCErDHnhEOfoDgyZ9YRXzXfv3Kmura19mSRJMJpstAXvLSVl6fd69HyJnvV4GQKi"
    "1uJilGWZy7Js4eNbt+7GcUye53jvERG8CHEUU9MFL16/4VJqTJRLeDcEVIBFpVQcaN3IjEFE"
    "MP+dow1ordFRzOvTf7DlCpMTmkBEB0AXOFVBsKCUWlBKlUapa63RWqOCgHKlTDI7Q557Ot2M"
    "l28yTjv5ZQh44E9E0iiK5qvV6ltBEBCGIb1ul9wY2u22Of7j5e8/7x9evKA1/1wqNm3/+Eoq"
    "s1+HAAdHR26p2byfZVm6t7f3wdTUVDNN0+lup/Pg7OLi2ezMzCOt1IP9x7+0Tt6d+a6X3v/b"
    "nTz+pv3TD0/UUrPJwdHReBNfrK8nrVarmiRJZanVejrIsrwUaj5b/ZzWJ+sfXdrKV5FPv331"
    "6N4zgH8HALgyiH/3nwzOAAAAAElFTkSuQmCC")
getfileopen_16Data = fileopen_16.GetData
getfileopen_16Image = fileopen_16.GetImage
getfileopen_16Bitmap = fileopen_16.GetBitmap

#----------------------------------------------------------------------
filesave_16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAABl0"
    "RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAHDSURBVDiNlZO/ixNBFMc/M7u5"
    "hOQUlDRGiCwcXCMoIhyIVoqlhbXYHKJ/g2JnpZ0o/gOihdhYpMmdWKiIWFyrFoFcYeNuk+wy"
    "m533xiJ3+SEnxC8zw4Ph++XzHjyzde/1WxG5yVSBuRbrI/+sta9iEbnxcPsqWx+egqoJqqBK"
    "CGo4rFVBZV6HwM71Bzx78/l2DCAa+P3iMUGEVaXX7gMQA0ZEOPXoOYS/qf+tysssAC+Bk7fu"
    "rmwGkHffFwMUEWE4HK5kTpJkicCIKFEUkSTJ6gRe5wRyMLzBYLCSudvtLs+gOkj7H4LlFryy"
    "/eQjjewrUbF/tMNMn0njDHnrLBunj88JvAhMCqJinyuXL1Gv16nVarNrraUsS/I8Z3f3Pfna"
    "Bt63ALCHOKqKtRHtdpt+v0+v16PZbCIijMdjRqMRRVGAsagqfrEFlYCqYgy0Wq0ZdZqmlGWJ"
    "cw7nHGVZEkIgqFBVC0OcVJ7YTjcky7JZQJZlS2bnHAFQVSrvpwHWmC97P3+d3+ysN8ZZIE1T"
    "Op0O3nvSNF0yO+cgwIljazMCc/HOy3Vj+FS3fvNc/K1uTEwgMD0Hu7GwI4bAnr+Qi6kbkfDj"
    "D/3zDzpnSVtRAAAAAElFTkSuQmCC")
getfilesave_16Data = filesave_16.GetData
getfilesave_16Image = filesave_16.GetImage
getfilesave_16Bitmap = filesave_16.GetBitmap

#----------------------------------------------------------------------
help_16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAABl0"
    "RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAM2SURBVDiNbZNbbFRlFIW/8//n"
    "WlEawIZOofQ27YBOqVOCBU1TLkYt+qKihsSEmBgTKwZJTCdBjGmirRck8UENiRHS+OCDCaBH"
    "I4KO1aAFaRla24Jjp2KdoS1Qe5lpp3bO70NLA8Gd7JedvVfWXllLU0pxYxVvawkAzwB1QHB+"
    "3AVEgNa4G+67cV+7DlC8rUUAjYtyzFd3PrrOvifgE5Xl+QCcv5ik80LCO3Ts18xkeqYJeDvu"
    "hr0FgPnjtvuqikItLz3snIoOcKI9Rk//MABrSvJ4oMbPxrWrCL//9dRPnQMdQG3cDXv6PJPG"
    "TetKQ2/uesjZs/9Lro2l2fvcZir9+aSnZvihI06r28nxX2K8u+cR55UDbvWPHfFGoJmi+uZA"
    "cPt7qb+Hx9TT4U9VUX2zerHliMpmPdXTP6RGx9NKKaVOno6pmp0fqYa3vlCJkXEV3L4/XVTf"
    "HJC5/q0vv/Dkhk2j42nt0LGzABiGzmfHz3PYPUd79188vuVuVi7P5fPvexkZTVG6YgklK5bK"
    "U9E/JwRQV1Xh0060xwCwTJ1Ll8dIXk1hWwZVFT4Arv6TxjB0chyLzt+HCK0uEFKIOh0IBsuW"
    "E72YxDAkpmlgWQaWaRAKFLB7x0aUUhw82oFjWwihkbgyyeriPDylgtdFRAgNQ9cxjbm2TIO9"
    "z9Zi6pLDX0XpuzRKjmMihMCxTDQ0NEAAXV2xy4QCBRiGnGNh6Cy+3WYgOcaZ3gRt0UEc28Sx"
    "LXIck/LCZcQGryGk6BJA5NyFhLdlfRm6LtF1iWHoaELwc/cgp3uTSCmxbWMBpNKfR/cfQ142"
    "60UE0PrxkTOZDWtXsf6ulehSoktB7iKH3U/dS8Nj1eQ4JpZlYtsma4rvpMyXy4HWSEYp1Sri"
    "brhvIpVp2vfBN1OvP7+ZUMCHlAIptQW/G/O6BAqX8ERtKa99+O30RCrTFHfDfTdZeWuNv/qN"
    "hgftaGyYaGyYxJVJbHvu58rSZZTkL6bp4Mlpt63n7My/s7VxN+zdEqY7brP37dpxv11V4dPK"
    "C5eiaRrxxCi/9Y9473zyXWZ8crop63k3h+n/4iylqFNKBQGklF2zs9mIUuqWOP8HZvdMlKLb"
    "imEAAAAASUVORK5CYII=")
gethelp_16Data = help_16.GetData
gethelp_16Image = help_16.GetImage
gethelp_16Bitmap = help_16.GetBitmap

#----------------------------------------------------------------------
preferences_16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH1QkaDBM5i2PCSAAAAfBJREFUOMulkktoE2EU"
    "hb+Z+EyKTRQKgkqwzMaFtt1FrC40FGJm60JwIVSkqLUtElICFQNDQqBrQXRlQIriwomN0GJX"
    "gtI2iUkXFYJVadOXhiBERDozbmaGMR3rwrP7ueece++5P/wnBOcjnVGigArI8Vgi9xdNNJ1R"
    "bI7YUlT7r/YDqKaZq/j6tQHNbLQd6YxiNBp1I51RDPdaw6pFAcR0RolaZKur19vmZhwFePDw"
    "PvFYQgZyACKgDt4cMp4+mzAA9fatETbX15A6Jer1r/das4ndGRUsMYBgFW8MDBqatiXoum7o"
    "ukZhfk4ovC8CyDsFK7R0sBHpu0i5UmG59gUgGY8l7v7zjE68yr80SpUS3Sd7KJYLmBNMArqr"
    "QTCSOgzUrPeVkE7XCYmjR47RbDZ5N/cWtzU8TvH4cJi+UCcdAS/ZmU2Ot39LLn1eOtd9qoeA"
    "P8BKbfnyhfD5+emp11XAABCDkVQXUHs0JjNbXmS2vEjHQR8A5t5yLv8CSZI4e7rX+mR2HiJQ"
    "HB8OM/WmxJamI+7zs1Fv2iOaI8vZJ4850O7nTKgXYMxpAMDuXR72+A7x88cvsvkFgHCrSS6v"
    "Uv1Y/SNsEWBl4zv7fQHa9np4PvMBIPxpcnTaSTRNkmvrqwtA0r5CMJK6BEw4uNvEO+E3N+LV"
    "9uq8VLwAAAAASUVORK5CYII=")
getpreferences_16Data = preferences_16.GetData
getpreferences_16Image = preferences_16.GetImage
getpreferences_16Bitmap = preferences_16.GetBitmap

#----------------------------------------------------------------------
print_16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsRAAALEQF/ZF+RAAAAB3RJTUUH1QsVEg0vn+2FigAAAa1JREFUOMulk82KE0EU"
    "hb97M4u8QHYNWamr0ATjJkQHH8KfdxDBB9AeZ0AQEXREfYZJ8gTJRkbCbLJMVhN3KgQ6fySB"
    "6U6nqlxoGttER7SgFvdS99ThfFXwn0t+LhrN+iEQ/MXc0d079w62uo1m3cVxnNnPXzzL1FEU"
    "uUaz7jYze7vku90uAJ2zUwBeHb+kVt0HoFKpZM7qLoFSqZQOb1bn7BTf93HOZfpbDqy19Ho9"
    "atV9VJWPnQ/cqt1GROj3+5TL5T8LAHieh6oi8j3jYrGIiCAilztwzlEoFNL64YNHKSyR32B8"
    "Ejw+BIJ8Ps/VK9ew1qK6HY+1FhFh8OmcKIoAjjYOgoPgKcYYkiS59BHM5zVUlXfv3wbpNSLC"
    "YDAgjmPa7TbOOcIwZDqdMh6PmUwmjEYjhsMhrVaLr18+ZzNYLBZEFxfMZjN83ycMQwCSJEmt"
    "AxhjGI9ConiVFVBV5osF7XaL5XIJwHq9RkWw1rA2BtUce7kc1drN3RSMMVyv3Ehp/OCCtQ5j"
    "DKqa4t2EnAqsVis8z0ut/sp7Q0FVcc5hrc0InBy/eX3/H37zyTfBI9ln/QvDwwAAAABJRU5E"
    "rkJggg==")
getprint_16Data = print_16.GetData
getprint_16Image = print_16.GetImage
getprint_16Bitmap = print_16.GetBitmap

#----------------------------------------------------------------------
start_16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH1QwGESQhztmtXgAAAiFJREFUOMudk0trEwEU"
    "hc88MskkTSYxmWliExNaSTAjukrR1EhSbIoFwWd0J1gQwUK23fkHXPQXSJeCL7pyo4ggLgxC"
    "TRWxWGygEUr60KQzTTIzuS7EpmIpsXd17uaDc+85QHd4HGC4XToCwAGgCYB6BbC7l/z42Otg"
    "MJgG4OsVwPwRiiwfGT6V+sYwTMeyzC/lD59utlqtz7VaTe/JQjQWk7w+qfjs6RzvkTz+anVl"
    "sr9fGekw9GYgNFCv1Wq0LyCpqpIoOorXCzfYSGSAnTg/wfW53eGN9fXbolNMOkXXu2TyWGN5"
    "ubI3YDiVkjiOKV69co0FAa4+N9SkyqVPpwWXU0z8qP+cNC1rdWhwqLK0tNT8B5DLZqW22S5e"
    "uniZ3dLrMIw2DKMNu8OOeCLB5fPjDiK6QDBTiXj8feZMplEqlcyd3wdkBQ2tDgDQdA0gAgGw"
    "8TZ4PT7opIPIYvyH/IbXE5B4jnUDaO4AFEVG9ftvf7q+BZvNjsPBMCzTxOzsA2vx6+JmLBa9"
    "owRCbwFauzs1ZfyVPlmWySYIAAjR8CB4nsfjJ4+shY8LRjxx9F5mJPuw0+msFgqFFvaKrywr"
    "EAQbdYjw8tULKpfnLbfH8zx7dnRaEOyVXC6r7fXGLkAJQBTtNDNz39J0bWU0O3orIIfmj6vq"
    "xn5B6t4gIGN7u7V5biw1fUI9OQcwm4qiUM9RJqIwAAPAGsMw1n/XkojYg9T5FzBGwR9B4E5i"
    "AAAAAElFTkSuQmCC")
getstart_16Data = start_16.GetData
getstart_16Image = start_16.GetImage
getstart_16Bitmap = start_16.GetBitmap

#----------------------------------------------------------------------
stop_16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH1QwGESgu8tP/wwAAATpJREFUOMvNkl9KAzEQ"
    "h7/spK8WCmY8gFjwFCIeQsRLCOKJRLyCiNcQVARFKYo+rCy0u93dxIf9q62KTxoIzGQyX+Y3"
    "GfjrZXr2xi9zb4BgG280GrG9s3VpjJGfMs/PLsZxHJsPAHWOwWBgTo5Pv03e29/1qkocxwBE"
    "TWDVKSLV47d3VzxO7nl5feYtiUmzFO89ANZanGoLbAGqHUDE1luQSDDAPM/qmKDOLQKcuhYQ"
    "RQIGfAgUZUGapcxm0wpgBbcMsNarIARPWZYUxZwsS5mlU6ZpBbAiaE+C7XrgmDw9AFCWJd57"
    "yqLi+xrYyHPqFgHqOgl5nhMIGCAQ8N63TRQrqFtSgfZ6MF7f/PIbpZMQPlWgiEg4PDr4dg4k"
    "iiLnOkA7ykmS1KMcquNQ2cFUQiq/uREYrgyv+RfrHSlsdbjaRYfOAAAAAElFTkSuQmCC")
getstop_16Data = stop_16.GetData
getstop_16Image = stop_16.GetImage
getstop_16Bitmap = stop_16.GetBitmap

