#----------------------------------------------------------------------
# This file was generated by D:\Entwicklungsumgebung\Librarys\BaseUI\wxApi\res\make.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

connect_creating_22 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABYAAAAWCAYAAADEtGw7AAAKT2lDQ1BQaG90b3Nob3AgSUND"
    "IHByb2ZpbGUAAHjanVNnVFPpFj333vRCS4iAlEtvUhUIIFJCi4AUkSYqIQkQSoghodkVUcER"
    "RUUEG8igiAOOjoCMFVEsDIoK2AfkIaKOg6OIisr74Xuja9a89+bN/rXXPues852zzwfACAyW"
    "SDNRNYAMqUIeEeCDx8TG4eQuQIEKJHAAEAizZCFz/SMBAPh+PDwrIsAHvgABeNMLCADATZvA"
    "MByH/w/qQplcAYCEAcB0kThLCIAUAEB6jkKmAEBGAYCdmCZTAKAEAGDLY2LjAFAtAGAnf+bT"
    "AICd+Jl7AQBblCEVAaCRACATZYhEAGg7AKzPVopFAFgwABRmS8Q5ANgtADBJV2ZIALC3AMDO"
    "EAuyAAgMADBRiIUpAAR7AGDIIyN4AISZABRG8lc88SuuEOcqAAB4mbI8uSQ5RYFbCC1xB1dX"
    "Lh4ozkkXKxQ2YQJhmkAuwnmZGTKBNA/g88wAAKCRFRHgg/P9eM4Ors7ONo62Dl8t6r8G/yJi"
    "YuP+5c+rcEAAAOF0ftH+LC+zGoA7BoBt/qIl7gRoXgugdfeLZrIPQLUAoOnaV/Nw+H48PEWh"
    "kLnZ2eXk5NhKxEJbYcpXff5nwl/AV/1s+X48/Pf14L7iJIEyXYFHBPjgwsz0TKUcz5IJhGLc"
    "5o9H/LcL//wd0yLESWK5WCoU41EScY5EmozzMqUiiUKSKcUl0v9k4t8s+wM+3zUAsGo+AXuR"
    "LahdYwP2SycQWHTA4vcAAPK7b8HUKAgDgGiD4c93/+8//UegJQCAZkmScQAAXkQkLlTKsz/H"
    "CAAARKCBKrBBG/TBGCzABhzBBdzBC/xgNoRCJMTCQhBCCmSAHHJgKayCQiiGzbAdKmAv1EAd"
    "NMBRaIaTcA4uwlW4Dj1wD/phCJ7BKLyBCQRByAgTYSHaiAFiilgjjggXmYX4IcFIBBKLJCDJ"
    "iBRRIkuRNUgxUopUIFVIHfI9cgI5h1xGupE7yAAygvyGvEcxlIGyUT3UDLVDuag3GoRGogvQ"
    "ZHQxmo8WoJvQcrQaPYw2oefQq2gP2o8+Q8cwwOgYBzPEbDAuxsNCsTgsCZNjy7EirAyrxhqw"
    "VqwDu4n1Y8+xdwQSgUXACTYEd0IgYR5BSFhMWE7YSKggHCQ0EdoJNwkDhFHCJyKTqEu0JroR"
    "+cQYYjIxh1hILCPWEo8TLxB7iEPENyQSiUMyJ7mQAkmxpFTSEtJG0m5SI+ksqZs0SBojk8na"
    "ZGuyBzmULCAryIXkneTD5DPkG+Qh8lsKnWJAcaT4U+IoUspqShnlEOU05QZlmDJBVaOaUt2o"
    "oVQRNY9aQq2htlKvUYeoEzR1mjnNgxZJS6WtopXTGmgXaPdpr+h0uhHdlR5Ol9BX0svpR+iX"
    "6AP0dwwNhhWDx4hnKBmbGAcYZxl3GK+YTKYZ04sZx1QwNzHrmOeZD5lvVVgqtip8FZHKCpVK"
    "lSaVGyovVKmqpqreqgtV81XLVI+pXlN9rkZVM1PjqQnUlqtVqp1Q61MbU2epO6iHqmeob1Q/"
    "pH5Z/YkGWcNMw09DpFGgsV/jvMYgC2MZs3gsIWsNq4Z1gTXEJrHN2Xx2KruY/R27iz2qqaE5"
    "QzNKM1ezUvOUZj8H45hx+Jx0TgnnKKeX836K3hTvKeIpG6Y0TLkxZVxrqpaXllirSKtRq0fr"
    "vTau7aedpr1Fu1n7gQ5Bx0onXCdHZ4/OBZ3nU9lT3acKpxZNPTr1ri6qa6UbobtEd79up+6Y"
    "nr5egJ5Mb6feeb3n+hx9L/1U/W36p/VHDFgGswwkBtsMzhg8xTVxbzwdL8fb8VFDXcNAQ6Vh"
    "lWGX4YSRudE8o9VGjUYPjGnGXOMk423GbcajJgYmISZLTepN7ppSTbmmKaY7TDtMx83MzaLN"
    "1pk1mz0x1zLnm+eb15vft2BaeFostqi2uGVJsuRaplnutrxuhVo5WaVYVVpds0atna0l1rut"
    "u6cRp7lOk06rntZnw7Dxtsm2qbcZsOXYBtuutm22fWFnYhdnt8Wuw+6TvZN9un2N/T0HDYfZ"
    "DqsdWh1+c7RyFDpWOt6azpzuP33F9JbpL2dYzxDP2DPjthPLKcRpnVOb00dnF2e5c4PziIuJ"
    "S4LLLpc+Lpsbxt3IveRKdPVxXeF60vWdm7Obwu2o26/uNu5p7ofcn8w0nymeWTNz0MPIQ+BR"
    "5dE/C5+VMGvfrH5PQ0+BZ7XnIy9jL5FXrdewt6V3qvdh7xc+9j5yn+M+4zw33jLeWV/MN8C3"
    "yLfLT8Nvnl+F30N/I/9k/3r/0QCngCUBZwOJgUGBWwL7+Hp8Ib+OPzrbZfay2e1BjKC5QRVB"
    "j4KtguXBrSFoyOyQrSH355jOkc5pDoVQfujW0Adh5mGLw34MJ4WHhVeGP45wiFga0TGXNXfR"
    "3ENz30T6RJZE3ptnMU85ry1KNSo+qi5qPNo3ujS6P8YuZlnM1VidWElsSxw5LiquNm5svt/8"
    "7fOH4p3iC+N7F5gvyF1weaHOwvSFpxapLhIsOpZATIhOOJTwQRAqqBaMJfITdyWOCnnCHcJn"
    "Ii/RNtGI2ENcKh5O8kgqTXqS7JG8NXkkxTOlLOW5hCepkLxMDUzdmzqeFpp2IG0yPTq9MYOS"
    "kZBxQqohTZO2Z+pn5mZ2y6xlhbL+xW6Lty8elQfJa7OQrAVZLQq2QqboVFoo1yoHsmdlV2a/"
    "zYnKOZarnivN7cyzytuQN5zvn//tEsIS4ZK2pYZLVy0dWOa9rGo5sjxxedsK4xUFK4ZWBqw8"
    "uIq2Km3VT6vtV5eufr0mek1rgV7ByoLBtQFr6wtVCuWFfevc1+1dT1gvWd+1YfqGnRs+FYmK"
    "rhTbF5cVf9go3HjlG4dvyr+Z3JS0qavEuWTPZtJm6ebeLZ5bDpaql+aXDm4N2dq0Dd9WtO31"
    "9kXbL5fNKNu7g7ZDuaO/PLi8ZafJzs07P1SkVPRU+lQ27tLdtWHX+G7R7ht7vPY07NXbW7z3"
    "/T7JvttVAVVN1WbVZftJ+7P3P66Jqun4lvttXa1ObXHtxwPSA/0HIw6217nU1R3SPVRSj9Yr"
    "60cOxx++/p3vdy0NNg1VjZzG4iNwRHnk6fcJ3/ceDTradox7rOEH0x92HWcdL2pCmvKaRptT"
    "mvtbYlu6T8w+0dbq3nr8R9sfD5w0PFl5SvNUyWna6YLTk2fyz4ydlZ19fi753GDborZ752PO"
    "32oPb++6EHTh0kX/i+c7vDvOXPK4dPKy2+UTV7hXmq86X23qdOo8/pPTT8e7nLuarrlca7nu"
    "er21e2b36RueN87d9L158Rb/1tWeOT3dvfN6b/fF9/XfFt1+cif9zsu72Xcn7q28T7xf9EDt"
    "QdlD3YfVP1v+3Njv3H9qwHeg89HcR/cGhYPP/pH1jw9DBY+Zj8uGDYbrnjg+OTniP3L96fyn"
    "Q89kzyaeF/6i/suuFxYvfvjV69fO0ZjRoZfyl5O/bXyl/erA6xmv28bCxh6+yXgzMV70Vvvt"
    "wXfcdx3vo98PT+R8IH8o/2j5sfVT0Kf7kxmTk/8EA5jz/GMzLdsAAAAGYktHRAD/AP8A/6C9"
    "p5MAAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfcBQcKJQOAcsW2AAAD0ElEQVQ4y53T"
    "XWwUVRQH8P+5Mzu7/dhud8tusBTLtgUKKQUaiKaKkPBCQmhQQqI+mEiTCqLGyIuaaOILzzxA"
    "LCaNjcRgpVBsoiaSCCFt/YiNyFIopaL9sN2Wdkt3uzsz986d64OaQNkyjefxnnN+OfeeGUKe"
    "OP7xOWJMNEb8bmtOui+93fzKjQfzJ9o+qyvUtC9SNr3mur6+948cVIsNlg9WUL5wgC7UrK+V"
    "hbrWtThfqGtda2trVThAFxSUL5+RF9aZbhiGEVoRiWwiYsUP5o5+cFwjYsXRSKTOMIxSnenG"
    "smGNMWJEUkmllFIPXVMpaEoppVyAEZMaY7RsWBGgFKAAEGHR+5H773MBSkHlZZeAGWNYKohp"
    "oGXU5j09dqgpQwS3oKgYAJz/zr/5aPe6/cMfrvdlxqBnk9Duj6K8tamy4zlsOlWHtQ/taTHa"
    "tG/vxnh1zVOO4L5700lypSw+3NL8cjAU8cUrkqf99buMivRFsIEuPF1GBdq7OxMziRSmOhOn"
    "ARxeEg6Fwu/Zpv18ov8n49Zv/SQEDzLNaE3PzmqVq2cMf1U5cTMEV5pghoAWMzB2feaPqwkc"
    "fezERcHgi3v37NEdwaEUYAQCWrCkJFg5fBJGQQUoOQcfbDjmHGYn7qHnOz++D+6Id2JAPhZ2"
    "hJhPTk2VpVKzICIwpruG5CxG82BPAkpYIJEG3Z/E9PUcqqIxjKUSlufyBOfKsizkciYs0wa3"
    "bQTnfkCoMo6pcRPZdBpKzMBnT2PL1kmUZn/HtXQZf+QnewQWAqZlIZvNAiBoGkPYiOBiTxKR"
    "+UHseSEEFkiB/Dm4C6X46s4qyJWFrufEXDoQnMOybZiWiWwuh7tWFEN6HGtiAZTEF0ArJFAe"
    "wpXLHGLHbjiSe3/Hwnb9jutCSgeO40AIgflMBqGxPtTvXwkKaEB4M5ziBoQ2bsXm22dg2+T3"
    "hENiIc25AOcCjvMP7giBVVENN/r/goV6oKQBetk2MJ5Gb3UzSp1M2hPeFh0+OzR4U2YWsrAs"
    "C5xzOI6DXnMd7v46jUBkNRB9FskfJ9H+cwSDd0awPTr8iefydJInDTJvzqbtQ1I6jYwUpJTw"
    "6ToadhYAQR3WtR60nbqshlDfFy42P9VJXvKc+PX2P0c0UmellMe4zQ/mcrmW2g0bJtLJcQSj"
    "BbBv/YLuE229l3I1B6SU72jkfn6kfWQU/yfeePOtgZbGasWvxNS3r8ZG2vch6NXDvAo6Or7c"
    "PnR7aHTLmjBPdBK6x544060fWPDq07wKLJvLooBGz0TMXV8noz0TRVWt58+fG/fq+xvxJrns"
    "Mm4KfQAAAABJRU5ErkJggg==")
getconnect_creating_22Data = connect_creating_22.GetData
getconnect_creating_22Image = connect_creating_22.GetImage
getconnect_creating_22Bitmap = connect_creating_22.GetBitmap

#----------------------------------------------------------------------
connect_established_22 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABYAAAAWCAYAAADEtGw7AAAACXBIWXMAAAsTAAALEwEAmpwY"
    "AAAKT2lDQ1BQaG90b3Nob3AgSUNDIHByb2ZpbGUAAHjanVNnVFPpFj333vRCS4iAlEtvUhUI"
    "IFJCi4AUkSYqIQkQSoghodkVUcERRUUEG8igiAOOjoCMFVEsDIoK2AfkIaKOg6OIisr74Xuj"
    "a9a89+bN/rXXPues852zzwfACAyWSDNRNYAMqUIeEeCDx8TG4eQuQIEKJHAAEAizZCFz/SMB"
    "APh+PDwrIsAHvgABeNMLCADATZvAMByH/w/qQplcAYCEAcB0kThLCIAUAEB6jkKmAEBGAYCd"
    "mCZTAKAEAGDLY2LjAFAtAGAnf+bTAICd+Jl7AQBblCEVAaCRACATZYhEAGg7AKzPVopFAFgw"
    "ABRmS8Q5ANgtADBJV2ZIALC3AMDOEAuyAAgMADBRiIUpAAR7AGDIIyN4AISZABRG8lc88Suu"
    "EOcqAAB4mbI8uSQ5RYFbCC1xB1dXLh4ozkkXKxQ2YQJhmkAuwnmZGTKBNA/g88wAAKCRFRHg"
    "g/P9eM4Ors7ONo62Dl8t6r8G/yJiYuP+5c+rcEAAAOF0ftH+LC+zGoA7BoBt/qIl7gRoXgug"
    "dfeLZrIPQLUAoOnaV/Nw+H48PEWhkLnZ2eXk5NhKxEJbYcpXff5nwl/AV/1s+X48/Pf14L7i"
    "JIEyXYFHBPjgwsz0TKUcz5IJhGLc5o9H/LcL//wd0yLESWK5WCoU41EScY5EmozzMqUiiUKS"
    "KcUl0v9k4t8s+wM+3zUAsGo+AXuRLahdYwP2SycQWHTA4vcAAPK7b8HUKAgDgGiD4c93/+8/"
    "/UegJQCAZkmScQAAXkQkLlTKsz/HCAAARKCBKrBBG/TBGCzABhzBBdzBC/xgNoRCJMTCQhBC"
    "CmSAHHJgKayCQiiGzbAdKmAv1EAdNMBRaIaTcA4uwlW4Dj1wD/phCJ7BKLyBCQRByAgTYSHa"
    "iAFiilgjjggXmYX4IcFIBBKLJCDJiBRRIkuRNUgxUopUIFVIHfI9cgI5h1xGupE7yAAygvyG"
    "vEcxlIGyUT3UDLVDuag3GoRGogvQZHQxmo8WoJvQcrQaPYw2oefQq2gP2o8+Q8cwwOgYBzPE"
    "bDAuxsNCsTgsCZNjy7EirAyrxhqwVqwDu4n1Y8+xdwQSgUXACTYEd0IgYR5BSFhMWE7YSKgg"
    "HCQ0EdoJNwkDhFHCJyKTqEu0JroR+cQYYjIxh1hILCPWEo8TLxB7iEPENyQSiUMyJ7mQAkmx"
    "pFTSEtJG0m5SI+ksqZs0SBojk8naZGuyBzmULCAryIXkneTD5DPkG+Qh8lsKnWJAcaT4U+Io"
    "UspqShnlEOU05QZlmDJBVaOaUt2ooVQRNY9aQq2htlKvUYeoEzR1mjnNgxZJS6WtopXTGmgX"
    "aPdpr+h0uhHdlR5Ol9BX0svpR+iX6AP0dwwNhhWDx4hnKBmbGAcYZxl3GK+YTKYZ04sZx1Qw"
    "NzHrmOeZD5lvVVgqtip8FZHKCpVKlSaVGyovVKmqpqreqgtV81XLVI+pXlN9rkZVM1PjqQnU"
    "lqtVqp1Q61MbU2epO6iHqmeob1Q/pH5Z/YkGWcNMw09DpFGgsV/jvMYgC2MZs3gsIWsNq4Z1"
    "gTXEJrHN2Xx2KruY/R27iz2qqaE5QzNKM1ezUvOUZj8H45hx+Jx0TgnnKKeX836K3hTvKeIp"
    "G6Y0TLkxZVxrqpaXllirSKtRq0frvTau7aedpr1Fu1n7gQ5Bx0onXCdHZ4/OBZ3nU9lT3acK"
    "pxZNPTr1ri6qa6UbobtEd79up+6Ynr5egJ5Mb6feeb3n+hx9L/1U/W36p/VHDFgGswwkBtsM"
    "zhg8xTVxbzwdL8fb8VFDXcNAQ6VhlWGX4YSRudE8o9VGjUYPjGnGXOMk423GbcajJgYmISZL"
    "TepN7ppSTbmmKaY7TDtMx83MzaLN1pk1mz0x1zLnm+eb15vft2BaeFostqi2uGVJsuRaplnu"
    "trxuhVo5WaVYVVpds0atna0l1rutu6cRp7lOk06rntZnw7Dxtsm2qbcZsOXYBtuutm22fWFn"
    "Yhdnt8Wuw+6TvZN9un2N/T0HDYfZDqsdWh1+c7RyFDpWOt6azpzuP33F9JbpL2dYzxDP2DPj"
    "thPLKcRpnVOb00dnF2e5c4PziIuJS4LLLpc+Lpsbxt3IveRKdPVxXeF60vWdm7Obwu2o26/u"
    "Nu5p7ofcn8w0nymeWTNz0MPIQ+BR5dE/C5+VMGvfrH5PQ0+BZ7XnIy9jL5FXrdewt6V3qvdh"
    "7xc+9j5yn+M+4zw33jLeWV/MN8C3yLfLT8Nvnl+F30N/I/9k/3r/0QCngCUBZwOJgUGBWwL7"
    "+Hp8Ib+OPzrbZfay2e1BjKC5QRVBj4KtguXBrSFoyOyQrSH355jOkc5pDoVQfujW0Adh5mGL"
    "w34MJ4WHhVeGP45wiFga0TGXNXfR3ENz30T6RJZE3ptnMU85ry1KNSo+qi5qPNo3ujS6P8Yu"
    "ZlnM1VidWElsSxw5LiquNm5svt/87fOH4p3iC+N7F5gvyF1weaHOwvSFpxapLhIsOpZATIhO"
    "OJTwQRAqqBaMJfITdyWOCnnCHcJnIi/RNtGI2ENcKh5O8kgqTXqS7JG8NXkkxTOlLOW5hCep"
    "kLxMDUzdmzqeFpp2IG0yPTq9MYOSkZBxQqohTZO2Z+pn5mZ2y6xlhbL+xW6Lty8elQfJa7OQ"
    "rAVZLQq2QqboVFoo1yoHsmdlV2a/zYnKOZarnivN7cyzytuQN5zvn//tEsIS4ZK2pYZLVy0d"
    "WOa9rGo5sjxxedsK4xUFK4ZWBqw8uIq2Km3VT6vtV5eufr0mek1rgV7ByoLBtQFr6wtVCuWF"
    "fevc1+1dT1gvWd+1YfqGnRs+FYmKrhTbF5cVf9go3HjlG4dvyr+Z3JS0qavEuWTPZtJm6ebe"
    "LZ5bDpaql+aXDm4N2dq0Dd9WtO319kXbL5fNKNu7g7ZDuaO/PLi8ZafJzs07P1SkVPRU+lQ2"
    "7tLdtWHX+G7R7ht7vPY07NXbW7z3/T7JvttVAVVN1WbVZftJ+7P3P66Jqun4lvttXa1ObXHt"
    "xwPSA/0HIw6217nU1R3SPVRSj9Yr60cOxx++/p3vdy0NNg1VjZzG4iNwRHnk6fcJ3/ceDTra"
    "dox7rOEH0x92HWcdL2pCmvKaRptTmvtbYlu6T8w+0dbq3nr8R9sfD5w0PFl5SvNUyWna6YLT"
    "k2fyz4ydlZ19fi753GDborZ752PO32oPb++6EHTh0kX/i+c7vDvOXPK4dPKy2+UTV7hXmq86"
    "X23qdOo8/pPTT8e7nLuarrlca7nuer21e2b36RueN87d9L158Rb/1tWeOT3dvfN6b/fF9/Xf"
    "Ft1+cif9zsu72Xcn7q28T7xf9EDtQdlD3YfVP1v+3Njv3H9qwHeg89HcR/cGhYPP/pH1jw9D"
    "BY+Zj8uGDYbrnjg+OTniP3L96fynQ89kzyaeF/6i/suuFxYvfvjV69fO0ZjRoZfyl5O/bXyl"
    "/erA6xmv28bCxh6+yXgzMV70VvvtwXfcdx3vo98PT+R8IH8o/2j5sfVT0Kf7kxmTk/8EA5jz"
    "/GMzLdsAAAAEZ0FNQQAAsY58+1GTAAAAIGNIUk0AAHolAACAgwAA+f8AAIDpAAB1MAAA6mAA"
    "ADqYAAAXb5JfxUYAAAMMSURBVHjapJXNi1xFFMXPrVdVr1/3dFozM2ntQZKJw4CCIqhgcKUg"
    "Y1yIkcGP4EYX2celq4D/gPoPRAUX0YBjFsYILhRFEXXlB2SYD2cyhhl7ptPdY7/3qurWdZFE"
    "N4b0wwO1PD9unbp1L4kIbqeXXj65KILnAfySpum77793dut2HoUxlOf5/cPh4ES73V6YPXKk"
    "NY5H37LKE0+rrT2eA8LhyP5hENW63e3OoN8/9sijj/81O9O48tHS53wrP/1XFG+9Oj//bf/e"
    "F3sj/QQh3AVIRxG1jE4KH+SK57g+OaG+fqy1/OHps5d/G7vi7XzydZO1npvKdDtRANH1xDiE"
    "GkeZS7SeU/AP7eQHZwCcGhu84TsLR+fn2zs72xAR4OaliIQAEBEdak9Prf7sn6yUsbN1Sa0V"
    "qw2xCBKloJMEUAT2QThGWGPhbSNWAk+kKk/TFI16AyCCsQbWGhCAoijhnKPUplKvqaISuJ41"
    "zESjQRwYiVIw1sJoDQGoLAry3qHZnEA9q9tKYFNLVZZayXVC2lhJ0xq00SIQEkRAmGrWwqap"
    "qgTeHwzi9z/8uJ+oJBFIFJFIRP+0KAHJyto6O+ek4gehr44ff+YVUqQARALiDQLdOKooyvDZ"
    "xU+/qRaF0S/s7f5pu90uZVkmtXpDCATvPMryesaTkweb2phFAK+NDWbmmBclSuchIHAUBQAh"
    "BHjnwcwY5YVE5mpRMHMcDofo9XpiUytZmkKIyDkP7xwkCrQ1YOZqfRyiJKUrMcpzFGWJkR5B"
    "oiDEiBgZCRFKdwAhiq4EVhzIeUeBGQgBpQNB/n0+JoIrHSkO1cbm3eHyB6srflFgpjh4UkpB"
    "aw0IECWCBdgfLu8cjmvnK4Gna723l/vT270hH7NGzSaK7gnMtRjjNZDaEiRXW1n88tAde+cq"
    "zWMAWHx2IVm/uj/z4AP3PVUUozc2NjePisgFlZh3gOT3zp1m9dzSxVh5g5y/cIkBbJw58+Z3"
    "u3u7f1zrDzrGmJ8+Wfr4i/+1mm5qZW2178ryUrN5YJMIv2JM/T0AxOt+lDjUYbsAAAAASUVO"
    "RK5CYII=")
getconnect_established_22Data = connect_established_22.GetData
getconnect_established_22Image = connect_established_22.GetImage
getconnect_established_22Bitmap = connect_established_22.GetBitmap

#----------------------------------------------------------------------
connect_no_22 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABYAAAAWCAYAAADEtGw7AAAACXBIWXMAAAsTAAALEwEAmpwY"
    "AAAKT2lDQ1BQaG90b3Nob3AgSUNDIHByb2ZpbGUAAHjanVNnVFPpFj333vRCS4iAlEtvUhUI"
    "IFJCi4AUkSYqIQkQSoghodkVUcERRUUEG8igiAOOjoCMFVEsDIoK2AfkIaKOg6OIisr74Xuj"
    "a9a89+bN/rXXPues852zzwfACAyWSDNRNYAMqUIeEeCDx8TG4eQuQIEKJHAAEAizZCFz/SMB"
    "APh+PDwrIsAHvgABeNMLCADATZvAMByH/w/qQplcAYCEAcB0kThLCIAUAEB6jkKmAEBGAYCd"
    "mCZTAKAEAGDLY2LjAFAtAGAnf+bTAICd+Jl7AQBblCEVAaCRACATZYhEAGg7AKzPVopFAFgw"
    "ABRmS8Q5ANgtADBJV2ZIALC3AMDOEAuyAAgMADBRiIUpAAR7AGDIIyN4AISZABRG8lc88Suu"
    "EOcqAAB4mbI8uSQ5RYFbCC1xB1dXLh4ozkkXKxQ2YQJhmkAuwnmZGTKBNA/g88wAAKCRFRHg"
    "g/P9eM4Ors7ONo62Dl8t6r8G/yJiYuP+5c+rcEAAAOF0ftH+LC+zGoA7BoBt/qIl7gRoXgug"
    "dfeLZrIPQLUAoOnaV/Nw+H48PEWhkLnZ2eXk5NhKxEJbYcpXff5nwl/AV/1s+X48/Pf14L7i"
    "JIEyXYFHBPjgwsz0TKUcz5IJhGLc5o9H/LcL//wd0yLESWK5WCoU41EScY5EmozzMqUiiUKS"
    "KcUl0v9k4t8s+wM+3zUAsGo+AXuRLahdYwP2SycQWHTA4vcAAPK7b8HUKAgDgGiD4c93/+8/"
    "/UegJQCAZkmScQAAXkQkLlTKsz/HCAAARKCBKrBBG/TBGCzABhzBBdzBC/xgNoRCJMTCQhBC"
    "CmSAHHJgKayCQiiGzbAdKmAv1EAdNMBRaIaTcA4uwlW4Dj1wD/phCJ7BKLyBCQRByAgTYSHa"
    "iAFiilgjjggXmYX4IcFIBBKLJCDJiBRRIkuRNUgxUopUIFVIHfI9cgI5h1xGupE7yAAygvyG"
    "vEcxlIGyUT3UDLVDuag3GoRGogvQZHQxmo8WoJvQcrQaPYw2oefQq2gP2o8+Q8cwwOgYBzPE"
    "bDAuxsNCsTgsCZNjy7EirAyrxhqwVqwDu4n1Y8+xdwQSgUXACTYEd0IgYR5BSFhMWE7YSKgg"
    "HCQ0EdoJNwkDhFHCJyKTqEu0JroR+cQYYjIxh1hILCPWEo8TLxB7iEPENyQSiUMyJ7mQAkmx"
    "pFTSEtJG0m5SI+ksqZs0SBojk8naZGuyBzmULCAryIXkneTD5DPkG+Qh8lsKnWJAcaT4U+Io"
    "UspqShnlEOU05QZlmDJBVaOaUt2ooVQRNY9aQq2htlKvUYeoEzR1mjnNgxZJS6WtopXTGmgX"
    "aPdpr+h0uhHdlR5Ol9BX0svpR+iX6AP0dwwNhhWDx4hnKBmbGAcYZxl3GK+YTKYZ04sZx1Qw"
    "NzHrmOeZD5lvVVgqtip8FZHKCpVKlSaVGyovVKmqpqreqgtV81XLVI+pXlN9rkZVM1PjqQnU"
    "lqtVqp1Q61MbU2epO6iHqmeob1Q/pH5Z/YkGWcNMw09DpFGgsV/jvMYgC2MZs3gsIWsNq4Z1"
    "gTXEJrHN2Xx2KruY/R27iz2qqaE5QzNKM1ezUvOUZj8H45hx+Jx0TgnnKKeX836K3hTvKeIp"
    "G6Y0TLkxZVxrqpaXllirSKtRq0frvTau7aedpr1Fu1n7gQ5Bx0onXCdHZ4/OBZ3nU9lT3acK"
    "pxZNPTr1ri6qa6UbobtEd79up+6Ynr5egJ5Mb6feeb3n+hx9L/1U/W36p/VHDFgGswwkBtsM"
    "zhg8xTVxbzwdL8fb8VFDXcNAQ6VhlWGX4YSRudE8o9VGjUYPjGnGXOMk423GbcajJgYmISZL"
    "TepN7ppSTbmmKaY7TDtMx83MzaLN1pk1mz0x1zLnm+eb15vft2BaeFostqi2uGVJsuRaplnu"
    "trxuhVo5WaVYVVpds0atna0l1rutu6cRp7lOk06rntZnw7Dxtsm2qbcZsOXYBtuutm22fWFn"
    "Yhdnt8Wuw+6TvZN9un2N/T0HDYfZDqsdWh1+c7RyFDpWOt6azpzuP33F9JbpL2dYzxDP2DPj"
    "thPLKcRpnVOb00dnF2e5c4PziIuJS4LLLpc+Lpsbxt3IveRKdPVxXeF60vWdm7Obwu2o26/u"
    "Nu5p7ofcn8w0nymeWTNz0MPIQ+BR5dE/C5+VMGvfrH5PQ0+BZ7XnIy9jL5FXrdewt6V3qvdh"
    "7xc+9j5yn+M+4zw33jLeWV/MN8C3yLfLT8Nvnl+F30N/I/9k/3r/0QCngCUBZwOJgUGBWwL7"
    "+Hp8Ib+OPzrbZfay2e1BjKC5QRVBj4KtguXBrSFoyOyQrSH355jOkc5pDoVQfujW0Adh5mGL"
    "w34MJ4WHhVeGP45wiFga0TGXNXfR3ENz30T6RJZE3ptnMU85ry1KNSo+qi5qPNo3ujS6P8Yu"
    "ZlnM1VidWElsSxw5LiquNm5svt/87fOH4p3iC+N7F5gvyF1weaHOwvSFpxapLhIsOpZATIhO"
    "OJTwQRAqqBaMJfITdyWOCnnCHcJnIi/RNtGI2ENcKh5O8kgqTXqS7JG8NXkkxTOlLOW5hCep"
    "kLxMDUzdmzqeFpp2IG0yPTq9MYOSkZBxQqohTZO2Z+pn5mZ2y6xlhbL+xW6Lty8elQfJa7OQ"
    "rAVZLQq2QqboVFoo1yoHsmdlV2a/zYnKOZarnivN7cyzytuQN5zvn//tEsIS4ZK2pYZLVy0d"
    "WOa9rGo5sjxxedsK4xUFK4ZWBqw8uIq2Km3VT6vtV5eufr0mek1rgV7ByoLBtQFr6wtVCuWF"
    "fevc1+1dT1gvWd+1YfqGnRs+FYmKrhTbF5cVf9go3HjlG4dvyr+Z3JS0qavEuWTPZtJm6ebe"
    "LZ5bDpaql+aXDm4N2dq0Dd9WtO319kXbL5fNKNu7g7ZDuaO/PLi8ZafJzs07P1SkVPRU+lQ2"
    "7tLdtWHX+G7R7ht7vPY07NXbW7z3/T7JvttVAVVN1WbVZftJ+7P3P66Jqun4lvttXa1ObXHt"
    "xwPSA/0HIw6217nU1R3SPVRSj9Yr60cOxx++/p3vdy0NNg1VjZzG4iNwRHnk6fcJ3/ceDTra"
    "dox7rOEH0x92HWcdL2pCmvKaRptTmvtbYlu6T8w+0dbq3nr8R9sfD5w0PFl5SvNUyWna6YLT"
    "k2fyz4ydlZ19fi753GDborZ752PO32oPb++6EHTh0kX/i+c7vDvOXPK4dPKy2+UTV7hXmq86"
    "X23qdOo8/pPTT8e7nLuarrlca7nuer21e2b36RueN87d9L158Rb/1tWeOT3dvfN6b/fF9/Xf"
    "Ft1+cif9zsu72Xcn7q28T7xf9EDtQdlD3YfVP1v+3Njv3H9qwHeg89HcR/cGhYPP/pH1jw9D"
    "BY+Zj8uGDYbrnjg+OTniP3L96fynQ89kzyaeF/6i/suuFxYvfvjV69fO0ZjRoZfyl5O/bXyl"
    "/erA6xmv28bCxh6+yXgzMV70VvvtwXfcdx3vo98PT+R8IH8o/2j5sfVT0Kf7kxmTk/8EA5jz"
    "/GMzLdsAAAAEZ0FNQQAAsY58+1GTAAAAIGNIUk0AAHolAACAgwAA+f8AAIDpAAB1MAAA6mAA"
    "ADqYAAAXb5JfxUYAAAOTSURBVHjajJVPaFxVFMa/c999b2byZpo40yxshFITrZRKu6gUBgR3"
    "gvgHQVAiFfxTsAsVpRv3gltRQRGkSItFtFFcCCJYpTVWwYVWG1uLpYFKbTKTJpN58+bee85x"
    "MYmNydjJgbu5HH73Ox/nnEuqivXx+rufkDG+Xi3qO1ngyfv3b/8173p8+s0MFhYzjG+/dXdq"
    "ow8bOR0SiacB6KvPP/YfhkGfUGhcLZkTE3fulDS2U+eveJz86U94zwAUaWynJnbeRdWSmVJo"
    "3E9cX7A1NkmSZGRrtXo3kSk3l4E/ZhtwQSAqERGVR6vV3UmSjFhjE0PRRkY/cGQMGdKgrFZV"
    "tZBESOIYAkAVkSpUBTBEITJEwCYVKwGq/6YrKWA0gAAAJCt29XIIIMLmwMbcuCb0oHG2AKMA"
    "mQi0LpeiaHPgV55+qEUELaVlgBDO/nASkSHYbB4hWwoAfCmtgAjauPxz6+zpzwd7/MjDD+7a"
    "MT6xf8++ejx37SoJc7kx//dkZbgaK+dKTo0IV+auXUUIPs6WGs9en/vrewDn1nJofas8deDA"
    "0TQtP1oslYasteS989653BhjtBcUJ0khjhMbQtA873SWW63Pjh479uRNFaeVyhP31uvWuy5U"
    "FYXSkBkeGakwM0QEEEXWydDtZCAiSorFoW9PnZ4EcHNw8H4x63RqzWYDRARjFrXZbEJEISJr"
    "ToCqolarIXi/ONBj75zmeY4s6yAyEaxlGAJEFaoKZoEwI4QAFkaaduGd08Fg79HJc7TbbQCE"
    "KDJQbAEzg5nhQwCHAGYBoChXKvDeD+4KxwHeOeTdnsdEBBEBi2DVZ11RT0TwzsEJDwb7rhSC"
    "CJgDRHoVOu+hIhsGyBhCEIHPpTAQPOyXl5zzFedulLe+JWXNI13nMRJaSwPB+0YvHj/1e/ll"
    "iuIotlFvZIlAKwth1QYRgQ+M6zMzuG/04nsDwZb47YQ65xpL3WeYQ92QgpkRWwuBgkA9sBJH"
    "kT1zSxlHLPFXA8GHjly6fObxB44z82+u624T8cN79u59bfq76W3FUhGGzMdE+NKYuJkU6EpE"
    "9IuC8k3t4w8++iIH8OPKwQsvvnS4XNmyrVAoQFW+NsD7sqJc+++xjeAdt4/jjokJ1LbWcPC5"
    "g5ifn7/nwvkLs2NjY2PMrCGEHCLkgmgIDv8XG8Cru7bdzvDGm29BRWaH0vSEqi4ACMaYGRij"
    "RUsAYgBt9Pvz/hkAMGELDgj/w4cAAAAASUVORK5CYII=")
getconnect_no_22Data = connect_no_22.GetData
getconnect_no_22Image = connect_no_22.GetImage
getconnect_no_22Bitmap = connect_no_22.GetBitmap

#----------------------------------------------------------------------
delete_22 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABYAAAAWCAYAAADEtGw7AAAABHNCSVQICAgIfAhkiAAAAAlw"
    "SFlzAAAN1wAADdcBQiibeAAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA"
    "AAP6SURBVDiNtZXLa9xVFMc/93d/j/nNTF5Nah+EWkWLLsQquhAEwQoSbYIRWhAFNxUXbtzo"
    "qn9AC8UHFV3oRheVWleKdSfuC61gjbYJxTRpWjMzyWRmfvm97rnXRaYxVhca8cDhXs6B7/me"
    "c885Vznn+D/EB5g6Go1Xq0Mfra+vPQ+o7QAp5UkUVT/Ist5bX32Rlz5AHA+8/9ijhydeefmE"
    "qkQ1ALZmcmdWf+dL07Y+cWr62MLCTxeBz9TkkXAsCKLF9079GJ08+S7tlWU8z/uTau3dYdN/"
    "8T196BDVunD6w1fnz37a3O9p7R975OCE7XRyLl76YTtV6DMX7t53kOGhXaNTR6PnvDCM33j2"
    "mdfj8+fPI2K2Day1pt1u8MLU2/V6beS4LyLVlZUGL05PMzk5ia81mxV0buN++/wHtk6ni1jZ"
    "oaaORC95Wp/5L2y3iu+H1pjisHLO8dqb9ebExFOjURgh4jDiELGUuSUvhDwTilxYTw3rPUOa"
    "lqSpIAaMWKw4xEJpUuLqjSufnO494G/EUatlwWgca5Qn+IECPExkqRiNKS3OhSgqpFlClqYU"
    "paXIhSwTssxgRZOlitUuv0F/QJxTzbLkPk/5iJN+2RzOgbOOWnUvxlh2jT4M+Fz+5VtqQQVT"
    "NglDD61jBmqj9JIqrfbsEoAHIMbdKgpB63CzVs6BtQ6tq9Ti3YRBnetLFwiCOg89OI3CJwhr"
    "1Gt3MTy0h3p9DGsdxtjrm4yNsTfy3KC9COgCEPiDxNEIigrtzjxWNGM7DhD4Mbgc5flUwkGM"
    "sYiUaK3J87QQsUubwEUhN7KsEO3Hmhw8L8TzYsZ3P4nnVbg2/z1JskqzNcfNW1fBaQK/Sll0"
    "KcsCB2gdkmXrxgrLm8BWXKPXSfIwGKxWojGUClBU0V5Es3UFhcaIwRjBiGWgtpNKtAMriyRJ"
    "D3Boz6fXXRNr3R+PZy2NokCicIQsa2JMiadKkrTJcmuGwgjGFKAChgf3styaZ6huSdZXEVv2"
    "F5Gim3QQu5WxpbHaXnMAYkvECnm5ynLrMiMj99PrtsizBfaPP4FSIXFlJ6Y0LN2c668BBziS"
    "pOdb2dJuVmi0220P57BiEGMwYsm7S1hRlCZHeSFBWENKg6d8fl28QJYnOOfQOqQsM8pSQudo"
    "bQKLpZEkWSQ2wzqFsQYxgjGWxsocphBKY5md+w7fH2BhaQZTCtZutGYUxqRZgrMq+/pcPsxZ"
    "VnyAb74sKpNH/Obc7Oyee+49gBjpj7btB3CIbKi1sH/8ccRabu97Y3Jmfr5EkatrwD6llPJv"
    "D8TNxfKdM5+fOy4iQ9v5B63VV67OFB/3hy5XzjmUUgoYAOpA+q9RNyQGCqDjnCt+BzEGY1pX"
    "iXo0AAAAAElFTkSuQmCC")
getdelete_22Data = delete_22.GetData
getdelete_22Image = delete_22.GetImage
getdelete_22Bitmap = delete_22.GetBitmap

#----------------------------------------------------------------------
edit_22 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABYAAAAWCAYAAADEtGw7AAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH1gcFDBUEtI+i2QAAAJF0RVh0Q29tbWVudABU"
    "b29sYmFyLXNpemVkIGljb24KPT09PT09PT09PT09CgooYykgMjAwMyBKYWt1YiAnamltbWFj"
    "JyBTdGVpbmVyLCAKaHR0cDovL2ppbW1hYy5tdXNpY2hhbGwuY3oKCmNyZWF0ZWQgd2l0aCB0"
    "aGUgR0lNUCwKaHR0cDovL3d3dy5naW1wLm9yZxbzvxQAAALTSURBVDjLnZVLTBNBGMd/u1uC"
    "oBxaDzR7MBxIiCf0olcOoiacfMRED+CVgyYk3ognQ0JAQvCiMSoEDoTyiB7QkEh8UHpCRCwP"
    "U4QCCqXYh7SN3dDd8QBbFlkq8E8238xk85v/fDPzDVjk7UAcJeaUtwMhhBBHiXY82dpJLQ9v"
    "xeknh4oWSWbDAdDY1NA1+C0JXOBNoB6o3RM943d3xZ5Pd4BaXvrv0djkFPmf7wNQ121I2Rka"
    "mxrEtSs3GB8fx+VyEY1GcTqdrKysoKoqsViM4uJigsEgqqqytraGqqqEw2EmJiZwLzVT0+Zl"
    "caSX931t1HUbksO07na7qaioAMAwDBRFoby8HEmSEGIrjWVlZciyjGEYAAghcC81c/vRKMsf"
    "upicWdcBJZsKgMLCQjRNA0BRFNsNNscVRSEUCvH1+cUdaCBCdLpfMVORBcvyzj4Gg8GcJ2h9"
    "fZ3Zzipq2rwE33Uy5g+RDLzK5ncX2KqSkpJ9oaurqzvQt518mfu1B7oveD/HWaetW9DpxRjx"
    "mQG0sw+gu57/gu0cZ522elkY6WFqIUrE34fz0gtC4Z97/j+QY9NpdcsI34famfkRJ+Lvp7J+"
    "kvn5+YODrY6FEIy0nKP64UcCQ+3MLMWJzw5QWT8JQCQSsU1bTsdCCDweD5vyeaZ8PhZXfhOf"
    "HeB0zWvC4TBCCHRdPzjYdKzrOuqPFobXSunp66NUHuPU9V5SqRTJZJKioiLS6fS+YNnOsRAC"
    "TdOo6zZovTnH6OZVTpZd5ozLBYDL5ULTtOwt3OYYVvAxO8dCCIQQ2SXf2l6BefskSSKTyeB2"
    "u5kPJtjm/IGtMuoACuyWIkkSkiTZXmlTeXl55Ofnm90CQAN0QHKYRSMWi+Hz+TisLJNbZxUO"
    "IJ3YSAw+ffa4iiMqsZEYBNJmGsx67ABOAEXAcctJkXOwzE3KACkgASS3+7ueEtnycQiw2Tb+"
    "GeMvnmKjxk6hepkAAAAASUVORK5CYII=")
getedit_22Data = edit_22.GetData
getedit_22Image = edit_22.GetImage
getedit_22Bitmap = edit_22.GetBitmap

#----------------------------------------------------------------------
filenew_22 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABYAAAAWCAYAAADEtGw7AAAABmJLR0QA/ADpAE8017ENAAAA"
    "CXBIWXMAAA3XAAAN1wFCKJt4AAAAB3RJTUUH1QISDiUwykMmCQAAAkFJREFUOMutlc1rE2EQ"
    "h5+Z3VSa4gdNmzUInjyIeBLEVvAf8NKDJ2/i1bMIYi+i4sc/4cGLeJDcRREENaUXC3qyudSQ"
    "GCgiMabZZMfDfmZT7Wp9IWR32Pd5Z36/mV1hn2vUWRGgBPiuV7c4LvHF/Yd3bwOrfwNVCagc"
    "GVBb7OGosTPUxxcvNK+5Xr3vZp5bvXH9ZmGomQ/+R4L+S3yrYJTZ/vrpiuG8GnVWnrr5Dc1m"
    "E8dxMDNEBJGwqOw1GCVpUdYXOKVZbOYS4sxzaOE1Fjy7LPZtXfPgGBBDzAzMMDMsMMwAxqj0"
    "ENnBZAF0HlDgADAuA4f3BCNAHFNBFUQcAjlIwCIy2gT/DQQdhoMGYj82gO3fglU1/BdBRNPD"
    "RFFxCDjKgGWGdgKGa7j+czY/byEET4CWuxtYVVONEZCsxgIqCDOYHMOnwphTzM6VaGx858zJ"
    "1gfg51TGa+uNSbMy2Sc/4iocTOcw5zgyc5pev4Tr1fuuV7cp8LmzS9RqtZympHKoRPdRdaJh"
    "VZNjwa5StNvtcJNpKENSPkkVkadED0wt909dYWJJdvleTg4QQSkATjYBGpkVagqi0X0cj5IN"
    "47lxzwfevX87lZFIKEUMzWossQl7gZeXzlOtVtMe1shENDJOEBTVbJdoMY273e5EuzHxnpDk"
    "gGxlhTROT9GMeRGQeMRJ9C8MTrLR1LiIF1uZTqNJpo8LZpy4Ho82k8aFVVAsY8/z+B8rAQdB"
    "cOfBo3u39gP7stW6OvXNy6vwj+zkY/oLI/uTo02YtuAAAAAASUVORK5CYII=")
getfilenew_22Data = filenew_22.GetData
getfilenew_22Image = filenew_22.GetImage
getfilenew_22Bitmap = filenew_22.GetBitmap

#----------------------------------------------------------------------
fileopen_22 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABYAAAAWCAYAAADEtGw7AAAABHNCSVQICAgIfAhkiAAAAAlw"
    "SFlzAAAN1wAADdcBQiibeAAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA"
    "AAMUSURBVDiNnZVPaBxVHMc/b2Z2NlnbImgONiBFiVAEDx6ktYh/0D2IRxFkTHPyVs8evYp4"
    "6kXrQUTMqWfBKIhCam2D/7AXzaGWbEOarUk33Z2defN7v5+H3W5306hJv/CY+THM533f9/3m"
    "jcuyjP9SFcrCORebmXPOAXDnJq2lf/Tz8vk0Tdu730sAvPfx7Ozs4b3A6xut+meffo5zbmIA"
    "LC5+cXzpm6UV4Clg5x7w3Nzc7865xwHbDTYz1tbWKMtyVIcQUFVOn16g0+k8uvLTyoWy759J"
    "07Q/ARaR4/Pz84QQMDNUFQBV5YMP3yeKIi5dvjQx4ckTJwA4c+Ydd+6Tj59cvrB8FuPt3WAT"
    "EddqtRARVBVVxcxwzpGmKc1XmpjZyDVAu91GRHj25Cl38ccf3lDZBQ4hmKo6ERkt884ASJKE"
    "pa+/IoQwcvziCy/hvR8UDlQ1gmgyY5HKRCpCCPjqLlhEwMXgYprNVyfcjl+TpI5ZpOu1l6e+"
    "O3bNZ6ur6rIso9FoyMLCQnzxSovzvwhRdHdmMyNyY/Wu/R3yh6tzwTnXvnzuzaOjjEMIbN5W"
    "nnv6GK+demL0AsCwu/bU+KPcS/zeR9/OZNlbNspYRMhLY2a6zman4PpW/19Qe2uqFvPw4RpR"
    "HHVhsivoVfDYA3UwSMbi2I/UoPSByEWdEbiqBpuXV44jjTpmkMT7B/cKYTqN8V5wEdsj8CCK"
    "QO7hUKMGQLIPblAjLwMSlOm0RtH3ADfHHRNCoKgAHF70HoAaw69yUHtR1CY7pNMrMbUb445V"
    "ROh7wwejWwR6peBF9wTsGUcZs3krR1TXJxxXIvhgbHcrWlt9gv4/bFw7tYitTlFZ0M0RGNC8"
    "DNRrMbf6ghwQClBWxna39Dj39ziYbqE88tARHmwkHJo6WKsBRM7R65VialsAyeLiYtJsNu3P"
    "jZKbnYLvf756YChAMKXby1PpbV8jHjiu53n+5a+r7derRj253SvuA+vMzKTc2Vi+cv7dq78N"
    "T4EacBSYYSya+5Ay+D39lWVZkQACXAduMHmmHFQ2hFcA/wDxAPK+pndhwAAAAABJRU5ErkJg"
    "gg==")
getfileopen_22Data = fileopen_22.GetData
getfileopen_22Image = fileopen_22.GetImage
getfileopen_22Bitmap = fileopen_22.GetBitmap

#----------------------------------------------------------------------
filesave_22 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABYAAAAWCAYAAADEtGw7AAAABHNCSVQICAgIfAhkiAAAABl0"
    "RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAKlSURBVDiNpZXBa1RXFMZ/Z+a9"
    "IKNGGtMuLERScGPblei6oauCkL+g4MbWlS7jRqFQcFEKUtwExFXsuuBKqWg33QTMphsXQhsM"
    "loFAJpqRe/Pu+bq4783MM1am9cDw7rvvvd9895z7nWvnvv35mrt/Bxg5xMF4c+5f3zFwzK4U"
    "7n7t6oUlK4suZ+//AO6GBBKSQA6S4Z7v3UHKHAk19xK/fnWd16Hizr31WwVgHTN++2ObT27f"
    "fIuQ6ePJqct8vngMoFsAltxJyTnx/a33AleDzAEoAFLKS577+tJ7gflpneSTYHe8ngCIMbK1"
    "tTUVa3FxcTSWOz6p2F3Ix4WemZlpfTBtSE6VMqcDUCUh+Ts/mgrsaqXC3L2lOKXE5ubmVLDJ"
    "lbmcVLWK5y3F3W73/6XCRUoJqFORkuP+NjP9V7CTak5dPEfuXPzx92wqyK5C2WD1FVQ/b+YZ"
    "uVCCjhlVlUZgq+pUyCH8vcHwz0dTKTy08AXF/Kc1W8js4D6WC5cY/vWY5eVlZmdnKcuSoigo"
    "y3I0LoqCGCP9fp+1tTV6c6dplulSex+nKjeT5p/n5+cpioLV1dWRupWVFUIIDIdDYoyY5Wbo"
    "KeVxzkUrFaSUcI1N0uv1KMuytezBYECMkRgjIQRijE0xkAsBHVduD02OG6g0Bjfbpond3d0W"
    "tAFnxR0k4UCVJhRXlQNjk+zt7U0oehfYsiCre7Ix7m4GL5/3B0dPHO/xvP9qBAkhHABPQkfP"
    "5Uj14aOxQQrBlxvPXjz87ORHRz/+8AhPgZ2dHUIILC0tsb+/TwiBwWDQAqe6aHOzM5h1AeGC"
    "uJ8AZJI4+83dMwYPBMcWtn/pjk6/N0Jqu9MwNj84D9atT0zLULhhB1426wAlcAg4DByZuAIM"
    "gb2J32sgSmpV+x+v6euDGbT4ywAAAABJRU5ErkJggg==")
getfilesave_22Data = filesave_22.GetData
getfilesave_22Image = filesave_22.GetImage
getfilesave_22Bitmap = filesave_22.GetBitmap

#----------------------------------------------------------------------
help_22 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABYAAAAWCAYAAADEtGw7AAAABHNCSVQICAgIfAhkiAAAABl0"
    "RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAThSURBVDiNjZRrbFRFGIafmTPn"
    "tm2Bgm2XO7tsLZctd+QqAQkksiAmGhISQ1QiKCgmRqReEn8YZUlI0IjIH/gBURMTIyFsAMFy"
    "EaQQJZSWUuhlWwqUNkUotN2223OOP3bboIA4yZv5M/PMl3m/9xOe5/GkFYhEDSAM3ANq4rGi"
    "J14SjwMHItEZwDpgNjAS6ARkWpeBE8DWeKzo5v8Cp6vbDKwNh/wZcyaOJBzyU5jvB6C8uomy"
    "6kZOX6hLllc3JYC34rGi7/8THIhExwIx21S5m15bkLF4Vj7F52oor22iorYZKSSFIT/hUB7z"
    "pwY49PtVoruPtSW6kieAFfFYUcdD4EAkagKV44J5I7/58EVxrryBrXt/ozvpoJSGpkmklAgh"
    "EAIybYN3V85mfDCHd6L7u8qqG/fGY0VvPAq8zbb0NQe3v+7buuckJ87XMX38cF5aOJ4JIT85"
    "2Rkkexwab7dx6EwV+09W4rgeC6YGWLVkEs+v39We6Eoui8eKjvWB00YVf7ZusU/XNT7fdRzT"
    "0Nm46llWLCp8pLk//nqJPbFSHNflvZUzabnbzsdfH2z2PEbHY0VtMn3u7UkFg33PPRNi23en"
    "MU0d09TxgMMl1Xyys5i1Ww7ww5FLfeCF0wLYtoltGew+cIHFM/OZPGZoBhAh3ToAs+dODnCk"
    "pIoex8PQFaahs/dQGTt//pOr1+/QlnA4XXa9D6w0ic82sC0DxxOcq7jJvGmjfcBMABmIRC1g"
    "xIT8wVTEm9F1DUNXGIZCVxqmoWOZBj7bYPXSSX3gi7Ut2JaJZRlYpkFd410KQ34hpZjXW/FE"
    "IFGY76eyrgWlNHRd9ckwUt+ydvlkJj+dB8C1pnvESuqwLQPbNDBNnfqm+4wdlYPneWMBFNAG"
    "SCEEUpMoTUNpEj39gKErXpgbYtqYVEDqm+6z9+hVdENHSImUAgToSqVaEdHZW/FlQFXUNhMO"
    "5iGlRNNSUpqGUhoTQ7l9X1BcehNd17EtA8vUMQwdXSlGD8vm6rUWhBQXAFQ8VuQGItHKippb"
    "E8cFcym5dAMpU2HQpEDTJDv2XcRnG1iWkYLaBj2OiwAcxyWpJMEh/amobnQdxz35YFecOFVa"
    "78yfGsAyVCo5kE6Z4JVFY1gTCfPqogKysyx8tomuNKQmEVJgG4rCYA7FZ6s6gZIHwVtKSusT"
    "Z8sbWL18CgAe4OHheR652T78A33kDrDBc0l0dtPT4+C6Lp7rsXRWkFMX6r3zlTcqgMN94PTo"
    "W//pt790zAwPY0rBYFzXxXU8XNdNvZJeXd09JBJddHYl6U72UDCsPwF/Fh99FetwHHdF76z+"
    "x3QLLo0emVE4ct6295cZ56/c4qfjlQhNwzJ7jVIopSGFQGmCxVOHE/D3Y/3mfR1/XGrYWHtg"
    "045e1r/HZqYQYntWhvnyFxuWZEwfN5TzV25xrfk+N1ra0XWNUf4BjMjLojAwiDNlDd6mLw90"
    "tHd0f/Ag9CEwKcMy/bPejNjZI3bMmRL0zZ8WMsOj80T+iEEAVDf8RXnNLffomSvJs6U1tber"
    "jm1orT52GWj1PK/tkWAhRDYwEBikZ+QM6ReYu9DIzAmbWU8VoDJyBI7rdLY2J1obq7pbGy+3"
    "1hw/Dd5t4A5wG7jpeV7icRUrwAZ8QFZa/YDMtNkJUmm9n97b0+r0HoD9DcIi5yD3PoxAAAAA"
    "AElFTkSuQmCC")
gethelp_22Data = help_22.GetData
gethelp_22Image = help_22.GetImage
gethelp_22Bitmap = help_22.GetBitmap

#----------------------------------------------------------------------
pause_22 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABYAAAAWCAYAAADEtGw7AAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAA3XAAAN1wFCKJt4AAAAB3RJTUUH1QwIFSEO/6m7rQAAAhxJREFUOMvtVcuKE0EU"
    "PbeqK92p9CudNzGELBwQ3PobMgy+t4JuRPwkQcIwGxn8Dj9CJQiDiPhIUnGGui6SrlSbxJ27"
    "qVV133PPPZx7qwq4Xv97kbfvAsgP4L4DuAAwBNA4gPkG4Ev5EZQbIURyfHL3XEp5y0dLKX+f"
    "v3132xhzIYTQJ/eO3xNR4mPquv71zevpHWbeJdZasxBieDo9g5TSJb189UKlaUrGGGitOQiC"
    "5HR6VpH67PnTptaa5/M5dogbjYYt959mH0AEdDuDTdE6+xhmxuzzRwDAoHejzK8QC4+YDzWi"
    "rjX/G0OI49j6f5ziJElcgIgqafGGME1Tu7/vQBzHvJc4yzImIhBh7TFvU8uiaZqy11Qwb0F+"
    "rGJFlmVcKpEygJDSKY+ThAEgz3OneLFc4Nf8B2jD7McqxEVRuMDV5SWMWQAb4rJos9l0qgIp"
    "UVOhI/JjfxPzdqYJQaCcmizNrF+cCKipGpRSzop2u72fuNvtctkTpWpQgSoFoyjWanq9nrNL"
    "qRqCoOaKdzqd/Vb0+30LgAlrtetDsk5qtVq8wXhWKATlQSLCYDDYPxXD4dAF8qxZGaV2u20B"
    "YDQa2a2nRQXj51eIJ5OJFULMHj15kPkApZS9eXR0BQDj8ZittT8fPr5fuSvyvLkcj8d27+3G"
    "zI3VahUZYyqTH4YhR1FkiGjOzA1jTLRarSqYKIo4DMMlES2uH4yd9Qdj25ohyRAhBwAAAABJ"
    "RU5ErkJggg==")
getpause_22Data = pause_22.GetData
getpause_22Image = pause_22.GetImage
getpause_22Bitmap = pause_22.GetBitmap

#----------------------------------------------------------------------
preferences_22 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABYAAAAWCAYAAADEtGw7AAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsRAAALEQF/ZF+RAAAAB3RJTUUH1QkaCxgledlRSQAABAxJREFUOMullX9MlHUc"
    "x1/PcQIp4KGWcoSIzWlWwgmjDe4WhbgWCs5labKmFstq/eFYCxnu25PEUf/QBuTI1ppjLcwt"
    "c9omsWkt2JQfZzupQyV2uziQHpEuQLg7nqc/5Lkd50Ftfbdnez7Pvs9r7+/n834/j0TEEkII"
    "4P258j2gV5bldv7vEkJoo7dHtJmZac3l+k0TQmgVFRXFgPQvr0qAQS8MUTaYmz49gaaqpJrN"
    "7Nu3l4SEhPOAthA8p7wl5YMT59Sc8pZTkWBJCJEFIMvyMGC2133EzPQ9MjIyIlVFQrMA77HD"
    "OzEvZ01OeUu7Dpaqq6tlwCGEOK7DrVYrkvTAgdQogh1dn+2np6eHg/nLCi3p8YUARmBJTEzM"
    "sTcPl2OIiX0XqN6yZQubNm1E01QkScI/M3lFCJEly/K1KGoZGBjA4/Hw4feTAObQ0Zqbm52l"
    "JTufXLr0IQJ+P5qmoWlaCJBkSqa21g5gnmuVDnV0Nr1E3tun9a2W7pNl10JgIURKfHz8r89v"
    "LzQ9/sRTSJIUmpVv/O59+HITtfY6APMF74bVgONq8yvB3De+MgJF3SfL2qMOQwiRlZ6e/rnb"
    "7c7Wn+Xm5ga2bStc8vdf42iaxrLEJFpbW2nqjOXnhhexvnNmnspwrrSIn1MAG9BaVXWUsTsK"
    "12/+wcdn3Xx7vJiCI2cXhAKa9B8CkwU41lqKOXHhBt9U5VP1RTclmwO4XP2WsIHq/Yvuy3DT"
    "K0Mer16vSk3jcv0uDtS1scsSz8slRdTU1OgDHQVmFzV8OHTP9o1kbl6PoozxScsVVqWmUbEj"
    "BbPJyPqMdaQ+moYsywCWSCsaFoO+WmpFnVBINJkotCShDHlw9f6EzWYjPi6WO3/e5v43C4ee"
    "3KhgHfr67kwO7X6Gtos/8GNPPxiMzAaDIa/KsszKh1cjSdKCcEMk9OhrVvYX53H6u3a6+gbJ"
    "s9lwuW4R8E8D4PP5FL/fny3LMitWPQIQgsfFxYXgBj1FypDHK7/1LHu2Z3PqzEUGPV6Kiktw"
    "uW7hdd+ko1/FGBzdUF9ff9dut98YGRmx6spn/H4OHjxAZWUlgCMEVoY8jiNlT1NakEnrucsM"
    "erzYniucBw2M9lqmFHcSsAJY6XQ6A06ns1iWZcypaTQ2NuLz+UKdMOp36evSmFU1RocGH4BO"
    "/N5WoLguBeaEJAOGzs7OIDA8MTGxt6Gh4euxsTFUVb0aCATsoeSte8Gu7cg3Y8m28FiKiV/6"
    "bnG1q4uOfpUp96X80b42JWImaphVZ4EZYBKYBoLArBFgxZqUrec7vL16g+5NTdDRrxJnmCxQ"
    "k1PHASXM9zpQ/6Ooc/CgDp0X6a2HvrSMjQz36nVCYuza660VI+ExDYNKUWKszl0aoP0DjPbe"
    "8WKg6ioAAAAASUVORK5CYII=")
getpreferences_22Data = preferences_22.GetData
getpreferences_22Image = preferences_22.GetImage
getpreferences_22Bitmap = preferences_22.GetBitmap

#----------------------------------------------------------------------
print_22 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABYAAAAWCAYAAADEtGw7AAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH1QsVEgcbRLaZtQAAAvJJREFUOMu1lc9rFEkU"
    "xz/V7iQz6yBRNNntxawxTg456CHiD4RdFGHFk7qKiHqPf0NIwKioB896USTmIKKZ4IKsiEl2"
    "iSQHbzn6Y2FNlB4PM8mY6e7prnoepqedJMPEH/jgUUVX1adeVX9fPfhOpup9zI6O3Af+/EzG"
    "g6NHjh3/rJnZ0REREdFaN3QRkezoiNRj/NBog9nZWXK5HADj409RSnHgwEGUUti2TVtbW+3J"
    "l2xgrRZ9a2srU1PPSKVSJJNJpqaeYds2lmU15KwKvnfvLr7v43le7MPDQyilGnIaXoVSilOn"
    "TqOUIpt9AMCJEyexLGs5OFg14v6Bvp540LJwHAfHcUgkEqxfvyGG1l5F7Zq64P6BvjPA89qI"
    "bdvGtm22b99BZ2cnlmXFXmPPo7VqBTgauDN4/iIAxWIRAGMMWmva239l8+Z2PM/DdV0WFxfj"
    "OV2ZDMCd/oG+01WmWg5dmM8zNjHB+NgYxuiGP/YX2yaTybBn7z7evXvLw78eApy9MHhpuBqt"
    "VM11XflScxxHHMeRmZkZ6R/okyWqmC/kmfjnX3bv3sXGjZuYnp6mu7sbEYnvU2sdn0KMoKxP"
    "yhgauk1Pz86VcnszO8fc3BzpdJrJyUk6OraQTq8FKgoQkVhiOgxjgIihXA7I5/OUy+FKsFIK"
    "EeHC4CBBWEZr8wkmIFHGipiIWIm6KdmE1oZUKkUY1gEXCgW6ujL81NZKYb6ABUikHhEhCAM+"
    "FIuUSi7WGoVSCqWsWO/NTYn6mReGIYKQTq+lOdmM53kgoE0lQqM1LS0bEBHEaIxUTiQiGGMQ"
    "Ufi+H8u4Cr7xdOxJ76E/DvP340df9bBv7djGq9cv8H3/UQwuB8GtpkSid2GhwO+/7V+RshVF"
    "hDWJJUs0HgQhpZLL6/9eksu9vwaIqsm860Dvt5SjIAhvXrl89RwQqDqlKgW0AJuAn4F1wI+R"
    "m2iOAYqAA/wP5IASoKOx+jUvyvc1QCJqk1G/CtbRU+lGrVleQT4CIpSukW+4hbcAAAAASUVO"
    "RK5CYII=")
getprint_22Data = print_22.GetData
getprint_22Image = print_22.GetImage
getprint_22Bitmap = print_22.GetBitmap

#----------------------------------------------------------------------
spreadsheet_22 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABYAAAAWCAYAAADEtGw7AAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAA3XAAAN1wFCKJt4AAAAB3RJTUUH1QYYDQgLwxltPwAAA4BJREFUOMullU9oHFUc"
    "xz+/t7PdyWZnEhPMv02rSTVaujmoKY01mBVPguChIP67BHrQiydRhKpgiMaABw+eRaFSaJFW"
    "KhbaQykpWosg4kZNUiKRzG67VNdkNsnMZud5mNntpk00pQ8e/N6PN5/f933fnxGAyamJ94F3"
    "uIumtR5/+62j725KTk5N6Lttk1MTupFpNA4WFhaIxWJoHc4RBJQAOowlzDVkQDTpdO9tK9gE"
    "FhFEBK3h6tX5CA5L+Tzpnh4AHMchne5BI+Qdh+xodktrtgSLaBzHQUTq8NpYROE4+ZtzldwJ"
    "WEin06RSKQDm5ubIZrOICLlcjkwmA0Aul0PJDsFKKXSg8TwvzKmwUNktg4BSCtd16/PZBqwa"
    "B1d+/KH+gWmaWJaNlbIREWzbxrYb4hY7skL9v+KDB4bp7u7GcRx8z2dVQpUiEqqM1NUUs73g"
    "260oFAoAJMwEKdtCgHw+j21bEPkfKgclipioO9s83/cpu254mkVwy7WYHXls3JqogU3TJGVZ"
    "KIRCASyrhZCjaLFb6hapnSj+/vJ3PHFoBADP81Hi1lW57grXLl2i8MnHLM3NEyyHqv9MJWke"
    "zJAcGqodea217t4Efnz4EB0dHRQKBUxzFynLCleQF3558w3cb85w30vPEh/ZT6CEjSDArwSI"
    "Mtk4/TXHDjx28cmvTr0oIktGVKVuQ7FYRETwPB8RFxFF+eQJjCvTPPDq82yslCgtLlEJAvyq"
    "JtbSRiUIqB4cIP7b0sjZp0Y/AsaM7Z5BM2FiRYqN8+dIv/IM7uJ8HVgJAn7v6ucv36ASbOBL"
    "ldQjXTx48tRh4LVtN2/d9xA3jPm7RNVfw6vehEr3LqyhBJ8Wn8aveAy0pQiqFfZ//mUCaNpS"
    "sUYzOJhBiUKJMNvWTuzeXlhdw7tRpFLVNA8k2bt3ha68Q3r3Q/yav05/8Q/cRMJjfT1uAPUH"
    "urOzc0tbeo8c4efPvqBv7DDt9z+MNgxaR9oJmhTvDQnHF1bYvTjDo6dP4Pf3n2NmRgvAB5Pj"
    "40qpo//167HOnqdpeppKdph4byvmqMbzA8o3Knx7JuC5yxdZ7+v76fXZ2ZeB643XRoAY0Ay0"
    "AhaQjHocMMf27RvNlEov3LO83BVfW41pDRvJZNXr7Ly2uGfPsQ8vXDgOOMA/t95Habg4KgIa"
    "UcFYNI5HxeORjRrwgHLUV4Hqv0lRjKtbp8qOAAAAAElFTkSuQmCC")
getspreadsheet_22Data = spreadsheet_22.GetData
getspreadsheet_22Image = spreadsheet_22.GetImage
getspreadsheet_22Bitmap = spreadsheet_22.GetBitmap

#----------------------------------------------------------------------
start_22 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABYAAAAWCAYAAADEtGw7AAAABHNCSVQICAgIfAhkiAAAABl0"
    "RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAANTSURBVDiNtdXfaxRXFAfw77mT"
    "2dnMLtsE6+oqbZPdTa2NGEvfKkIh1BBsC4ZaY9SC9aXqi/gLQQQFwdouGGtbahtiWrP98Q+U"
    "2ibxF6JJVm1BK+hTKZlNsptkdpPs7MyOc3yIu+zmF6nVAwfufZjP3HvO3DvEzHgeUVY8IaJl"
    "AGQAI8w88cxgAN6GxneaEkMjd4noTwAJZjafBYyKiopjfr8fwXD1r7G+W6eI6B8ASWa2/xcM"
    "Ar4916b80XXxfVmW17++auXZrt+7O4goCWCUF9oUZi4kgFc3t2zKMjNbOYvT42k+82Wr0bK1"
    "Ob7u7bU7AQQB+IqfmSvnhAeHNU6ldbZtmwe0f3n/oX2ZLS2b++rqatcDeAWA+tTw4LDGQ4k4"
    "T0yOs23bfOevO86Ojz/KNH2wMRoIBN4EsAyAaza4pMZut3tm/RiYzEzAyBp4bcUKOvdNW/nF"
    "rt82KW7lvZSuR3pv9P/s8/nGhBCjuq4/KrSquBe1tbWh1WtW3fsp+ouSHE2AnjSzpNuSDFX1"
    "wDJNtHe0G719NxNjydRhTdNuCiFGiSgdi8W4ZMWhUMjJjyVJAoFKYGaG/SiHMX0ELlnBrk92"
    "lzdtbHr5zBetbYterOzPTGb3E9EAgEFRDAeDQScP5WxrKnNTaZpZWJYJ27bhOA6yZgammUVg"
    "aQAbNrzrztnWWz6fujQYDDIw7TsOhULOcDIOABAQICEgiEBEAFF+2ZBlF8rdKrS4hiORI4ae"
    "Hrv20vLlR8PhlfcBTMyAq6urnRu91xkApLIySEJACAlCCBARiARkWYaZNfHV12eNW7djWuUL"
    "lQe2Nm+/KoRI1dfXF5pXAtfU1BRqLIggnsCSJEEukwEA3T3d1g8Xvjc8Hu/xfXsPdqqqmgqH"
    "wxamRQlcVVVVgB3HARFBliW4ZBcePHzgRCKfmZIkXdjWsv3ThoaGIQCZ6eCssKIohbEQAh7V"
    "Cz2VQmvraSMeH+h/Y03doT179ubr6GCemHkJ5V/iKkdntNPoudSTCCxZcqDtu/PdAMYB5OYD"
    "54EZl6/02Oc7OrJer+fk56ci7X6/PwXAWAg4J6wo7nvRH6N/N3+45URjY+MgFrDt2aLkSANY"
    "DEBgartpAP/pcp8PdmHqED/V76g4HgOyO8DvUiocTQAAAABJRU5ErkJggg==")
getstart_22Data = start_22.GetData
getstart_22Image = start_22.GetImage
getstart_22Bitmap = start_22.GetBitmap

#----------------------------------------------------------------------
stop_22 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABYAAAAWCAYAAADEtGw7AAAABHNCSVQICAgIfAhkiAAAABl0"
    "RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAGTSURBVDiN1ZXLitRAFIa/c6qS"
    "jm1f6A59YxqxwRdxJ4g7GQZfT8RXUPFlvDQis5RBmJnUcZFJ0knamBF7YW1SdVJ89dVfuYiZ"
    "cYqmJ6GeEuyPFUVE7guyRqbSzFhEVsD0vmDgysz2xaBlnCTJg+cvnr1Tdbu+RAu2//D+49PD"
    "Wgu82WxM1Z29ef2WKIp6gc8vXp5Np9PQCZ7P52U2X/efyEI+v516Xni0fQzAer2uZdoCL5fL"
    "cmURoe85pmlaM249bovF4q/emMOdwhHjyWRiPy+vEAHnPEhWn2BGRah6TaGj4O+X30CE65tr"
    "brNbzAJmdnel7IdQ7X42m3VHsdvtAoAgqCpOFace7zzeRXjviXxE5GPiaFAT6jRO0zSfIBBH"
    "MZlzUFhiB+Z5/yCK7sctSRIrjON4QJZlJSgU0GB344r1x8MrogBQzW2DSW5nAQtgmkM1VElu"
    "t9tu49FoVK48GU+at3/bhsNht/F4PDZ1+vni1fmTvlAV/bJarWrGra8b8BAYNIs92g3wowv8"
    "T9r/92v6BUU6qMwo4dgfAAAAAElFTkSuQmCC")
getstop_22Data = stop_22.GetData
getstop_22Image = stop_22.GetImage
getstop_22Bitmap = stop_22.GetBitmap

