#----------------------------------------------------------------------
# This file was generated by D:\Entwicklungsumgebung\cedrei Veranstaltungsverwaltung\src\BaseUI\wxApi\res\make.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

cancel_16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAC30lEQVQ4jaWRz2+TBRzGP9+3"
    "P9dua2nXdp0zS4GNlSnDTTcxkIHGUUOMhoOKB+PNPwBP/hM6Y+KFExCIUUY0HPRgRESSiT+G"
    "EPYLyUaadV23tuv2tn3bvu/XAz1490mew3N4njzJR1SV/yMxxIejFnFgJhz56NlKcXnT4ScB"
    "soAf6AS8wAt+45U7nq7R87s7X+YBbyCIgBto4YPR+mp+nsW/uJrJeL3QXG8PBAADOHfxsuq+"
    "OME3pydqcNfV0YEBLYCXPx+fnCdfguQhxk9NNSyg2bYFTEy/oRw5jjxzgJnXMr8BJ2zbRoD9"
    "1je//ONdXYIb17GDEVwvvcjC9Qtcu3df/MDrY5M6mnmHxoN7eGnBUJr72S2OfP3FiAC4w73V"
    "+VR/x8jSMoVmHXwBYj1RSm+9TT2XIzk3R6FSgapJzOthLRwmtbGNYgkA+5IpgAePI1Gtg94E"
    "/Rm0PJjWQjKpt0Bvg1ZBF0GBta5gFPx+BKCjf5BadoUYzM12dU6Ud/fYAFxtVC6gBxDDxYeO"
    "/XATRnyhBFajgqxNnuTXuZvsASuAZzD9faZWPb2QXcP+D+/nYgm+c3tuSy57YpinN5LdEYwN"
    "22YLKAEmcHK3fNoy9ygBNaABlIGKVWfa5TputnMR2ALcdceh2i5/EO9TK7/OisIhINa+nwOK"
    "lR0OmlXejyf0x828AFgoRtNuUQf3VDCoRiHHnsJhnjowNo7/2DGeB1JA0W7SWSwxFQ1pDQIt"
    "RzGajUb0k08/a3abJiVVBtrlP8Jhth49nF1fmL90NxLiKNAPFFoNQts7fHz2XbOpTh93zrzH"
    "rZ5u/Rv0EagFeiUe06zPvfxDKMCNcIBVj+vPK4lebYE+Bl3qDurvyV6dEcFwUFREtoEDw2mu"
    "DQ/zaqHwxIYhB0FFsGFsqphf/CqeIJXoo1wxccQQxMBQBBvBBpkd2s+56VPYyoCjirZxOQq2"
    "o+mzQwN8mz6IA6IiOCL8C2ZiPnhZ5r4bAAAAAElFTkSuQmCC")
getcancel_16Data = cancel_16.GetData
getcancel_16Image = cancel_16.GetImage
getcancel_16Bitmap = cancel_16.GetBitmap

#----------------------------------------------------------------------
checked_16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9sCBRMKFAdmxMAAAAC5"
    "SURBVDjLY2CgEDAyMDAwyAQ2/CdV45P1DYwMDAwMLDCBYxNjEaYyMjEwMUEwMzMzAxMTM5xm"
    "YmJi0Izrh6tlwnASAc1MTKhamIjVbLDBCCrHjN0AQpoZGBjgrsBqAEyz1S47rJphahgZGXEb"
    "wMwMcZ7pVgsMzTcirjMwMjLidgHMRhjApZmREacXIM6+EHAORQG6ZpxeQI6qKyGXcGrGEwaI"
    "eGZiYiZKM9ZYgBlEjGaUpIycPIcWAAAEtR+tFw3cjAAAAABJRU5ErkJggg==")
getchecked_16Data = checked_16.GetData
getchecked_16Image = checked_16.GetImage
getchecked_16Bitmap = checked_16.GetBitmap

#----------------------------------------------------------------------
connect_creating_16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAACBUlEQVQ4jZWSO2hTURjHf+fc"
    "tCGpTTFIm/YODmIa6iClFAexdunig4L1UfCFCE4dhIqD4CTS1aGDBB3UJYM6iA+q+FgUwVcr"
    "GOJobaAaoWiTe5vHPZ9DTNqbGsE/HM7h/M//953zcRARauP2w5m9j168nL00fXN47f6/PM0a"
    "tYXaLm6Lx7f3dPWco0HNPB+g4LrtWmuiHe3hRkAzzwdQShkREBFpBDTzdOPB/5WqAY8cOth3"
    "4MTppzsHd8Rev//kfHj1+CzGCyqF7F64Pt0MEKgtNkQ6Jt0fi7GZ+3fQWocT8a1JI4IYDxZg"
    "JDnpC2afPSCdyqwCPM/TjuMC1RsZcRFjSLy7TN94ApY/robffCWdyjBy45uqA0qlEo5TwBhZ"
    "hZjqbPca+PWlGv6s62HfE8rlMoVCAc8zgCAYhuavVasvRerV7U74bts8OdklPsBK3pN8vkCx"
    "VKRS8fAqJQDSqQxpYJNt0z9mQzRP/8Qg2bl2fw+6e+cv5HIbT2EJARSiNKnW/SgRlGgOZ+9B"
    "Zy9YPWTnMut7kLzydnHfnl0DSkfvKmU2BwItKAWiBMnnIAZYEV/Y9w8AxHiMjo61Lud/bik6"
    "7oBR3FIKhpdmmbpaJOsO+cLrAACVSgXXXeHo8WPdwZZgFqXUmdBz+sYT68K+JtZkWRbhcIjW"
    "lqBjBQJTf86c/1sY4Df2IRlBM8NGSgAAAABJRU5ErkJggg==")
getconnect_creating_16Data = connect_creating_16.GetData
getconnect_creating_16Image = connect_creating_16.GetImage
getconnect_creating_16Bitmap = connect_creating_16.GetBitmap

#----------------------------------------------------------------------
connect_established_16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAACXBIWXMAAAsTAAALEwEAmpwY"
    "AAAKT2lDQ1BQaG90b3Nob3AgSUNDIHByb2ZpbGUAAHjanVNnVFPpFj333vRCS4iAlEtvUhUI"
    "IFJCi4AUkSYqIQkQSoghodkVUcERRUUEG8igiAOOjoCMFVEsDIoK2AfkIaKOg6OIisr74Xuj"
    "a9a89+bN/rXXPues852zzwfACAyWSDNRNYAMqUIeEeCDx8TG4eQuQIEKJHAAEAizZCFz/SMB"
    "APh+PDwrIsAHvgABeNMLCADATZvAMByH/w/qQplcAYCEAcB0kThLCIAUAEB6jkKmAEBGAYCd"
    "mCZTAKAEAGDLY2LjAFAtAGAnf+bTAICd+Jl7AQBblCEVAaCRACATZYhEAGg7AKzPVopFAFgw"
    "ABRmS8Q5ANgtADBJV2ZIALC3AMDOEAuyAAgMADBRiIUpAAR7AGDIIyN4AISZABRG8lc88Suu"
    "EOcqAAB4mbI8uSQ5RYFbCC1xB1dXLh4ozkkXKxQ2YQJhmkAuwnmZGTKBNA/g88wAAKCRFRHg"
    "g/P9eM4Ors7ONo62Dl8t6r8G/yJiYuP+5c+rcEAAAOF0ftH+LC+zGoA7BoBt/qIl7gRoXgug"
    "dfeLZrIPQLUAoOnaV/Nw+H48PEWhkLnZ2eXk5NhKxEJbYcpXff5nwl/AV/1s+X48/Pf14L7i"
    "JIEyXYFHBPjgwsz0TKUcz5IJhGLc5o9H/LcL//wd0yLESWK5WCoU41EScY5EmozzMqUiiUKS"
    "KcUl0v9k4t8s+wM+3zUAsGo+AXuRLahdYwP2SycQWHTA4vcAAPK7b8HUKAgDgGiD4c93/+8/"
    "/UegJQCAZkmScQAAXkQkLlTKsz/HCAAARKCBKrBBG/TBGCzABhzBBdzBC/xgNoRCJMTCQhBC"
    "CmSAHHJgKayCQiiGzbAdKmAv1EAdNMBRaIaTcA4uwlW4Dj1wD/phCJ7BKLyBCQRByAgTYSHa"
    "iAFiilgjjggXmYX4IcFIBBKLJCDJiBRRIkuRNUgxUopUIFVIHfI9cgI5h1xGupE7yAAygvyG"
    "vEcxlIGyUT3UDLVDuag3GoRGogvQZHQxmo8WoJvQcrQaPYw2oefQq2gP2o8+Q8cwwOgYBzPE"
    "bDAuxsNCsTgsCZNjy7EirAyrxhqwVqwDu4n1Y8+xdwQSgUXACTYEd0IgYR5BSFhMWE7YSKgg"
    "HCQ0EdoJNwkDhFHCJyKTqEu0JroR+cQYYjIxh1hILCPWEo8TLxB7iEPENyQSiUMyJ7mQAkmx"
    "pFTSEtJG0m5SI+ksqZs0SBojk8naZGuyBzmULCAryIXkneTD5DPkG+Qh8lsKnWJAcaT4U+Io"
    "UspqShnlEOU05QZlmDJBVaOaUt2ooVQRNY9aQq2htlKvUYeoEzR1mjnNgxZJS6WtopXTGmgX"
    "aPdpr+h0uhHdlR5Ol9BX0svpR+iX6AP0dwwNhhWDx4hnKBmbGAcYZxl3GK+YTKYZ04sZx1Qw"
    "NzHrmOeZD5lvVVgqtip8FZHKCpVKlSaVGyovVKmqpqreqgtV81XLVI+pXlN9rkZVM1PjqQnU"
    "lqtVqp1Q61MbU2epO6iHqmeob1Q/pH5Z/YkGWcNMw09DpFGgsV/jvMYgC2MZs3gsIWsNq4Z1"
    "gTXEJrHN2Xx2KruY/R27iz2qqaE5QzNKM1ezUvOUZj8H45hx+Jx0TgnnKKeX836K3hTvKeIp"
    "G6Y0TLkxZVxrqpaXllirSKtRq0frvTau7aedpr1Fu1n7gQ5Bx0onXCdHZ4/OBZ3nU9lT3acK"
    "pxZNPTr1ri6qa6UbobtEd79up+6Ynr5egJ5Mb6feeb3n+hx9L/1U/W36p/VHDFgGswwkBtsM"
    "zhg8xTVxbzwdL8fb8VFDXcNAQ6VhlWGX4YSRudE8o9VGjUYPjGnGXOMk423GbcajJgYmISZL"
    "TepN7ppSTbmmKaY7TDtMx83MzaLN1pk1mz0x1zLnm+eb15vft2BaeFostqi2uGVJsuRaplnu"
    "trxuhVo5WaVYVVpds0atna0l1rutu6cRp7lOk06rntZnw7Dxtsm2qbcZsOXYBtuutm22fWFn"
    "Yhdnt8Wuw+6TvZN9un2N/T0HDYfZDqsdWh1+c7RyFDpWOt6azpzuP33F9JbpL2dYzxDP2DPj"
    "thPLKcRpnVOb00dnF2e5c4PziIuJS4LLLpc+Lpsbxt3IveRKdPVxXeF60vWdm7Obwu2o26/u"
    "Nu5p7ofcn8w0nymeWTNz0MPIQ+BR5dE/C5+VMGvfrH5PQ0+BZ7XnIy9jL5FXrdewt6V3qvdh"
    "7xc+9j5yn+M+4zw33jLeWV/MN8C3yLfLT8Nvnl+F30N/I/9k/3r/0QCngCUBZwOJgUGBWwL7"
    "+Hp8Ib+OPzrbZfay2e1BjKC5QRVBj4KtguXBrSFoyOyQrSH355jOkc5pDoVQfujW0Adh5mGL"
    "w34MJ4WHhVeGP45wiFga0TGXNXfR3ENz30T6RJZE3ptnMU85ry1KNSo+qi5qPNo3ujS6P8Yu"
    "ZlnM1VidWElsSxw5LiquNm5svt/87fOH4p3iC+N7F5gvyF1weaHOwvSFpxapLhIsOpZATIhO"
    "OJTwQRAqqBaMJfITdyWOCnnCHcJnIi/RNtGI2ENcKh5O8kgqTXqS7JG8NXkkxTOlLOW5hCep"
    "kLxMDUzdmzqeFpp2IG0yPTq9MYOSkZBxQqohTZO2Z+pn5mZ2y6xlhbL+xW6Lty8elQfJa7OQ"
    "rAVZLQq2QqboVFoo1yoHsmdlV2a/zYnKOZarnivN7cyzytuQN5zvn//tEsIS4ZK2pYZLVy0d"
    "WOa9rGo5sjxxedsK4xUFK4ZWBqw8uIq2Km3VT6vtV5eufr0mek1rgV7ByoLBtQFr6wtVCuWF"
    "fevc1+1dT1gvWd+1YfqGnRs+FYmKrhTbF5cVf9go3HjlG4dvyr+Z3JS0qavEuWTPZtJm6ebe"
    "LZ5bDpaql+aXDm4N2dq0Dd9WtO319kXbL5fNKNu7g7ZDuaO/PLi8ZafJzs07P1SkVPRU+lQ2"
    "7tLdtWHX+G7R7ht7vPY07NXbW7z3/T7JvttVAVVN1WbVZftJ+7P3P66Jqun4lvttXa1ObXHt"
    "xwPSA/0HIw6217nU1R3SPVRSj9Yr60cOxx++/p3vdy0NNg1VjZzG4iNwRHnk6fcJ3/ceDTra"
    "dox7rOEH0x92HWcdL2pCmvKaRptTmvtbYlu6T8w+0dbq3nr8R9sfD5w0PFl5SvNUyWna6YLT"
    "k2fyz4ydlZ19fi753GDborZ752PO32oPb++6EHTh0kX/i+c7vDvOXPK4dPKy2+UTV7hXmq86"
    "X23qdOo8/pPTT8e7nLuarrlca7nuer21e2b36RueN87d9L158Rb/1tWeOT3dvfN6b/fF9/Xf"
    "Ft1+cif9zsu72Xcn7q28T7xf9EDtQdlD3YfVP1v+3Njv3H9qwHeg89HcR/cGhYPP/pH1jw9D"
    "BY+Zj8uGDYbrnjg+OTniP3L96fynQ89kzyaeF/6i/suuFxYvfvjV69fO0ZjRoZfyl5O/bXyl"
    "/erA6xmv28bCxh6+yXgzMV70VvvtwXfcdx3vo98PT+R8IH8o/2j5sfVT0Kf7kxmTk/8EA5jz"
    "/GMzLdsAAAAEZ0FNQQAAsY58+1GTAAAAIGNIUk0AAHolAACAgwAA+f8AAIDpAAB1MAAA6mAA"
    "ADqYAAAXb5JfxUYAAAIASURBVHjahNLPaxNBFAfw75uZ3WQ3uyZptPSgLdSKSMFYEP+CgoGC"
    "BxEE6cF/w4PgxYsHwX9A0EvPPUhBpBerJ2+Kegg1qa1amhhLNuvs7PzwVEiL2X5P78Hjw3vM"
    "kHMOR3lyfxE7aQ0f+1Wcm4rmGeOP4zj+kCnzzAy7+mq8hwcvv2A8bLwhAESEPM+9/f2DZq9/"
    "cCsISq0/g8PpNJXg/Ng4AECMN9a6y8bhWhgEdxmyKwQEO93OdZnZF40geG3t4BWAzxOBvfzC"
    "Q1SmWuejsEHOACDoXNdqdb4c+rT8M6EmgNWJgKpebFWiqOHrDDJTEJyDiJw1BrV6nX6L4Gbh"
    "CUIwHQYlEMqIQotSUAIBSNOUgqAMzpk5BRBsbnbu5AwdFb1enwoBrbXZbrcxKVprWwhwxjab"
    "S0v3JgFb77Y2CwEHrHQ63+B5Ar7vw/dLyKSClH9RLpdARCun/ANrkySBcw5CcOt5HpOZglY5"
    "KnEEa60rBpzjKs8hpXTaaBARrLEAHLgvYB1YIeAfbm8kstZKXFg1KiMhBAgEAwetfiCUvzYK"
    "gRnefdQZJuvfB9XblTK7oXM1q63ddeR9apTzN/PV3fWTwLGVGGNfndFrudKrCwuX1sA5MqWe"
    "J6P0DsE9ZYzahRsYY0BEmJ45m43S9O2ZuLoYR/H7/mA4clb+92n/DQDMft8q4PNRpgAAAABJ"
    "RU5ErkJggg==")
getconnect_established_16Data = connect_established_16.GetData
getconnect_established_16Image = connect_established_16.GetImage
getconnect_established_16Bitmap = connect_established_16.GetBitmap

#----------------------------------------------------------------------
connect_no_16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAACXBIWXMAAAsTAAALEwEAmpwY"
    "AAAKT2lDQ1BQaG90b3Nob3AgSUNDIHByb2ZpbGUAAHjanVNnVFPpFj333vRCS4iAlEtvUhUI"
    "IFJCi4AUkSYqIQkQSoghodkVUcERRUUEG8igiAOOjoCMFVEsDIoK2AfkIaKOg6OIisr74Xuj"
    "a9a89+bN/rXXPues852zzwfACAyWSDNRNYAMqUIeEeCDx8TG4eQuQIEKJHAAEAizZCFz/SMB"
    "APh+PDwrIsAHvgABeNMLCADATZvAMByH/w/qQplcAYCEAcB0kThLCIAUAEB6jkKmAEBGAYCd"
    "mCZTAKAEAGDLY2LjAFAtAGAnf+bTAICd+Jl7AQBblCEVAaCRACATZYhEAGg7AKzPVopFAFgw"
    "ABRmS8Q5ANgtADBJV2ZIALC3AMDOEAuyAAgMADBRiIUpAAR7AGDIIyN4AISZABRG8lc88Suu"
    "EOcqAAB4mbI8uSQ5RYFbCC1xB1dXLh4ozkkXKxQ2YQJhmkAuwnmZGTKBNA/g88wAAKCRFRHg"
    "g/P9eM4Ors7ONo62Dl8t6r8G/yJiYuP+5c+rcEAAAOF0ftH+LC+zGoA7BoBt/qIl7gRoXgug"
    "dfeLZrIPQLUAoOnaV/Nw+H48PEWhkLnZ2eXk5NhKxEJbYcpXff5nwl/AV/1s+X48/Pf14L7i"
    "JIEyXYFHBPjgwsz0TKUcz5IJhGLc5o9H/LcL//wd0yLESWK5WCoU41EScY5EmozzMqUiiUKS"
    "KcUl0v9k4t8s+wM+3zUAsGo+AXuRLahdYwP2SycQWHTA4vcAAPK7b8HUKAgDgGiD4c93/+8/"
    "/UegJQCAZkmScQAAXkQkLlTKsz/HCAAARKCBKrBBG/TBGCzABhzBBdzBC/xgNoRCJMTCQhBC"
    "CmSAHHJgKayCQiiGzbAdKmAv1EAdNMBRaIaTcA4uwlW4Dj1wD/phCJ7BKLyBCQRByAgTYSHa"
    "iAFiilgjjggXmYX4IcFIBBKLJCDJiBRRIkuRNUgxUopUIFVIHfI9cgI5h1xGupE7yAAygvyG"
    "vEcxlIGyUT3UDLVDuag3GoRGogvQZHQxmo8WoJvQcrQaPYw2oefQq2gP2o8+Q8cwwOgYBzPE"
    "bDAuxsNCsTgsCZNjy7EirAyrxhqwVqwDu4n1Y8+xdwQSgUXACTYEd0IgYR5BSFhMWE7YSKgg"
    "HCQ0EdoJNwkDhFHCJyKTqEu0JroR+cQYYjIxh1hILCPWEo8TLxB7iEPENyQSiUMyJ7mQAkmx"
    "pFTSEtJG0m5SI+ksqZs0SBojk8naZGuyBzmULCAryIXkneTD5DPkG+Qh8lsKnWJAcaT4U+Io"
    "UspqShnlEOU05QZlmDJBVaOaUt2ooVQRNY9aQq2htlKvUYeoEzR1mjnNgxZJS6WtopXTGmgX"
    "aPdpr+h0uhHdlR5Ol9BX0svpR+iX6AP0dwwNhhWDx4hnKBmbGAcYZxl3GK+YTKYZ04sZx1Qw"
    "NzHrmOeZD5lvVVgqtip8FZHKCpVKlSaVGyovVKmqpqreqgtV81XLVI+pXlN9rkZVM1PjqQnU"
    "lqtVqp1Q61MbU2epO6iHqmeob1Q/pH5Z/YkGWcNMw09DpFGgsV/jvMYgC2MZs3gsIWsNq4Z1"
    "gTXEJrHN2Xx2KruY/R27iz2qqaE5QzNKM1ezUvOUZj8H45hx+Jx0TgnnKKeX836K3hTvKeIp"
    "G6Y0TLkxZVxrqpaXllirSKtRq0frvTau7aedpr1Fu1n7gQ5Bx0onXCdHZ4/OBZ3nU9lT3acK"
    "pxZNPTr1ri6qa6UbobtEd79up+6Ynr5egJ5Mb6feeb3n+hx9L/1U/W36p/VHDFgGswwkBtsM"
    "zhg8xTVxbzwdL8fb8VFDXcNAQ6VhlWGX4YSRudE8o9VGjUYPjGnGXOMk423GbcajJgYmISZL"
    "TepN7ppSTbmmKaY7TDtMx83MzaLN1pk1mz0x1zLnm+eb15vft2BaeFostqi2uGVJsuRaplnu"
    "trxuhVo5WaVYVVpds0atna0l1rutu6cRp7lOk06rntZnw7Dxtsm2qbcZsOXYBtuutm22fWFn"
    "Yhdnt8Wuw+6TvZN9un2N/T0HDYfZDqsdWh1+c7RyFDpWOt6azpzuP33F9JbpL2dYzxDP2DPj"
    "thPLKcRpnVOb00dnF2e5c4PziIuJS4LLLpc+Lpsbxt3IveRKdPVxXeF60vWdm7Obwu2o26/u"
    "Nu5p7ofcn8w0nymeWTNz0MPIQ+BR5dE/C5+VMGvfrH5PQ0+BZ7XnIy9jL5FXrdewt6V3qvdh"
    "7xc+9j5yn+M+4zw33jLeWV/MN8C3yLfLT8Nvnl+F30N/I/9k/3r/0QCngCUBZwOJgUGBWwL7"
    "+Hp8Ib+OPzrbZfay2e1BjKC5QRVBj4KtguXBrSFoyOyQrSH355jOkc5pDoVQfujW0Adh5mGL"
    "w34MJ4WHhVeGP45wiFga0TGXNXfR3ENz30T6RJZE3ptnMU85ry1KNSo+qi5qPNo3ujS6P8Yu"
    "ZlnM1VidWElsSxw5LiquNm5svt/87fOH4p3iC+N7F5gvyF1weaHOwvSFpxapLhIsOpZATIhO"
    "OJTwQRAqqBaMJfITdyWOCnnCHcJnIi/RNtGI2ENcKh5O8kgqTXqS7JG8NXkkxTOlLOW5hCep"
    "kLxMDUzdmzqeFpp2IG0yPTq9MYOSkZBxQqohTZO2Z+pn5mZ2y6xlhbL+xW6Lty8elQfJa7OQ"
    "rAVZLQq2QqboVFoo1yoHsmdlV2a/zYnKOZarnivN7cyzytuQN5zvn//tEsIS4ZK2pYZLVy0d"
    "WOa9rGo5sjxxedsK4xUFK4ZWBqw8uIq2Km3VT6vtV5eufr0mek1rgV7ByoLBtQFr6wtVCuWF"
    "fevc1+1dT1gvWd+1YfqGnRs+FYmKrhTbF5cVf9go3HjlG4dvyr+Z3JS0qavEuWTPZtJm6ebe"
    "LZ5bDpaql+aXDm4N2dq0Dd9WtO319kXbL5fNKNu7g7ZDuaO/PLi8ZafJzs07P1SkVPRU+lQ2"
    "7tLdtWHX+G7R7ht7vPY07NXbW7z3/T7JvttVAVVN1WbVZftJ+7P3P66Jqun4lvttXa1ObXHt"
    "xwPSA/0HIw6217nU1R3SPVRSj9Yr60cOxx++/p3vdy0NNg1VjZzG4iNwRHnk6fcJ3/ceDTra"
    "dox7rOEH0x92HWcdL2pCmvKaRptTmvtbYlu6T8w+0dbq3nr8R9sfD5w0PFl5SvNUyWna6YLT"
    "k2fyz4ydlZ19fi753GDborZ752PO32oPb++6EHTh0kX/i+c7vDvOXPK4dPKy2+UTV7hXmq86"
    "X23qdOo8/pPTT8e7nLuarrlca7nuer21e2b36RueN87d9L158Rb/1tWeOT3dvfN6b/fF9/Xf"
    "Ft1+cif9zsu72Xcn7q28T7xf9EDtQdlD3YfVP1v+3Njv3H9qwHeg89HcR/cGhYPP/pH1jw9D"
    "BY+Zj8uGDYbrnjg+OTniP3L96fynQ89kzyaeF/6i/suuFxYvfvjV69fO0ZjRoZfyl5O/bXyl"
    "/erA6xmv28bCxh6+yXgzMV70VvvtwXfcdx3vo98PT+R8IH8o/2j5sfVT0Kf7kxmTk/8EA5jz"
    "/GMzLdsAAAAEZ0FNQQAAsY58+1GTAAAAIGNIUk0AAHolAACAgwAA+f8AAIDpAAB1MAAA6mAA"
    "ADqYAAAXb5JfxUYAAAKASURBVHjadJO9axRBGId/Mzuzu5fLJn5E7yRKCosoItFLQLASQY2N"
    "lSltDIErtbKwFkEk9f0FNhZ2NulsBAtTmJDAYTCnyd3l4nlf+zGzu/Na3B0xnv5g4GU+HoZ5"
    "5mVEBAB4UXoLALAtc2fKs576YfSMc/6l7QdwpLh6yvNeNbrJqk75GgA8Ly4BADgGYeBg4PBc"
    "+Xi+sHB/TIqHnW4PO5V9hEG4VCjML3quXB7uG0YMC2n1SymYGSCTnx0fBICoPyeFSKVF+DNH"
    "ADcDIgIhJgDg3CIHBMYEGOODU5yEI8EYGwVsfnwPKSXmrhcUADQPa0Y39+CQBSReDACJ7ury"
    "+jpirYFHd48DartbV2zbmWqez88BwEFt/0an01lmjDG/nb0JAL8a1Wv13a1bWqkGgE0AYEML"
    "xWJxzXWcy/lcbtoYQ7bjkCUEN6mBSVOKY824ZaFaq1WVUtulUun2sRtkXHfa87x8Lne2L6U/"
    "jiQNEgTBuU632x15gzAMQ855VD9oZH0/oLGxDAkheJqkSJIEOtbIZrPwfT8KgyAcBSgFblms"
    "5/tot9vQWkFKCa01krQPISKEKkKk1aiFKDKuEMaOkxhKKcSDA2RMXxsR4rEMlCInisgdAUzT"
    "XoXUeLbZ4jNpEoOl6bEPQ2Rw2OphQu1XJqm3MwKYyVRettPMhXLVegKTLoASJqTsLxpCSoBh"
    "7c8zE99eT2b8yggAjH2wOEMaq0+tVnf20uzFB99/7K30er2WY9urRHwj62U3OGdlsH/0wtCc"
    "MVReXLxXPnnCy9fqByunp860pWW9USr+2pf5n14AEYgIjmOjXq9he3trd3zceyeEOIy17jAw"
    "qCTG3/k9ALI0RT57sk02AAAAAElFTkSuQmCC")
getconnect_no_16Data = connect_no_16.GetData
getconnect_no_16Image = connect_no_16.GetImage
getconnect_no_16Bitmap = connect_no_16.GetBitmap

#----------------------------------------------------------------------
delete_16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QAAAAAAAD5Q7t/AAAA"
    "CXBIWXMAAA3XAAAN1wFCKJt4AAAAB3RJTUUH1QQWDyovwTM/8wAAAhxJREFUOMulks9LlGEQ"
    "xz/P+9syNUWyXBQzAunQrYQI+wPqYiLh2im6dokILwndqpvdskMXCUPtFmFE5yQNMrNwxS3L"
    "FQQxZd3d932eeTqYW2EESwPDwDDz4TtfBv4zFEDv5bZuEWe8slW5OTaydNfrSbf3dnScGe3v"
    "G6hofXxi6A5MznjAaH/fAMPDj1hZ/oLjuLiu88/ade4sF7uv8WZ68oWzS5x9N0cQBARBSBju"
    "ZkQURURR1c8aEYYhuZVcWYkHsLDwlqH79yo6YWb65Y6JPen2B8DVrq5T5FYziLWIWIy2aG0x"
    "WohjIUkMOrGIgDYGYwzW2mEF0JNut9dvpFnfmN3xVyybGyWUqsZza1nfWGZrs8B2XlMsGQ7W"
    "HWXq9RRjI4vK+5s8a6GhPkVL8xUA8vkPzH16Tn7fFoWCRbRbni2b6KhfzSONF3DciEz2Idvb"
    "8ziOiwV8r4ooCmlsqN0LULi4TkAY1BGFLaSa0iS6yOLnSTLZVzQ1nkCsYIwhiMK9gMA/gO/X"
    "oJSDBXJr4ygUranzKFyaD3ci1hKXNO5vasseKOVgrcFay+raBPU1nQTeMar3H6Lj+CXez4+h"
    "dYJYQyJmL0CLwVqDiBDH38l+e0YSG5Ty+bjwlLhkEKMRMYjWfwBCgGxmPWltO+kba5FE0CJo"
    "LRQLq6SaTmOMYIwljg3Zpa8J4AOBB8RxSd96/GTkdgWP6BcLySCgfwCHx/uHvBXx4AAAAABJ"
    "RU5ErkJggg==")
getdelete_16Data = delete_16.GetData
getdelete_16Image = delete_16.GetImage
getdelete_16Bitmap = delete_16.GetBitmap

#----------------------------------------------------------------------
down_16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9oMCAg0Ga5nWogAAAAZ"
    "dEVYdENvbW1lbnQAQ3JlYXRlZCB3aXRoIEdJTVBXgQ4XAAAAKElEQVQ4y2NgGAUDDxhxiP8n"
    "Vg8jHoX/ibGQkYAL/5OgliSXjIJBBQAzhAQDZf0M9QAAAABJRU5ErkJggg==")
getdown_16Data = down_16.GetData
getdown_16Image = down_16.GetImage
getdown_16Bitmap = down_16.GetBitmap

#----------------------------------------------------------------------
edit_16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH1QkWEjcpO1ICSAAAActJREFUOMulk01oE0EU"
    "x38z3aNIFiIt4rHgKaBYKwEPghWEeOxF0LYnr6UXFTyKIMUg9SJ+gJoWijG9WxoRTVwQ7cFi"
    "040bTP3A1WzrEBVakc14MEOzbWorvsv/Dcz7z29m3oP/DGGS4l36gBng2FZ6eIi8qZMAl0cv"
    "nQFmDh532I62ElhNvQHw7fk5tqNXT0rdrDstjdPeVEBZFVjdk6esCvzoethWX0xLBseKHOkf"
    "Bhg3BMTjccSJpT+LfU1lTX3fJ39PMnTtGR+ejDO3EIRAh9V6H6UU9Xp9w0sHQYCbSa0Ve8t8"
    "LU11AD0RA9u2sW07Uuz7Pm4mxeBYkcXHGV6Vl1GlHEDPyGRj9q8E5uSBdIHFfIa5twpVyvFz"
    "/0XOn70wC4hNCbTWFNK9DFx5ijd9h8rn76j5B7zvGqazzTdGCLTWZLNZfslDzDsO7z7VWXo9"
    "Bb1pdq2sANo0oW5LEIYhuz+mefSlm/u5HN3yJTv7bpFMJnFdlzeVBYyLXE9QrVbxPI+RyQZH"
    "Oyus7kgQHhglkUhgWRaWZUW6eANBLBZDa02tVkNrjZQSrTVCCIQQrdsbEQOlFI7jbDp1xmR9"
    "GIOJm7evn/qHKZ4wyW9aneiYeQn8EgAAAABJRU5ErkJggg==")
getedit_16Data = edit_16.GetData
getedit_16Image = edit_16.GetImage
getedit_16Bitmap = edit_16.GetBitmap

#----------------------------------------------------------------------
fileexport_16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAACXBIWXMAAAsTAAALEwEAmpwY"
    "AAAKT2lDQ1BQaG90b3Nob3AgSUNDIHByb2ZpbGUAAHjanVNnVFPpFj333vRCS4iAlEtvUhUI"
    "IFJCi4AUkSYqIQkQSoghodkVUcERRUUEG8igiAOOjoCMFVEsDIoK2AfkIaKOg6OIisr74Xuj"
    "a9a89+bN/rXXPues852zzwfACAyWSDNRNYAMqUIeEeCDx8TG4eQuQIEKJHAAEAizZCFz/SMB"
    "APh+PDwrIsAHvgABeNMLCADATZvAMByH/w/qQplcAYCEAcB0kThLCIAUAEB6jkKmAEBGAYCd"
    "mCZTAKAEAGDLY2LjAFAtAGAnf+bTAICd+Jl7AQBblCEVAaCRACATZYhEAGg7AKzPVopFAFgw"
    "ABRmS8Q5ANgtADBJV2ZIALC3AMDOEAuyAAgMADBRiIUpAAR7AGDIIyN4AISZABRG8lc88Suu"
    "EOcqAAB4mbI8uSQ5RYFbCC1xB1dXLh4ozkkXKxQ2YQJhmkAuwnmZGTKBNA/g88wAAKCRFRHg"
    "g/P9eM4Ors7ONo62Dl8t6r8G/yJiYuP+5c+rcEAAAOF0ftH+LC+zGoA7BoBt/qIl7gRoXgug"
    "dfeLZrIPQLUAoOnaV/Nw+H48PEWhkLnZ2eXk5NhKxEJbYcpXff5nwl/AV/1s+X48/Pf14L7i"
    "JIEyXYFHBPjgwsz0TKUcz5IJhGLc5o9H/LcL//wd0yLESWK5WCoU41EScY5EmozzMqUiiUKS"
    "KcUl0v9k4t8s+wM+3zUAsGo+AXuRLahdYwP2SycQWHTA4vcAAPK7b8HUKAgDgGiD4c93/+8/"
    "/UegJQCAZkmScQAAXkQkLlTKsz/HCAAARKCBKrBBG/TBGCzABhzBBdzBC/xgNoRCJMTCQhBC"
    "CmSAHHJgKayCQiiGzbAdKmAv1EAdNMBRaIaTcA4uwlW4Dj1wD/phCJ7BKLyBCQRByAgTYSHa"
    "iAFiilgjjggXmYX4IcFIBBKLJCDJiBRRIkuRNUgxUopUIFVIHfI9cgI5h1xGupE7yAAygvyG"
    "vEcxlIGyUT3UDLVDuag3GoRGogvQZHQxmo8WoJvQcrQaPYw2oefQq2gP2o8+Q8cwwOgYBzPE"
    "bDAuxsNCsTgsCZNjy7EirAyrxhqwVqwDu4n1Y8+xdwQSgUXACTYEd0IgYR5BSFhMWE7YSKgg"
    "HCQ0EdoJNwkDhFHCJyKTqEu0JroR+cQYYjIxh1hILCPWEo8TLxB7iEPENyQSiUMyJ7mQAkmx"
    "pFTSEtJG0m5SI+ksqZs0SBojk8naZGuyBzmULCAryIXkneTD5DPkG+Qh8lsKnWJAcaT4U+Io"
    "UspqShnlEOU05QZlmDJBVaOaUt2ooVQRNY9aQq2htlKvUYeoEzR1mjnNgxZJS6WtopXTGmgX"
    "aPdpr+h0uhHdlR5Ol9BX0svpR+iX6AP0dwwNhhWDx4hnKBmbGAcYZxl3GK+YTKYZ04sZx1Qw"
    "NzHrmOeZD5lvVVgqtip8FZHKCpVKlSaVGyovVKmqpqreqgtV81XLVI+pXlN9rkZVM1PjqQnU"
    "lqtVqp1Q61MbU2epO6iHqmeob1Q/pH5Z/YkGWcNMw09DpFGgsV/jvMYgC2MZs3gsIWsNq4Z1"
    "gTXEJrHN2Xx2KruY/R27iz2qqaE5QzNKM1ezUvOUZj8H45hx+Jx0TgnnKKeX836K3hTvKeIp"
    "G6Y0TLkxZVxrqpaXllirSKtRq0frvTau7aedpr1Fu1n7gQ5Bx0onXCdHZ4/OBZ3nU9lT3acK"
    "pxZNPTr1ri6qa6UbobtEd79up+6Ynr5egJ5Mb6feeb3n+hx9L/1U/W36p/VHDFgGswwkBtsM"
    "zhg8xTVxbzwdL8fb8VFDXcNAQ6VhlWGX4YSRudE8o9VGjUYPjGnGXOMk423GbcajJgYmISZL"
    "TepN7ppSTbmmKaY7TDtMx83MzaLN1pk1mz0x1zLnm+eb15vft2BaeFostqi2uGVJsuRaplnu"
    "trxuhVo5WaVYVVpds0atna0l1rutu6cRp7lOk06rntZnw7Dxtsm2qbcZsOXYBtuutm22fWFn"
    "Yhdnt8Wuw+6TvZN9un2N/T0HDYfZDqsdWh1+c7RyFDpWOt6azpzuP33F9JbpL2dYzxDP2DPj"
    "thPLKcRpnVOb00dnF2e5c4PziIuJS4LLLpc+Lpsbxt3IveRKdPVxXeF60vWdm7Obwu2o26/u"
    "Nu5p7ofcn8w0nymeWTNz0MPIQ+BR5dE/C5+VMGvfrH5PQ0+BZ7XnIy9jL5FXrdewt6V3qvdh"
    "7xc+9j5yn+M+4zw33jLeWV/MN8C3yLfLT8Nvnl+F30N/I/9k/3r/0QCngCUBZwOJgUGBWwL7"
    "+Hp8Ib+OPzrbZfay2e1BjKC5QRVBj4KtguXBrSFoyOyQrSH355jOkc5pDoVQfujW0Adh5mGL"
    "w34MJ4WHhVeGP45wiFga0TGXNXfR3ENz30T6RJZE3ptnMU85ry1KNSo+qi5qPNo3ujS6P8Yu"
    "ZlnM1VidWElsSxw5LiquNm5svt/87fOH4p3iC+N7F5gvyF1weaHOwvSFpxapLhIsOpZATIhO"
    "OJTwQRAqqBaMJfITdyWOCnnCHcJnIi/RNtGI2ENcKh5O8kgqTXqS7JG8NXkkxTOlLOW5hCep"
    "kLxMDUzdmzqeFpp2IG0yPTq9MYOSkZBxQqohTZO2Z+pn5mZ2y6xlhbL+xW6Lty8elQfJa7OQ"
    "rAVZLQq2QqboVFoo1yoHsmdlV2a/zYnKOZarnivN7cyzytuQN5zvn//tEsIS4ZK2pYZLVy0d"
    "WOa9rGo5sjxxedsK4xUFK4ZWBqw8uIq2Km3VT6vtV5eufr0mek1rgV7ByoLBtQFr6wtVCuWF"
    "fevc1+1dT1gvWd+1YfqGnRs+FYmKrhTbF5cVf9go3HjlG4dvyr+Z3JS0qavEuWTPZtJm6ebe"
    "LZ5bDpaql+aXDm4N2dq0Dd9WtO319kXbL5fNKNu7g7ZDuaO/PLi8ZafJzs07P1SkVPRU+lQ2"
    "7tLdtWHX+G7R7ht7vPY07NXbW7z3/T7JvttVAVVN1WbVZftJ+7P3P66Jqun4lvttXa1ObXHt"
    "xwPSA/0HIw6217nU1R3SPVRSj9Yr60cOxx++/p3vdy0NNg1VjZzG4iNwRHnk6fcJ3/ceDTra"
    "dox7rOEH0x92HWcdL2pCmvKaRptTmvtbYlu6T8w+0dbq3nr8R9sfD5w0PFl5SvNUyWna6YLT"
    "k2fyz4ydlZ19fi753GDborZ752PO32oPb++6EHTh0kX/i+c7vDvOXPK4dPKy2+UTV7hXmq86"
    "X23qdOo8/pPTT8e7nLuarrlca7nuer21e2b36RueN87d9L158Rb/1tWeOT3dvfN6b/fF9/Xf"
    "Ft1+cif9zsu72Xcn7q28T7xf9EDtQdlD3YfVP1v+3Njv3H9qwHeg89HcR/cGhYPP/pH1jw9D"
    "BY+Zj8uGDYbrnjg+OTniP3L96fynQ89kzyaeF/6i/suuFxYvfvjV69fO0ZjRoZfyl5O/bXyl"
    "/erA6xmv28bCxh6+yXgzMV70VvvtwXfcdx3vo98PT+R8IH8o/2j5sfVT0Kf7kxmTk/8EA5jz"
    "/GMzLdsAAAAEZ0FNQQAAsY58+1GTAAAAIGNIUk0AAHolAACAgwAA+f8AAIDpAAB1MAAA6mAA"
    "ADqYAAAXb5JfxUYAAAMhSURBVHjafJLNTxxlAMZ/7+ywzHZ2t7B8yQKWVrCph0XXUD2oB9HE"
    "tHrQAxxKP1QiqT2Y4I14MCb+BRxMTSkx+AfYYOKpiq1NoVg0tkRt+abbFNguH8vs7My8874e"
    "sMQa45M8pyf55Xd4RDrd8nakIvrFu2dOeq+8/JIMAin4jwgh9OraWvTiyGhsZ6fcYxjiMoBZ"
    "9rxEQ1VtQ0tLM11dXfxfJq5fp+R6HGw7nNJKAWCCVsIwkDIEYHPbQYjHJbTWxOM2vpQopXBL"
    "JfXtN1/vArSGIJCESlMONU7ZexygASGIxiBQEIYSzyvvzabSmjCU+FLjlAJK7i5Aa41AYBgG"
    "jlNicXmFxYVlfM+nMmrqRwBDK0UoQ4QwEIaJwERpk51SyIPVPPn8Jj/+cBkhXbY2H7K+vooV"
    "FeaegdYarTV//D7DzZtTlF2XrWKR5cVlaqrieJ7LkfY2OrNZkgmbqclJ2trbPu17r+/uhYsX"
    "fhHxRFVvuunA6K62wvNcHMdlf2If5788T/0T9WwUCqw9yNN66EmeOnSQeCLJC52dn09PT39i"
    "aqVQWhGttIkI6Mg8Q2yfjZYS244xc3sGIaA2lSJuJxn/6RqNdQ0IwTpAxIxGM7GY/Y7n+Tyf"
    "zXDq5Am2t3c4d+5D4skkC/Nz/HlnlpGvRknEbToyGQqFh2SefS575vSpiCG0JvADfK+MYRgU"
    "CptcuXoNISKUHAer0iK3cp8bU78yPn6VikgE3/d5teu1+sbGprdMhTYDGRBKjeeVEQLu53KM"
    "jAxz/M3jVFoWx469QWO6gWw2SyRisLi8wODg4Nj83OxnZuD5ayWnqJ3ilpi7e4dQ+pw920cQ"
    "+LQ0N9FQX8fs/AI9Pd1YloUvAw4/fYTcvZVLxWLxZzMMg+8NLT/o73+/PZnYL/L5fFUoZeXG"
    "RqHDLbsdt3+7xYHWVoQAz/e4MTmhamrrjHgi0bR3x5pUiuHhYXK5HEqpiFIqNnZprL05nf7I"
    "sqzu3t4TV/zA1wMDH09EKypej9t2vxAiofXfh0xVVzM0NMTS0hKPjvXPNqbT3UdfPPpddap6"
    "4N/bXwMA6f2S5bKHROUAAAAASUVORK5CYII=")
getfileexport_16Data = fileexport_16.GetData
getfileexport_16Image = fileexport_16.GetImage
getfileexport_16Bitmap = fileexport_16.GetBitmap

#----------------------------------------------------------------------
fileimport_16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAACXBIWXMAAAsTAAALEwEAmpwY"
    "AAAKT2lDQ1BQaG90b3Nob3AgSUNDIHByb2ZpbGUAAHjanVNnVFPpFj333vRCS4iAlEtvUhUI"
    "IFJCi4AUkSYqIQkQSoghodkVUcERRUUEG8igiAOOjoCMFVEsDIoK2AfkIaKOg6OIisr74Xuj"
    "a9a89+bN/rXXPues852zzwfACAyWSDNRNYAMqUIeEeCDx8TG4eQuQIEKJHAAEAizZCFz/SMB"
    "APh+PDwrIsAHvgABeNMLCADATZvAMByH/w/qQplcAYCEAcB0kThLCIAUAEB6jkKmAEBGAYCd"
    "mCZTAKAEAGDLY2LjAFAtAGAnf+bTAICd+Jl7AQBblCEVAaCRACATZYhEAGg7AKzPVopFAFgw"
    "ABRmS8Q5ANgtADBJV2ZIALC3AMDOEAuyAAgMADBRiIUpAAR7AGDIIyN4AISZABRG8lc88Suu"
    "EOcqAAB4mbI8uSQ5RYFbCC1xB1dXLh4ozkkXKxQ2YQJhmkAuwnmZGTKBNA/g88wAAKCRFRHg"
    "g/P9eM4Ors7ONo62Dl8t6r8G/yJiYuP+5c+rcEAAAOF0ftH+LC+zGoA7BoBt/qIl7gRoXgug"
    "dfeLZrIPQLUAoOnaV/Nw+H48PEWhkLnZ2eXk5NhKxEJbYcpXff5nwl/AV/1s+X48/Pf14L7i"
    "JIEyXYFHBPjgwsz0TKUcz5IJhGLc5o9H/LcL//wd0yLESWK5WCoU41EScY5EmozzMqUiiUKS"
    "KcUl0v9k4t8s+wM+3zUAsGo+AXuRLahdYwP2SycQWHTA4vcAAPK7b8HUKAgDgGiD4c93/+8/"
    "/UegJQCAZkmScQAAXkQkLlTKsz/HCAAARKCBKrBBG/TBGCzABhzBBdzBC/xgNoRCJMTCQhBC"
    "CmSAHHJgKayCQiiGzbAdKmAv1EAdNMBRaIaTcA4uwlW4Dj1wD/phCJ7BKLyBCQRByAgTYSHa"
    "iAFiilgjjggXmYX4IcFIBBKLJCDJiBRRIkuRNUgxUopUIFVIHfI9cgI5h1xGupE7yAAygvyG"
    "vEcxlIGyUT3UDLVDuag3GoRGogvQZHQxmo8WoJvQcrQaPYw2oefQq2gP2o8+Q8cwwOgYBzPE"
    "bDAuxsNCsTgsCZNjy7EirAyrxhqwVqwDu4n1Y8+xdwQSgUXACTYEd0IgYR5BSFhMWE7YSKgg"
    "HCQ0EdoJNwkDhFHCJyKTqEu0JroR+cQYYjIxh1hILCPWEo8TLxB7iEPENyQSiUMyJ7mQAkmx"
    "pFTSEtJG0m5SI+ksqZs0SBojk8naZGuyBzmULCAryIXkneTD5DPkG+Qh8lsKnWJAcaT4U+Io"
    "UspqShnlEOU05QZlmDJBVaOaUt2ooVQRNY9aQq2htlKvUYeoEzR1mjnNgxZJS6WtopXTGmgX"
    "aPdpr+h0uhHdlR5Ol9BX0svpR+iX6AP0dwwNhhWDx4hnKBmbGAcYZxl3GK+YTKYZ04sZx1Qw"
    "NzHrmOeZD5lvVVgqtip8FZHKCpVKlSaVGyovVKmqpqreqgtV81XLVI+pXlN9rkZVM1PjqQnU"
    "lqtVqp1Q61MbU2epO6iHqmeob1Q/pH5Z/YkGWcNMw09DpFGgsV/jvMYgC2MZs3gsIWsNq4Z1"
    "gTXEJrHN2Xx2KruY/R27iz2qqaE5QzNKM1ezUvOUZj8H45hx+Jx0TgnnKKeX836K3hTvKeIp"
    "G6Y0TLkxZVxrqpaXllirSKtRq0frvTau7aedpr1Fu1n7gQ5Bx0onXCdHZ4/OBZ3nU9lT3acK"
    "pxZNPTr1ri6qa6UbobtEd79up+6Ynr5egJ5Mb6feeb3n+hx9L/1U/W36p/VHDFgGswwkBtsM"
    "zhg8xTVxbzwdL8fb8VFDXcNAQ6VhlWGX4YSRudE8o9VGjUYPjGnGXOMk423GbcajJgYmISZL"
    "TepN7ppSTbmmKaY7TDtMx83MzaLN1pk1mz0x1zLnm+eb15vft2BaeFostqi2uGVJsuRaplnu"
    "trxuhVo5WaVYVVpds0atna0l1rutu6cRp7lOk06rntZnw7Dxtsm2qbcZsOXYBtuutm22fWFn"
    "Yhdnt8Wuw+6TvZN9un2N/T0HDYfZDqsdWh1+c7RyFDpWOt6azpzuP33F9JbpL2dYzxDP2DPj"
    "thPLKcRpnVOb00dnF2e5c4PziIuJS4LLLpc+Lpsbxt3IveRKdPVxXeF60vWdm7Obwu2o26/u"
    "Nu5p7ofcn8w0nymeWTNz0MPIQ+BR5dE/C5+VMGvfrH5PQ0+BZ7XnIy9jL5FXrdewt6V3qvdh"
    "7xc+9j5yn+M+4zw33jLeWV/MN8C3yLfLT8Nvnl+F30N/I/9k/3r/0QCngCUBZwOJgUGBWwL7"
    "+Hp8Ib+OPzrbZfay2e1BjKC5QRVBj4KtguXBrSFoyOyQrSH355jOkc5pDoVQfujW0Adh5mGL"
    "w34MJ4WHhVeGP45wiFga0TGXNXfR3ENz30T6RJZE3ptnMU85ry1KNSo+qi5qPNo3ujS6P8Yu"
    "ZlnM1VidWElsSxw5LiquNm5svt/87fOH4p3iC+N7F5gvyF1weaHOwvSFpxapLhIsOpZATIhO"
    "OJTwQRAqqBaMJfITdyWOCnnCHcJnIi/RNtGI2ENcKh5O8kgqTXqS7JG8NXkkxTOlLOW5hCep"
    "kLxMDUzdmzqeFpp2IG0yPTq9MYOSkZBxQqohTZO2Z+pn5mZ2y6xlhbL+xW6Lty8elQfJa7OQ"
    "rAVZLQq2QqboVFoo1yoHsmdlV2a/zYnKOZarnivN7cyzytuQN5zvn//tEsIS4ZK2pYZLVy0d"
    "WOa9rGo5sjxxedsK4xUFK4ZWBqw8uIq2Km3VT6vtV5eufr0mek1rgV7ByoLBtQFr6wtVCuWF"
    "fevc1+1dT1gvWd+1YfqGnRs+FYmKrhTbF5cVf9go3HjlG4dvyr+Z3JS0qavEuWTPZtJm6ebe"
    "LZ5bDpaql+aXDm4N2dq0Dd9WtO319kXbL5fNKNu7g7ZDuaO/PLi8ZafJzs07P1SkVPRU+lQ2"
    "7tLdtWHX+G7R7ht7vPY07NXbW7z3/T7JvttVAVVN1WbVZftJ+7P3P66Jqun4lvttXa1ObXHt"
    "xwPSA/0HIw6217nU1R3SPVRSj9Yr60cOxx++/p3vdy0NNg1VjZzG4iNwRHnk6fcJ3/ceDTra"
    "dox7rOEH0x92HWcdL2pCmvKaRptTmvtbYlu6T8w+0dbq3nr8R9sfD5w0PFl5SvNUyWna6YLT"
    "k2fyz4ydlZ19fi753GDborZ752PO32oPb++6EHTh0kX/i+c7vDvOXPK4dPKy2+UTV7hXmq86"
    "X23qdOo8/pPTT8e7nLuarrlca7nuer21e2b36RueN87d9L158Rb/1tWeOT3dvfN6b/fF9/Xf"
    "Ft1+cif9zsu72Xcn7q28T7xf9EDtQdlD3YfVP1v+3Njv3H9qwHeg89HcR/cGhYPP/pH1jw9D"
    "BY+Zj8uGDYbrnjg+OTniP3L96fynQ89kzyaeF/6i/suuFxYvfvjV69fO0ZjRoZfyl5O/bXyl"
    "/erA6xmv28bCxh6+yXgzMV70VvvtwXfcdx3vo98PT+R8IH8o/2j5sfVT0Kf7kxmTk/8EA5jz"
    "/GMzLdsAAAAEZ0FNQQAAsY58+1GTAAAAIGNIUk0AAHolAACAgwAA+f8AAIDpAAB1MAAA6mAA"
    "ADqYAAAXb5JfxUYAAAL7SURBVHjabJJbaFxVFIa/fc6eOWdO5pbMOGoypmlNKyLWFonRFKxR"
    "1IJIKBaxtX0Qi74IvogW9E0flSKtFkHIkyKISEC0Vay2akIpBUOsCQnE3IZ0ajKTucU5t719"
    "aGaq4npbt3+t/19LjI2NAaC1ftB13awpZHg9XOWr1S+MgdyQcp0mU/KSMdI4ojq5BWUoAKSU"
    "Qko5IbeasSzrXDqdSgKQ9Hm2/wgr3gqeqTjoHCa73k2KG2khBEEQUK3W9rUBhBDs3/8IAG/8"
    "/ip5s5dlb4F5Z5pMOg0Fi5EDI7Ts4sULhGGI0Y6gUUpRb9SZXJvCicfpS20n05UhFnMoFAuE"
    "YYhSqkV5i4oh8ZQHCADCMKRRr5OwUxgmZBMZEs0ES801tBaY5j9mAkbJXceOxACN1ppQBWwu"
    "uzgRBycW51azm9t1D55yUSpsT24DHH3mGAeeehJD3EBWoSZeTWJHLJCaBEmSIkVIiNbqXwB2"
    "1Ea2HNd1MU2Tro4MWS8HUuCqJhWzjMtfWNLGMi1aqpnC5MyXZ7TMv3DbtpXRa4vHTxwvPXR5"
    "MClc2D2wm0azxoYqs5RYYJEF4pEOXh59kYgtqdk11BSMXx6PyM7ueAZY7H061/fAsYH2elev"
    "/0Yz2qDULDERv8C2x3fRt9nXzn/07Wm0HRhCa819b981FK1Zo3ffce+uTH+G9XgRGTPQUcWC"
    "nsNOWiRjaRKdCf5cXKMxFnKo/znMshwSLVFOfPDa+fOz3w+XNzfI7u1C9PooK6AiNuiwHUgK"
    "Kst1Yj+mef/5DzGrBuXSxr72UR/b+cT9n7z5GflcD9PnZpj+YY7p2VlWi0Xmi0ss/Vwgf+VO"
    "Pn3pc4b3DKM1+IF/8xOVVkZ3NM/Jo6cY3DPI5q8+1a9DGr8o9LjgnsJeTh48zfbcDiqVCkop"
    "hBBGm8LZs9/8oTUxIYTSKN767vWJuZn5h3UQmD09+Z/eO3RqwDSMrTdGCAGe59/U4L/26DtD"
    "xkxp8pVazfd3pHZ+PPnuVf//6v4eAA5DTU7CEKk1AAAAAElFTkSuQmCC")
getfileimport_16Data = fileimport_16.GetData
getfileimport_16Image = fileimport_16.GetImage
getfileimport_16Bitmap = fileimport_16.GetBitmap

#----------------------------------------------------------------------
filenew_16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/ADpAE8017ENAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH1QISDiYc07YZKQAAAWpJREFUOMutkE9LW1EQ"
    "xX9z741WJH0lgtDKWxbc1O5cZqkb8w2ycVm/Rd6y3XcjBMSC38BNN90qhVJKslJKSVqEEP9F"
    "Ypved8eFJsYYk1R6NjMMc+acM1Iul7drtVqREZid/cvcXJtn0W/yy5/f5aJvH+HPvmTDGaVS"
    "Scfh/HhTL0/faOe8oJcnK52LxuKutrLr2jIzrqvSbDYJIQAgIj31jNlj2n4h474iZgnrTCbY"
    "9mrHt1tTzld7BwbJ3WrkCGvqiHmFuAJgMSpG01+L4F66/qyD5OtebzoLTIE4EAuCABduNFkI"
    "Ok/Q59hQRdNpQNC0ot6besamFffQ57uHAq/x4SfgsVoBFO9f6OlZ69PM/PeDkRFEBOUpHV1D"
    "dYE0/QE8YWvn0GxsbL8FcKPItzWL1zwiQhRFNBpJT9QwIfp/0497EYY5eIh8x8GwpcHZsB0z"
    "qd2xEXK5HI+Bi+P4Q5IkxX8hxXH8nv+FK8w9mWB7rBTJAAAAAElFTkSuQmCC")
getfilenew_16Data = filenew_16.GetData
getfilenew_16Image = filenew_16.GetImage
getfilenew_16Bitmap = filenew_16.GetBitmap

#----------------------------------------------------------------------
fileopen_16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAACXBIWXMAAAsTAAALEwEAmpwY"
    "AAAKT2lDQ1BQaG90b3Nob3AgSUNDIHByb2ZpbGUAAHjanVNnVFPpFj333vRCS4iAlEtvUhUI"
    "IFJCi4AUkSYqIQkQSoghodkVUcERRUUEG8igiAOOjoCMFVEsDIoK2AfkIaKOg6OIisr74Xuj"
    "a9a89+bN/rXXPues852zzwfACAyWSDNRNYAMqUIeEeCDx8TG4eQuQIEKJHAAEAizZCFz/SMB"
    "APh+PDwrIsAHvgABeNMLCADATZvAMByH/w/qQplcAYCEAcB0kThLCIAUAEB6jkKmAEBGAYCd"
    "mCZTAKAEAGDLY2LjAFAtAGAnf+bTAICd+Jl7AQBblCEVAaCRACATZYhEAGg7AKzPVopFAFgw"
    "ABRmS8Q5ANgtADBJV2ZIALC3AMDOEAuyAAgMADBRiIUpAAR7AGDIIyN4AISZABRG8lc88Suu"
    "EOcqAAB4mbI8uSQ5RYFbCC1xB1dXLh4ozkkXKxQ2YQJhmkAuwnmZGTKBNA/g88wAAKCRFRHg"
    "g/P9eM4Ors7ONo62Dl8t6r8G/yJiYuP+5c+rcEAAAOF0ftH+LC+zGoA7BoBt/qIl7gRoXgug"
    "dfeLZrIPQLUAoOnaV/Nw+H48PEWhkLnZ2eXk5NhKxEJbYcpXff5nwl/AV/1s+X48/Pf14L7i"
    "JIEyXYFHBPjgwsz0TKUcz5IJhGLc5o9H/LcL//wd0yLESWK5WCoU41EScY5EmozzMqUiiUKS"
    "KcUl0v9k4t8s+wM+3zUAsGo+AXuRLahdYwP2SycQWHTA4vcAAPK7b8HUKAgDgGiD4c93/+8/"
    "/UegJQCAZkmScQAAXkQkLlTKsz/HCAAARKCBKrBBG/TBGCzABhzBBdzBC/xgNoRCJMTCQhBC"
    "CmSAHHJgKayCQiiGzbAdKmAv1EAdNMBRaIaTcA4uwlW4Dj1wD/phCJ7BKLyBCQRByAgTYSHa"
    "iAFiilgjjggXmYX4IcFIBBKLJCDJiBRRIkuRNUgxUopUIFVIHfI9cgI5h1xGupE7yAAygvyG"
    "vEcxlIGyUT3UDLVDuag3GoRGogvQZHQxmo8WoJvQcrQaPYw2oefQq2gP2o8+Q8cwwOgYBzPE"
    "bDAuxsNCsTgsCZNjy7EirAyrxhqwVqwDu4n1Y8+xdwQSgUXACTYEd0IgYR5BSFhMWE7YSKgg"
    "HCQ0EdoJNwkDhFHCJyKTqEu0JroR+cQYYjIxh1hILCPWEo8TLxB7iEPENyQSiUMyJ7mQAkmx"
    "pFTSEtJG0m5SI+ksqZs0SBojk8naZGuyBzmULCAryIXkneTD5DPkG+Qh8lsKnWJAcaT4U+Io"
    "UspqShnlEOU05QZlmDJBVaOaUt2ooVQRNY9aQq2htlKvUYeoEzR1mjnNgxZJS6WtopXTGmgX"
    "aPdpr+h0uhHdlR5Ol9BX0svpR+iX6AP0dwwNhhWDx4hnKBmbGAcYZxl3GK+YTKYZ04sZx1Qw"
    "NzHrmOeZD5lvVVgqtip8FZHKCpVKlSaVGyovVKmqpqreqgtV81XLVI+pXlN9rkZVM1PjqQnU"
    "lqtVqp1Q61MbU2epO6iHqmeob1Q/pH5Z/YkGWcNMw09DpFGgsV/jvMYgC2MZs3gsIWsNq4Z1"
    "gTXEJrHN2Xx2KruY/R27iz2qqaE5QzNKM1ezUvOUZj8H45hx+Jx0TgnnKKeX836K3hTvKeIp"
    "G6Y0TLkxZVxrqpaXllirSKtRq0frvTau7aedpr1Fu1n7gQ5Bx0onXCdHZ4/OBZ3nU9lT3acK"
    "pxZNPTr1ri6qa6UbobtEd79up+6Ynr5egJ5Mb6feeb3n+hx9L/1U/W36p/VHDFgGswwkBtsM"
    "zhg8xTVxbzwdL8fb8VFDXcNAQ6VhlWGX4YSRudE8o9VGjUYPjGnGXOMk423GbcajJgYmISZL"
    "TepN7ppSTbmmKaY7TDtMx83MzaLN1pk1mz0x1zLnm+eb15vft2BaeFostqi2uGVJsuRaplnu"
    "trxuhVo5WaVYVVpds0atna0l1rutu6cRp7lOk06rntZnw7Dxtsm2qbcZsOXYBtuutm22fWFn"
    "Yhdnt8Wuw+6TvZN9un2N/T0HDYfZDqsdWh1+c7RyFDpWOt6azpzuP33F9JbpL2dYzxDP2DPj"
    "thPLKcRpnVOb00dnF2e5c4PziIuJS4LLLpc+Lpsbxt3IveRKdPVxXeF60vWdm7Obwu2o26/u"
    "Nu5p7ofcn8w0nymeWTNz0MPIQ+BR5dE/C5+VMGvfrH5PQ0+BZ7XnIy9jL5FXrdewt6V3qvdh"
    "7xc+9j5yn+M+4zw33jLeWV/MN8C3yLfLT8Nvnl+F30N/I/9k/3r/0QCngCUBZwOJgUGBWwL7"
    "+Hp8Ib+OPzrbZfay2e1BjKC5QRVBj4KtguXBrSFoyOyQrSH355jOkc5pDoVQfujW0Adh5mGL"
    "w34MJ4WHhVeGP45wiFga0TGXNXfR3ENz30T6RJZE3ptnMU85ry1KNSo+qi5qPNo3ujS6P8Yu"
    "ZlnM1VidWElsSxw5LiquNm5svt/87fOH4p3iC+N7F5gvyF1weaHOwvSFpxapLhIsOpZATIhO"
    "OJTwQRAqqBaMJfITdyWOCnnCHcJnIi/RNtGI2ENcKh5O8kgqTXqS7JG8NXkkxTOlLOW5hCep"
    "kLxMDUzdmzqeFpp2IG0yPTq9MYOSkZBxQqohTZO2Z+pn5mZ2y6xlhbL+xW6Lty8elQfJa7OQ"
    "rAVZLQq2QqboVFoo1yoHsmdlV2a/zYnKOZarnivN7cyzytuQN5zvn//tEsIS4ZK2pYZLVy0d"
    "WOa9rGo5sjxxedsK4xUFK4ZWBqw8uIq2Km3VT6vtV5eufr0mek1rgV7ByoLBtQFr6wtVCuWF"
    "fevc1+1dT1gvWd+1YfqGnRs+FYmKrhTbF5cVf9go3HjlG4dvyr+Z3JS0qavEuWTPZtJm6ebe"
    "LZ5bDpaql+aXDm4N2dq0Dd9WtO319kXbL5fNKNu7g7ZDuaO/PLi8ZafJzs07P1SkVPRU+lQ2"
    "7tLdtWHX+G7R7ht7vPY07NXbW7z3/T7JvttVAVVN1WbVZftJ+7P3P66Jqun4lvttXa1ObXHt"
    "xwPSA/0HIw6217nU1R3SPVRSj9Yr60cOxx++/p3vdy0NNg1VjZzG4iNwRHnk6fcJ3/ceDTra"
    "dox7rOEH0x92HWcdL2pCmvKaRptTmvtbYlu6T8w+0dbq3nr8R9sfD5w0PFl5SvNUyWna6YLT"
    "k2fyz4ydlZ19fi753GDborZ752PO32oPb++6EHTh0kX/i+c7vDvOXPK4dPKy2+UTV7hXmq86"
    "X23qdOo8/pPTT8e7nLuarrlca7nuer21e2b36RueN87d9L158Rb/1tWeOT3dvfN6b/fF9/Xf"
    "Ft1+cif9zsu72Xcn7q28T7xf9EDtQdlD3YfVP1v+3Njv3H9qwHeg89HcR/cGhYPP/pH1jw9D"
    "BY+Zj8uGDYbrnjg+OTniP3L96fynQ89kzyaeF/6i/suuFxYvfvjV69fO0ZjRoZfyl5O/bXyl"
    "/erA6xmv28bCxh6+yXgzMV70VvvtwXfcdx3vo98PT+R8IH8o/2j5sfVT0Kf7kxmTk/8EA5jz"
    "/GMzLdsAAAAEZ0FNQQAAsY58+1GTAAAAIGNIUk0AAHolAACAgwAA+f8AAIDpAAB1MAAA6mAA"
    "ADqYAAAXb5JfxUYAAAK2SURBVHjaXJFPbxtFGMZ/s7PejR0ix1CTrIKFEuEolopyKLQ9giLC"
    "JbcIkU+QUxQkDnwFvgNnpJzoLeqpooeocKBIqdQmikpLwREhbf7YZu3d2Zl5ORhbCc9lNO+8"
    "z0/vPK/a2NgAYGdnh5G2t7ffX15erjYajXB3d/fTer1eD4Lg7fJENBWE0fREeXLOx9M8/PXg"
    "IBQRrmp1dbW5ubl5L0mShve+2NrakmazWQc4Sw1PnrchiLn94Rx/db6Pwn6/fw1wfn5+e2Vl"
    "5WatVrtWLwrL3v5v1G7UmZ97Bw/khQsDay3W2nGj1toNBgMPICKICM5aLs7PiAPhvbkbCIp+"
    "AdYjoQw7xwCl1LU/KaWwzmGMwZgc68B48AqcF0KT54RhODY45xjlIiIopcYgAYwd9qA0HiE8"
    "OT7m6eHhGDAa+/93EcFaISsEWxiEmLwQQufctbCMMd57PzaPIQwhaT9DvKUQTZo7wtGII01O"
    "TqqrgNG7eCErDHnhEOfoDgyZ9YRXzXfv3Kmura19mSRJMJpstAXvLSVl6fd69HyJnvV4GQKi"
    "1uJilGWZy7Js4eNbt+7GcUye53jvERG8CHEUU9MFL16/4VJqTJRLeDcEVIBFpVQcaN3IjEFE"
    "MP+dow1ordFRzOvTf7DlCpMTmkBEB0AXOFVBsKCUWlBKlUapa63RWqOCgHKlTDI7Q557Ot2M"
    "l28yTjv5ZQh44E9E0iiK5qvV6ltBEBCGIb1ul9wY2u22Of7j5e8/7x9evKA1/1wqNm3/+Eoq"
    "s1+HAAdHR26p2byfZVm6t7f3wdTUVDNN0+lup/Pg7OLi2ezMzCOt1IP9x7+0Tt6d+a6X3v/b"
    "nTz+pv3TD0/UUrPJwdHReBNfrK8nrVarmiRJZanVejrIsrwUaj5b/ZzWJ+sfXdrKV5FPv331"
    "6N4zgH8HALgyiH/3nwzOAAAAAElFTkSuQmCC")
getfileopen_16Data = fileopen_16.GetData
getfileopen_16Image = fileopen_16.GetImage
getfileopen_16Bitmap = fileopen_16.GetBitmap

#----------------------------------------------------------------------
filesave_16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAABl0"
    "RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAHDSURBVDiNlZO/ixNBFMc/M7u5"
    "hOQUlDRGiCwcXCMoIhyIVoqlhbXYHKJ/g2JnpZ0o/gOihdhYpMmdWKiIWFyrFoFcYeNuk+wy"
    "m533xiJ3+SEnxC8zw4Ph++XzHjyzde/1WxG5yVSBuRbrI/+sta9iEbnxcPsqWx+egqoJqqBK"
    "CGo4rFVBZV6HwM71Bzx78/l2DCAa+P3iMUGEVaXX7gMQA0ZEOPXoOYS/qf+tysssAC+Bk7fu"
    "rmwGkHffFwMUEWE4HK5kTpJkicCIKFEUkSTJ6gRe5wRyMLzBYLCSudvtLs+gOkj7H4LlFryy"
    "/eQjjewrUbF/tMNMn0njDHnrLBunj88JvAhMCqJinyuXL1Gv16nVarNrraUsS/I8Z3f3Pfna"
    "Bt63ALCHOKqKtRHtdpt+v0+v16PZbCIijMdjRqMRRVGAsagqfrEFlYCqYgy0Wq0ZdZqmlGWJ"
    "cw7nHGVZEkIgqFBVC0OcVJ7YTjcky7JZQJZlS2bnHAFQVSrvpwHWmC97P3+d3+ysN8ZZIE1T"
    "Op0O3nvSNF0yO+cgwIljazMCc/HOy3Vj+FS3fvNc/K1uTEwgMD0Hu7GwI4bAnr+Qi6kbkfDj"
    "D/3zDzpnSVtRAAAAAElFTkSuQmCC")
getfilesave_16Data = filesave_16.GetData
getfilesave_16Image = filesave_16.GetImage
getfilesave_16Bitmap = filesave_16.GetBitmap

#----------------------------------------------------------------------
flagged_16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9sCBRMMAqXo1hcAAAHi"
    "SURBVDjLzZLNaxNRFMXPu9NVFi2YXRlEQkwQi5Q2rRQULThQipuJUkFE7B9QqY1LYeiiVPED"
    "JVtXEgTxYzAVF05RQa3WpASsBBupXUShURJJ0nnpNA3XjQxO22jBTc/ywfmd87gH+E+JrR5j"
    "cZOtdA7FsoS/zQctEsL1EV1sC6DqBg/2BqF1BxAJtyOzWIA1t4SpmU/4ao6LvwJOXbrN0cNh"
    "HOrYDSKCoiggUqAoCl5/zOPe83kkjLMeD/2Z3MxMpOBoZwCnj3VC1Q3eBIjFTR7sDbrmuqjj"
    "ReUlhueH8TifRK1RAxGhvyuI6JEDiMVN9gCsVA5ad8BNfrvyDg+c+5AtNq5kLyP5JQkiBUSE"
    "4337YKVy3gbFikQk3O7WTeQTKJZKsKXEqlPHtfdXQUQQQqCvYw+KFekF+Ft9yCwW3D+f8J/E"
    "8rdlfC/8QKX8E2NdFyGEABFhNpuHv9XnBWg9IVhzS26DAXUAo8ELoJUWTBycxND+od8NCE9m"
    "stB6QpsHoeoGT73KcLVaZtuucq0m2XFWeW3N4fX1OjcaDZ5OL/DGK3h0ZvwOP33zoan53MRd"
    "/ue2Vd3g8zcf8rPZLFdtydOpBR69ZTZN3nLfY/FHbKU/o1SW2NXmgxbZixsjUYEdqV8sXNyP"
    "TWcg+QAAAABJRU5ErkJggg==")
getflagged_16Data = flagged_16.GetData
getflagged_16Image = flagged_16.GetImage
getflagged_16Bitmap = flagged_16.GetBitmap

#----------------------------------------------------------------------
help_16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAABl0"
    "RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAM2SURBVDiNbZNbbFRlFIW/8//n"
    "WlEawIZOofQ27YBOqVOCBU1TLkYt+qKihsSEmBgTKwZJTCdBjGmirRck8UENiRHS+OCDCaBH"
    "I4KO1aAFaRla24Jjp2KdoS1Qe5lpp3bO70NLA8Gd7JedvVfWXllLU0pxYxVvawkAzwB1QHB+"
    "3AVEgNa4G+67cV+7DlC8rUUAjYtyzFd3PrrOvifgE5Xl+QCcv5ik80LCO3Ts18xkeqYJeDvu"
    "hr0FgPnjtvuqikItLz3snIoOcKI9Rk//MABrSvJ4oMbPxrWrCL//9dRPnQMdQG3cDXv6PJPG"
    "TetKQ2/uesjZs/9Lro2l2fvcZir9+aSnZvihI06r28nxX2K8u+cR55UDbvWPHfFGoJmi+uZA"
    "cPt7qb+Hx9TT4U9VUX2zerHliMpmPdXTP6RGx9NKKaVOno6pmp0fqYa3vlCJkXEV3L4/XVTf"
    "HJC5/q0vv/Dkhk2j42nt0LGzABiGzmfHz3PYPUd79188vuVuVi7P5fPvexkZTVG6YgklK5bK"
    "U9E/JwRQV1Xh0060xwCwTJ1Ll8dIXk1hWwZVFT4Arv6TxjB0chyLzt+HCK0uEFKIOh0IBsuW"
    "E72YxDAkpmlgWQaWaRAKFLB7x0aUUhw82oFjWwihkbgyyeriPDylgtdFRAgNQ9cxjbm2TIO9"
    "z9Zi6pLDX0XpuzRKjmMihMCxTDQ0NEAAXV2xy4QCBRiGnGNh6Cy+3WYgOcaZ3gRt0UEc28Sx"
    "LXIck/LCZcQGryGk6BJA5NyFhLdlfRm6LtF1iWHoaELwc/cgp3uTSCmxbWMBpNKfR/cfQ142"
    "60UE0PrxkTOZDWtXsf6ulehSoktB7iKH3U/dS8Nj1eQ4JpZlYtsma4rvpMyXy4HWSEYp1Sri"
    "brhvIpVp2vfBN1OvP7+ZUMCHlAIptQW/G/O6BAqX8ERtKa99+O30RCrTFHfDfTdZeWuNv/qN"
    "hgftaGyYaGyYxJVJbHvu58rSZZTkL6bp4Mlpt63n7My/s7VxN+zdEqY7brP37dpxv11V4dPK"
    "C5eiaRrxxCi/9Y9473zyXWZ8crop63k3h+n/4iylqFNKBQGklF2zs9mIUuqWOP8HZvdMlKLb"
    "imEAAAAASUVORK5CYII=")
gethelp_16Data = help_16.GetData
gethelp_16Image = help_16.GetImage
gethelp_16Bitmap = help_16.GetBitmap

#----------------------------------------------------------------------
important_16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QAAAAAAAD5Q7t/AAAA"
    "CXBIWXMAAA3XAAAN1wFCKJt4AAAAB3RJTUUH1QsODC8BdSmQgQAAAlpJREFUOMutk8tvjFEY"
    "h59zvmO+ubTzTVudijKarlx2RVCbBpFYsLPTYCES/gJsELGUCImEFWElIbETCbGQSJSFRCVE"
    "6UXTmplOzUyn893Oa0Gr1UgsPKt387vkvOdVLOHqAXR/T/ZxQuxWO9/MShw5ynEijPkWNf0L"
    "2+9xkz9QC8PzY+6JXMJc87rb3FxPHrc1hXIcJIzxa/OUR6bC2dGpSWXtob67vF1m8GzQGWwz"
    "+nZh92aVzmWRmRBC+R1jFKrVoVqt2fEXb+eV0L9goq8eINGecm8Vdm9SabcFmQ4gFMze8yRP"
    "vcQMnIFIkEpENpHR3bu2GAt3Frz1zvWpR7nuDjftZZFqxEr04iTzllzWc7OF1b1vjnAcQCdh"
    "h1foRGZ+iyXykcpnoncPkdrkMjupx7SuywtwGEBbP2h1W1IQybJUqX6FYA5b+QJ+DeyvgBiS"
    "6VRShO0ARuLYUVqzKJcYqU0Qf3sPxoXv49jiMCiFyuRRLV1o7TpK0QZg0CqyzbpRQROZKyGN"
    "MohFhh8QDT9Y0l2Q+jRSnyZIbqoDwc+ujlMMyiVs5SMyVwSxPze37yLpy4IZOLf8TY0hDOMQ"
    "GALQTT+6UppqhLqjnX8hyBf86nipAtxf/EhDg2p0w7YN6zONspJq7e/qtg7Kq7yJ0uuRib67"
    "7FpcshY5OPbqS6Oa6gz0mi4wZmXttb1h0XgTxaERFzi54hau72GgL8/19p7VPZkuz8mkTMJo"
    "1FxAM4ysPzNWKjUmK/Wk4eiKW1jKjb1c6vXY77lsNJqWyFKb9fnwaZYnp59ylv/ND4XdA/mU"
    "hOKgAAAAAElFTkSuQmCC")
getimportant_16Data = important_16.GetData
getimportant_16Image = important_16.GetImage
getimportant_16Bitmap = important_16.GetBitmap

#----------------------------------------------------------------------
left_16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9oMCAg1B01zVqoAAAAZ"
    "dEVYdENvbW1lbnQAQ3JlYXRlZCB3aXRoIEdJTVBXgQ4XAAAALElEQVQ4y2NgGAV0A/9xSTBR"
    "opkYA/4TMp2JEs2EDGCk1ACiDWGgNCBHOgAATMwFCJh3mZMAAAAASUVORK5CYII=")
getleft_16Data = left_16.GetData
getleft_16Image = left_16.GetImage
getleft_16Bitmap = left_16.GetBitmap

#----------------------------------------------------------------------
minus_16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9sCBRMNFEgnUgcAAABE"
    "SURBVDjLY2CgJThw4MB/QmoYidHs4ODASJKt6DZjEyPLydjkmegaYNjUseBQ95/YAGchNXYG"
    "cSCSmw6onxLJidqBBQCEoT0AtzJV2AAAAABJRU5ErkJggg==")
getminus_16Data = minus_16.GetData
getminus_16Image = minus_16.GetImage
getminus_16Bitmap = minus_16.GetBitmap

#----------------------------------------------------------------------
notchecked_16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9sCBRMLFWl6xRcAAACC"
    "SURBVDjL1dK9DYAgEAXgd+8Yww2cxsrWUeitnMQVHMY9tPAXFTxi5SWEBPheLuSAjyUAUFR+"
    "yoVj7wUA3HYwtPV+SXJdClUHVYVzy04qyqY73l6T3zAZEuZiUp8DrDjagRUnAmw4GmDFiQAb"
    "FokEWLGIxDvIxbdPzMXBKJ/H8181A1IPCymzLqOaAAAAAElFTkSuQmCC")
getnotchecked_16Data = notchecked_16.GetData
getnotchecked_16Image = notchecked_16.GetImage
getnotchecked_16Bitmap = notchecked_16.GetBitmap

#----------------------------------------------------------------------
notflagged_16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9sCBRMMK+daTnsAAAFn"
    "SURBVDjLxZO/SwJxGMYf3+9NDg5uwg0i3BAFJeFQDQ0iBE0XtNhQ/0ARbkVwNLQW4ebWUBCE"
    "QhgUKhSESBYmJBaCCDmG4V1aZvK2RZfaBQ494wuf5/0NDChbr2AoHOVEtoSa3oTTYUfAp2B7"
    "ec72JwNZ1XjG54Hf68a44kK+/IRUroJ45gHV2KbtV4P59QirUwomh2UQCQghQQgBSZKQLlRx"
    "eH6HfW3RxND3zP1gIQSmxzwI+kchqxp3VRAKR1k3DGwEJ3vCRAJEBCKBtcgpJIm+ZkIAkMiW"
    "4Pe6LWEiwuzEEBLZkrmFmt7EuOKyhIkIEyNu1PSm2cDpsCNffrKEiQhXxUc4HXazQcCnIJWr"
    "WMJEhHi6iIBP6T4IWdX4+OKG6/VnNow6Nxov/Pra5Fbrjdvtd+50Pjh5/cA/t2DSwuYen1ze"
    "9oWXtg7Y8rZlVeOVnSM+yxRYf2lwMnvPq7uxvpkH/oX/1yfye61quCYxwQAAAABJRU5ErkJg"
    "gg==")
getnotflagged_16Data = notflagged_16.GetData
getnotflagged_16Image = notflagged_16.GetImage
getnotflagged_16Bitmap = notflagged_16.GetBitmap

#----------------------------------------------------------------------
ok_16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAACXBIWXMAAAsTAAALEwEAmpwY"
    "AAAKT2lDQ1BQaG90b3Nob3AgSUNDIHByb2ZpbGUAAHjanVNnVFPpFj333vRCS4iAlEtvUhUI"
    "IFJCi4AUkSYqIQkQSoghodkVUcERRUUEG8igiAOOjoCMFVEsDIoK2AfkIaKOg6OIisr74Xuj"
    "a9a89+bN/rXXPues852zzwfACAyWSDNRNYAMqUIeEeCDx8TG4eQuQIEKJHAAEAizZCFz/SMB"
    "APh+PDwrIsAHvgABeNMLCADATZvAMByH/w/qQplcAYCEAcB0kThLCIAUAEB6jkKmAEBGAYCd"
    "mCZTAKAEAGDLY2LjAFAtAGAnf+bTAICd+Jl7AQBblCEVAaCRACATZYhEAGg7AKzPVopFAFgw"
    "ABRmS8Q5ANgtADBJV2ZIALC3AMDOEAuyAAgMADBRiIUpAAR7AGDIIyN4AISZABRG8lc88Suu"
    "EOcqAAB4mbI8uSQ5RYFbCC1xB1dXLh4ozkkXKxQ2YQJhmkAuwnmZGTKBNA/g88wAAKCRFRHg"
    "g/P9eM4Ors7ONo62Dl8t6r8G/yJiYuP+5c+rcEAAAOF0ftH+LC+zGoA7BoBt/qIl7gRoXgug"
    "dfeLZrIPQLUAoOnaV/Nw+H48PEWhkLnZ2eXk5NhKxEJbYcpXff5nwl/AV/1s+X48/Pf14L7i"
    "JIEyXYFHBPjgwsz0TKUcz5IJhGLc5o9H/LcL//wd0yLESWK5WCoU41EScY5EmozzMqUiiUKS"
    "KcUl0v9k4t8s+wM+3zUAsGo+AXuRLahdYwP2SycQWHTA4vcAAPK7b8HUKAgDgGiD4c93/+8/"
    "/UegJQCAZkmScQAAXkQkLlTKsz/HCAAARKCBKrBBG/TBGCzABhzBBdzBC/xgNoRCJMTCQhBC"
    "CmSAHHJgKayCQiiGzbAdKmAv1EAdNMBRaIaTcA4uwlW4Dj1wD/phCJ7BKLyBCQRByAgTYSHa"
    "iAFiilgjjggXmYX4IcFIBBKLJCDJiBRRIkuRNUgxUopUIFVIHfI9cgI5h1xGupE7yAAygvyG"
    "vEcxlIGyUT3UDLVDuag3GoRGogvQZHQxmo8WoJvQcrQaPYw2oefQq2gP2o8+Q8cwwOgYBzPE"
    "bDAuxsNCsTgsCZNjy7EirAyrxhqwVqwDu4n1Y8+xdwQSgUXACTYEd0IgYR5BSFhMWE7YSKgg"
    "HCQ0EdoJNwkDhFHCJyKTqEu0JroR+cQYYjIxh1hILCPWEo8TLxB7iEPENyQSiUMyJ7mQAkmx"
    "pFTSEtJG0m5SI+ksqZs0SBojk8naZGuyBzmULCAryIXkneTD5DPkG+Qh8lsKnWJAcaT4U+Io"
    "UspqShnlEOU05QZlmDJBVaOaUt2ooVQRNY9aQq2htlKvUYeoEzR1mjnNgxZJS6WtopXTGmgX"
    "aPdpr+h0uhHdlR5Ol9BX0svpR+iX6AP0dwwNhhWDx4hnKBmbGAcYZxl3GK+YTKYZ04sZx1Qw"
    "NzHrmOeZD5lvVVgqtip8FZHKCpVKlSaVGyovVKmqpqreqgtV81XLVI+pXlN9rkZVM1PjqQnU"
    "lqtVqp1Q61MbU2epO6iHqmeob1Q/pH5Z/YkGWcNMw09DpFGgsV/jvMYgC2MZs3gsIWsNq4Z1"
    "gTXEJrHN2Xx2KruY/R27iz2qqaE5QzNKM1ezUvOUZj8H45hx+Jx0TgnnKKeX836K3hTvKeIp"
    "G6Y0TLkxZVxrqpaXllirSKtRq0frvTau7aedpr1Fu1n7gQ5Bx0onXCdHZ4/OBZ3nU9lT3acK"
    "pxZNPTr1ri6qa6UbobtEd79up+6Ynr5egJ5Mb6feeb3n+hx9L/1U/W36p/VHDFgGswwkBtsM"
    "zhg8xTVxbzwdL8fb8VFDXcNAQ6VhlWGX4YSRudE8o9VGjUYPjGnGXOMk423GbcajJgYmISZL"
    "TepN7ppSTbmmKaY7TDtMx83MzaLN1pk1mz0x1zLnm+eb15vft2BaeFostqi2uGVJsuRaplnu"
    "trxuhVo5WaVYVVpds0atna0l1rutu6cRp7lOk06rntZnw7Dxtsm2qbcZsOXYBtuutm22fWFn"
    "Yhdnt8Wuw+6TvZN9un2N/T0HDYfZDqsdWh1+c7RyFDpWOt6azpzuP33F9JbpL2dYzxDP2DPj"
    "thPLKcRpnVOb00dnF2e5c4PziIuJS4LLLpc+Lpsbxt3IveRKdPVxXeF60vWdm7Obwu2o26/u"
    "Nu5p7ofcn8w0nymeWTNz0MPIQ+BR5dE/C5+VMGvfrH5PQ0+BZ7XnIy9jL5FXrdewt6V3qvdh"
    "7xc+9j5yn+M+4zw33jLeWV/MN8C3yLfLT8Nvnl+F30N/I/9k/3r/0QCngCUBZwOJgUGBWwL7"
    "+Hp8Ib+OPzrbZfay2e1BjKC5QRVBj4KtguXBrSFoyOyQrSH355jOkc5pDoVQfujW0Adh5mGL"
    "w34MJ4WHhVeGP45wiFga0TGXNXfR3ENz30T6RJZE3ptnMU85ry1KNSo+qi5qPNo3ujS6P8Yu"
    "ZlnM1VidWElsSxw5LiquNm5svt/87fOH4p3iC+N7F5gvyF1weaHOwvSFpxapLhIsOpZATIhO"
    "OJTwQRAqqBaMJfITdyWOCnnCHcJnIi/RNtGI2ENcKh5O8kgqTXqS7JG8NXkkxTOlLOW5hCep"
    "kLxMDUzdmzqeFpp2IG0yPTq9MYOSkZBxQqohTZO2Z+pn5mZ2y6xlhbL+xW6Lty8elQfJa7OQ"
    "rAVZLQq2QqboVFoo1yoHsmdlV2a/zYnKOZarnivN7cyzytuQN5zvn//tEsIS4ZK2pYZLVy0d"
    "WOa9rGo5sjxxedsK4xUFK4ZWBqw8uIq2Km3VT6vtV5eufr0mek1rgV7ByoLBtQFr6wtVCuWF"
    "fevc1+1dT1gvWd+1YfqGnRs+FYmKrhTbF5cVf9go3HjlG4dvyr+Z3JS0qavEuWTPZtJm6ebe"
    "LZ5bDpaql+aXDm4N2dq0Dd9WtO319kXbL5fNKNu7g7ZDuaO/PLi8ZafJzs07P1SkVPRU+lQ2"
    "7tLdtWHX+G7R7ht7vPY07NXbW7z3/T7JvttVAVVN1WbVZftJ+7P3P66Jqun4lvttXa1ObXHt"
    "xwPSA/0HIw6217nU1R3SPVRSj9Yr60cOxx++/p3vdy0NNg1VjZzG4iNwRHnk6fcJ3/ceDTra"
    "dox7rOEH0x92HWcdL2pCmvKaRptTmvtbYlu6T8w+0dbq3nr8R9sfD5w0PFl5SvNUyWna6YLT"
    "k2fyz4ydlZ19fi753GDborZ752PO32oPb++6EHTh0kX/i+c7vDvOXPK4dPKy2+UTV7hXmq86"
    "X23qdOo8/pPTT8e7nLuarrlca7nuer21e2b36RueN87d9L158Rb/1tWeOT3dvfN6b/fF9/Xf"
    "Ft1+cif9zsu72Xcn7q28T7xf9EDtQdlD3YfVP1v+3Njv3H9qwHeg89HcR/cGhYPP/pH1jw9D"
    "BY+Zj8uGDYbrnjg+OTniP3L96fynQ89kzyaeF/6i/suuFxYvfvjV69fO0ZjRoZfyl5O/bXyl"
    "/erA6xmv28bCxh6+yXgzMV70VvvtwXfcdx3vo98PT+R8IH8o/2j5sfVT0Kf7kxmTk/8EA5jz"
    "/GMzLdsAAAAEZ0FNQQAAsY58+1GTAAAAIGNIUk0AAHolAACAgwAA+f8AAIDpAAB1MAAA6mAA"
    "ADqYAAAXb5JfxUYAAAIRSURBVHjaYvz//z8DJYCJgULAQqqGitUl97///Sa888hOuRtT7n4g"
    "yYDyVUVXhXmFFV5+/cUgzCt8RTNVZR0jsWGQuTj1vIGivsGq68sZzr++wmDIr8vw6e3H3/Aw"
    "kK8R91Ksk7TCpjl4rs8lAy09g60f1zGcYjvGwC/JzvDu1xuGH6w/vrCo1Elz/f//PzrQIGjW"
    "l+9ffstVizk8an11DKbZZZbNhWDLUN2jXw8wXGI+xyDHI8PA+ZiP4dun77UMjAyzWAR5hB7o"
    "yuuJxtknMPz485P15/+f++SqxQwetb66YdymfSHNP13/OuNlhmtMFxnEmCUY/j1mZvj24Xvd"
    "tYZ7LQwMDAwsf///ZXj6/THDpldrGZS51RgSvBPZ//3/e0a7UflaTnC+/nPeJww3f15h4Psv"
    "wPDx6neG7x+/V1xruNcJcyEzmxHj1JevXj289+2OD4s8IyMjIxODiYopm46irvRXiY8MlxnP"
    "Mfz58o/hzf6PDN/e/ai93nivHTl84LEgUM6RpGKoMMfY1ZBRjUWbgZOVg+HS/7MMn359Zrix"
    "9B7DT9EvtVfDH7XgTIkfOn/M+3zlR/z1I7f+PeW9z3Cf/TYDMxsrw9Pjrxg4+dmwamZgYGBg"
    "+P//PwpWqZRNDdjh+r/3f+N/17W2/41naNaiq0HGWAW16pQKrKeb/tOoVezCp/n///8MjAOe"
    "GwEDAJhGHvWNELyaAAAAAElFTkSuQmCC")
getok_16Data = ok_16.GetData
getok_16Image = ok_16.GetImage
getok_16Bitmap = ok_16.GetBitmap

#----------------------------------------------------------------------
plus_16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9sCBRMNLRci2g8AAABT"
    "SURBVDjLxVPJDQAgCAPjYIzOZvVvCJcaeXIVSiF6aaqKKIczxSLCJdQd2fK1RrbiI+iJU8IQ"
    "5c0EMjzCZ3AdeJfKrIFTErmlvooO7iux+gv/bQFGx0H9h96FygAAAABJRU5ErkJggg==")
getplus_16Data = plus_16.GetData
getplus_16Image = plus_16.GetImage
getplus_16Bitmap = plus_16.GetBitmap

#----------------------------------------------------------------------
preferences_16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH1QkaDBM5i2PCSAAAAfBJREFUOMulkktoE2EU"
    "hb+Z+EyKTRQKgkqwzMaFtt1FrC40FGJm60JwIVSkqLUtElICFQNDQqBrQXRlQIriwomN0GJX"
    "gtI2iUkXFYJVadOXhiBERDozbmaGMR3rwrP7ueece++5P/wnBOcjnVGigArI8Vgi9xdNNJ1R"
    "bI7YUlT7r/YDqKaZq/j6tQHNbLQd6YxiNBp1I51RDPdaw6pFAcR0RolaZKur19vmZhwFePDw"
    "PvFYQgZyACKgDt4cMp4+mzAA9fatETbX15A6Jer1r/das4ndGRUsMYBgFW8MDBqatiXoum7o"
    "ukZhfk4ovC8CyDsFK7R0sBHpu0i5UmG59gUgGY8l7v7zjE68yr80SpUS3Sd7KJYLmBNMArqr"
    "QTCSOgzUrPeVkE7XCYmjR47RbDZ5N/cWtzU8TvH4cJi+UCcdAS/ZmU2Ot39LLn1eOtd9qoeA"
    "P8BKbfnyhfD5+emp11XAABCDkVQXUHs0JjNbXmS2vEjHQR8A5t5yLv8CSZI4e7rX+mR2HiJQ"
    "HB8OM/WmxJamI+7zs1Fv2iOaI8vZJ4850O7nTKgXYMxpAMDuXR72+A7x88cvsvkFgHCrSS6v"
    "Uv1Y/SNsEWBl4zv7fQHa9np4PvMBIPxpcnTaSTRNkmvrqwtA0r5CMJK6BEw4uNvEO+E3N+LV"
    "9uq8VLwAAAAASUVORK5CYII=")
getpreferences_16Data = preferences_16.GetData
getpreferences_16Image = preferences_16.GetImage
getpreferences_16Bitmap = preferences_16.GetBitmap

#----------------------------------------------------------------------
print_16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsRAAALEQF/ZF+RAAAAB3RJTUUH1QsVEg0vn+2FigAAAa1JREFUOMulk82KE0EU"
    "hb97M4u8QHYNWamr0ATjJkQHH8KfdxDBB9AeZ0AQEXREfYZJ8gTJRkbCbLJMVhN3KgQ6fySB"
    "6U6nqlxoGttER7SgFvdS99ThfFXwn0t+LhrN+iEQ/MXc0d079w62uo1m3cVxnNnPXzzL1FEU"
    "uUaz7jYze7vku90uAJ2zUwBeHb+kVt0HoFKpZM7qLoFSqZQOb1bn7BTf93HOZfpbDqy19Ho9"
    "atV9VJWPnQ/cqt1GROj3+5TL5T8LAHieh6oi8j3jYrGIiCAilztwzlEoFNL64YNHKSyR32B8"
    "Ejw+BIJ8Ps/VK9ew1qK6HY+1FhFh8OmcKIoAjjYOgoPgKcYYkiS59BHM5zVUlXfv3wbpNSLC"
    "YDAgjmPa7TbOOcIwZDqdMh6PmUwmjEYjhsMhrVaLr18+ZzNYLBZEFxfMZjN83ycMQwCSJEmt"
    "AxhjGI9ConiVFVBV5osF7XaL5XIJwHq9RkWw1rA2BtUce7kc1drN3RSMMVyv3Ehp/OCCtQ5j"
    "DKqa4t2EnAqsVis8z0ut/sp7Q0FVcc5hrc0InBy/eX3/H37zyTfBI9ln/QvDwwAAAABJRU5E"
    "rkJggg==")
getprint_16Data = print_16.GetData
getprint_16Image = print_16.GetImage
getprint_16Bitmap = print_16.GetBitmap

#----------------------------------------------------------------------
right_16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9oMCAg1IZ9+01cAAAAZ"
    "dEVYdENvbW1lbnQAQ3JlYXRlZCB3aXRoIEdJTVBXgQ4XAAAAKUlEQVQ4y2NgGAU0Bf+JUcRE"
    "qSFMlLqEiVLvEGsAIyUGMNI0FkYBAwMAWLAFCPU80SQAAAAASUVORK5CYII=")
getright_16Data = right_16.GetData
getright_16Image = right_16.GetImage
getright_16Bitmap = right_16.GetBitmap

#----------------------------------------------------------------------
start_16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH1QwGESQhztmtXgAAAiFJREFUOMudk0trEwEU"
    "hc88MskkTSYxmWliExNaSTAjukrR1EhSbIoFwWd0J1gQwUK23fkHXPQXSJeCL7pyo4ggLgxC"
    "TRWxWGygEUr60KQzTTIzuS7EpmIpsXd17uaDc+85QHd4HGC4XToCwAGgCYB6BbC7l/z42Otg"
    "MJgG4OsVwPwRiiwfGT6V+sYwTMeyzC/lD59utlqtz7VaTe/JQjQWk7w+qfjs6RzvkTz+anVl"
    "sr9fGekw9GYgNFCv1Wq0LyCpqpIoOorXCzfYSGSAnTg/wfW53eGN9fXbolNMOkXXu2TyWGN5"
    "ubI3YDiVkjiOKV69co0FAa4+N9SkyqVPpwWXU0z8qP+cNC1rdWhwqLK0tNT8B5DLZqW22S5e"
    "uniZ3dLrMIw2DKMNu8OOeCLB5fPjDiK6QDBTiXj8feZMplEqlcyd3wdkBQ2tDgDQdA0gAgGw"
    "8TZ4PT7opIPIYvyH/IbXE5B4jnUDaO4AFEVG9ftvf7q+BZvNjsPBMCzTxOzsA2vx6+JmLBa9"
    "owRCbwFauzs1ZfyVPlmWySYIAAjR8CB4nsfjJ4+shY8LRjxx9F5mJPuw0+msFgqFFvaKrywr"
    "EAQbdYjw8tULKpfnLbfH8zx7dnRaEOyVXC6r7fXGLkAJQBTtNDNz39J0bWU0O3orIIfmj6vq"
    "xn5B6t4gIGN7u7V5biw1fUI9OQcwm4qiUM9RJqIwAAPAGsMw1n/XkojYg9T5FzBGwR9B4E5i"
    "AAAAAElFTkSuQmCC")
getstart_16Data = start_16.GetData
getstart_16Image = start_16.GetImage
getstart_16Bitmap = start_16.GetBitmap

#----------------------------------------------------------------------
stop_16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH1QwGESgu8tP/wwAAATpJREFUOMvNkl9KAzEQ"
    "h7/spK8WCmY8gFjwFCIeQsRLCOKJRLyCiNcQVARFKYo+rCy0u93dxIf9q62KTxoIzGQyX+Y3"
    "GfjrZXr2xi9zb4BgG280GrG9s3VpjJGfMs/PLsZxHJsPAHWOwWBgTo5Pv03e29/1qkocxwBE"
    "TWDVKSLV47d3VzxO7nl5feYtiUmzFO89ANZanGoLbAGqHUDE1luQSDDAPM/qmKDOLQKcuhYQ"
    "RQIGfAgUZUGapcxm0wpgBbcMsNarIARPWZYUxZwsS5mlU6ZpBbAiaE+C7XrgmDw9AFCWJd57"
    "yqLi+xrYyHPqFgHqOgl5nhMIGCAQ8N63TRQrqFtSgfZ6MF7f/PIbpZMQPlWgiEg4PDr4dg4k"
    "iiLnOkA7ykmS1KMcquNQ2cFUQiq/uREYrgyv+RfrHSlsdbjaRYfOAAAAAElFTkSuQmCC")
getstop_16Data = stop_16.GetData
getstop_16Image = stop_16.GetImage
getstop_16Bitmap = stop_16.GetBitmap

#----------------------------------------------------------------------
up_16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9oMCAg2IbRTgJQAAAAZ"
    "dEVYdENvbW1lbnQAQ3JlYXRlZCB3aXRoIEdJTVBXgQ4XAAAAJUlEQVQ4y2NgGAWDH/wnpICR"
    "SM2MpBrwn1i1jCQ6m3E0VgcjAABB+gQD/lsQ6QAAAABJRU5ErkJggg==")
getup_16Data = up_16.GetData
getup_16Image = up_16.GetImage
getup_16Bitmap = up_16.GetBitmap

